;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


music_music_data:
	.byte 13
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Overworld
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Waterworld
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Underworld
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; Castleworld
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256 ; Cloud
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256 ; Enter in a pipe
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256 ; Starman
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256 ; Death
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256 ; Game Over
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256 ; You saved the princess
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256 ; In an other castle
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,307,256 ; Victory
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,307,256 ; Hurry up

@instruments:
	.word @env10,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env0
	.word @env4,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env13
	.word @env5,@env0,@env0,@env12
	.word @env6,@env0,@env0,@env13
	.word @env7,@env11,@env0,@env13
	.word @env8,@env11,@env0,@env13
	.word @env9,@env0,@env0,@env13

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$07,$c0,$00,$02
@env3:
	.byte $cc,$04,$c0,$00,$02
@env4:
	.byte $cc,$c0,$00,$01
@env5:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env6:
	.byte $c0,$cb,$ca,$c9,$c8,$00,$04
@env7:
	.byte $ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0a
@env8:
	.byte $c8,$c4,$c0,$00,$02
@env9:
	.byte $ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0b
@env10:
	.byte $cf,$00,$00
@env11:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env12:
	.byte $c0,$c2,$00,$01
@env13:
	.byte $c2,$00,$00


; Overworld
@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $88,$22,$83,$22,$89,$22,$89,$22,$83,$22,$89,$27,$95,$23,$95
@ref1:
	.byte $20,$8f,$1c,$8f,$17,$8f,$1c,$89,$1e,$89,$1d,$83,$1c,$89
@ref2:
	.byte $1c,$85,$23,$85,$27,$85,$28,$89,$25,$83,$27,$89,$25,$89,$20,$83
	.byte $21,$83,$1e,$8f
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
@ref5:
	.byte $8b,$2c,$83,$2b,$83,$2a,$83,$27,$89,$28,$89,$20,$83,$21,$83,$23
	.byte $89,$1c,$83,$20,$83,$21,$83
@ref6:
	.byte $8b,$2c,$83,$2b,$83,$2a,$83,$27,$89,$28,$89,$2d,$89,$2d,$83,$2d
	.byte $95
	.byte $ff,$17
	.word @ref5
@ref8:
	.byte $8b,$24,$8f,$21,$8f,$20,$ad
	.byte $ff,$17
	.word @ref5
	.byte $ff,$11
	.word @ref6
	.byte $ff,$17
	.word @ref5
	.byte $ff,$07
	.word @ref8
@ref13:
	.byte $24,$83,$24,$89,$24,$89,$24,$83,$26,$89,$23,$83,$20,$89,$20,$83
	.byte $1c,$95
@ref14:
	.byte $24,$83,$24,$89,$24,$89,$24,$83,$26,$83,$23,$b3
	.byte $ff,$12
	.word @ref13
@ref16:
	.byte $22,$83,$22,$89,$22,$89,$22,$83,$22,$89,$27,$95,$23,$95
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
@ref21:
	.byte $28,$83,$25,$89,$20,$8f,$20,$89,$21,$83,$28,$89,$28,$83,$21,$95
@ref22:
	.byte $23,$85,$2d,$85,$2d,$85,$2d,$85,$2c,$85,$2a,$85,$28,$85,$25,$85
	.byte $21,$85,$20,$95
	.byte $ff,$10
	.word @ref21
@ref24:
	.byte $23,$85,$2a,$87,$2a,$83,$2a,$85,$28,$85,$27,$85,$23,$83,$20,$89
	.byte $20,$83,$1c,$95
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref22
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref24
	.byte $ff,$12
	.word @ref13
	.byte $ff,$0c
	.word @ref14
	.byte $ff,$12
	.word @ref13
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref22
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref24
	.byte $fd
	.word @song0ch0loop

; Overworld
@song0ch1:
@song0ch1loop:
@ref37:
	.byte $88,$2c,$83,$2c,$89,$2c,$89,$28,$83,$2c,$89,$2f,$ad
@ref38:
	.byte $28,$8f,$23,$8f,$20,$8f,$25,$89,$27,$89,$26,$83,$25,$89
@ref39:
	.byte $23,$85,$2c,$85,$2f,$85,$31,$89,$2d,$83,$2f,$89,$2c,$89,$28,$83
	.byte $2a,$83,$27,$8f
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
@ref42:
	.byte $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$24,$83,$25,$83,$28
	.byte $89,$25,$83,$28,$83,$2a,$83
@ref43:
	.byte $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$34,$89,$34,$83,$34
	.byte $95
	.byte $ff,$17
	.word @ref42
@ref45:
	.byte $8b,$2b,$8f,$2a,$8f,$28,$ad
	.byte $ff,$17
	.word @ref42
	.byte $ff,$11
	.word @ref43
	.byte $ff,$17
	.word @ref42
	.byte $ff,$07
	.word @ref45
@ref50:
	.byte $28,$83,$28,$89,$28,$89,$28,$83,$2a,$89,$2c,$83,$28,$89,$25,$83
	.byte $23,$95
@ref51:
	.byte $28,$83,$28,$89,$28,$89,$28,$83,$2a,$83,$2c,$b3
	.byte $ff,$12
	.word @ref50
@ref53:
	.byte $2c,$83,$2c,$89,$2c,$89,$28,$83,$2c,$89,$2f,$ad
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
@ref58:
	.byte $2c,$83,$28,$89,$23,$8f,$24,$89,$25,$83,$2d,$89,$2d,$83,$25,$95
@ref59:
	.byte $27,$85,$31,$85,$31,$85,$31,$85,$2f,$85,$2d,$85,$2c,$85,$28,$85
	.byte $25,$85,$23,$95
	.byte $ff,$10
	.word @ref58
@ref61:
	.byte $27,$85,$2d,$87,$2d,$83,$2d,$85,$2c,$85,$2a,$85,$28,$ad
	.byte $ff,$10
	.word @ref58
	.byte $ff,$14
	.word @ref59
	.byte $ff,$10
	.word @ref58
	.byte $ff,$0e
	.word @ref61
	.byte $ff,$12
	.word @ref50
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$12
	.word @ref50
	.byte $ff,$0c
	.word @ref53
	.byte $ff,$10
	.word @ref58
	.byte $ff,$14
	.word @ref59
	.byte $ff,$10
	.word @ref58
	.byte $ff,$0e
	.word @ref61
	.byte $fd
	.word @song0ch1loop

; Overworld
@song0ch2:
@song0ch2loop:
@ref74:
	.byte $82,$1e,$83,$1e,$89,$1e,$89,$1e,$83,$1e,$89,$2f,$95,$23,$95
@ref75:
	.byte $23,$8f,$20,$8f,$1c,$8f,$21,$89,$23,$89,$22,$83,$21,$89
@ref76:
	.byte $88,$20,$85,$28,$85,$2c,$85,$2d,$89,$2a,$83,$2c,$89,$28,$89,$25
	.byte $83,$27,$83,$23,$8f
@ref77:
	.byte $82,$23,$8f,$20,$8f,$1c,$8f,$21,$89,$23,$89,$22,$83,$21,$89
	.byte $ff,$14
	.word @ref76
@ref79:
	.byte $1c,$8f,$23,$8f,$28,$89,$21,$8f,$28,$83,$28,$89,$21,$89
@ref80:
	.byte $1c,$8f,$20,$8f,$23,$83,$28,$89,$3b,$89,$3b,$83,$3b,$89,$23,$89
	.byte $ff,$0e
	.word @ref79
@ref82:
	.byte $82,$1c,$89,$24,$8f,$26,$8f,$28,$8f,$23,$83,$23,$89,$1c,$89
@ref83:
	.byte $88,$1c,$8f,$23,$8f,$28,$89,$21,$8f,$28,$83,$28,$89,$21,$89
	.byte $ff,$10
	.word @ref80
	.byte $ff,$0e
	.word @ref79
	.byte $ff,$0e
	.word @ref82
@ref87:
	.byte $18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0c
	.word @ref87
@ref90:
	.byte $1e,$83,$1e,$89,$1e,$89,$1e,$83,$1e,$89,$2f,$95,$23,$95
	.byte $ff,$0e
	.word @ref75
	.byte $ff,$14
	.word @ref76
	.byte $ff,$0e
	.word @ref77
	.byte $ff,$14
	.word @ref76
@ref95:
	.byte $82,$1c,$8f,$22,$83,$23,$89,$28,$89,$21,$89,$21,$89,$28,$83,$28
	.byte $83,$21,$89
@ref96:
	.byte $1e,$8f,$21,$83,$23,$89,$27,$89,$23,$89,$23,$89,$28,$83,$28,$83
	.byte $23,$89
@ref97:
	.byte $1c,$8f,$22,$83,$23,$89,$28,$89,$21,$89,$21,$89,$28,$83,$28,$83
	.byte $21,$89
@ref98:
	.byte $88,$23,$8f,$23,$83,$23,$85,$25,$85,$27,$85,$28,$89,$23,$89,$1c
	.byte $95
	.byte $ff,$12
	.word @ref95
	.byte $ff,$12
	.word @ref96
	.byte $ff,$12
	.word @ref97
	.byte $ff,$10
	.word @ref98
@ref103:
	.byte $82,$18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0e
	.word @ref90
	.byte $ff,$12
	.word @ref97
	.byte $ff,$12
	.word @ref96
	.byte $ff,$12
	.word @ref97
	.byte $ff,$10
	.word @ref98
	.byte $fd
	.word @song0ch2loop

; Overworld
@song0ch3:
@song0ch3loop:
@ref111:
	.byte $84,$0c,$89,$86,$0c,$83,$84,$0c,$89,$86,$0c,$83,$84,$0c,$89,$0c
	.byte $8f,$0c,$89,$86,$0c,$83,$0c,$83,$0c,$83
@ref112:
	.byte $03,$89,$0c,$85,$0c,$81,$84,$0c,$89,$86,$0c,$85,$0c,$81,$03,$89
	.byte $0c,$85,$0c,$81,$84,$0c,$89,$86,$0c,$85,$0c,$81
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
@ref132:
	.byte $0c,$8f,$0c,$83,$84,$0c,$89,$86,$0c,$89,$0c,$8f,$0c,$83,$84,$0c
	.byte $89,$86,$0c,$89
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $fd
	.word @song0ch3loop

; Overworld
@song0ch4:
@song0ch4loop:
@ref148:
	.byte $df
@ref149:
	.byte $df
@ref150:
	.byte $df
@ref151:
	.byte $df
@ref152:
	.byte $df
@ref153:
	.byte $df
@ref154:
	.byte $df
@ref155:
	.byte $df
@ref156:
	.byte $df
@ref157:
	.byte $df
@ref158:
	.byte $df
@ref159:
	.byte $df
@ref160:
	.byte $df
@ref161:
	.byte $df
@ref162:
	.byte $df
@ref163:
	.byte $df
@ref164:
	.byte $df
@ref165:
	.byte $df
@ref166:
	.byte $df
@ref167:
	.byte $df
@ref168:
	.byte $df
@ref169:
	.byte $df
@ref170:
	.byte $df
@ref171:
	.byte $df
@ref172:
	.byte $df
@ref173:
	.byte $df
@ref174:
	.byte $df
@ref175:
	.byte $df
@ref176:
	.byte $df
@ref177:
	.byte $df
@ref178:
	.byte $df
@ref179:
	.byte $df
@ref180:
	.byte $df
@ref181:
	.byte $df
@ref182:
	.byte $df
@ref183:
	.byte $df
@ref184:
	.byte $df
	.byte $fd
	.word @song0ch4loop


; Waterworld
@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref185:
	.byte $8a,$1e,$85,$1d,$85,$1c,$85,$1b,$85,$1c,$85,$1d,$85,$1e,$81,$1e
	.byte $81,$1e,$81,$00,$81,$20,$81,$00,$81,$21,$91,$00,$81
@ref186:
	.byte $23,$95,$22,$95,$23,$ad
@ref187:
	.byte $23,$95,$22,$8d,$25,$85,$23,$ad
@ref188:
	.byte $21,$95,$20,$95,$21,$ad
@ref189:
	.byte $21,$95,$1b,$8d,$25,$85,$23,$ad
@ref190:
	.byte $2c,$95,$2a,$95,$29,$ad
@ref191:
	.byte $2a,$95,$29,$95,$28,$ad
@ref192:
	.byte $1c,$95,$21,$85,$23,$85,$27,$85,$27,$81,$27,$81,$27,$89,$21,$81
	.byte $20,$95
	.byte $fd
	.word @song1ch0loop

; Waterworld
@song1ch1:
@song1ch1loop:
@ref193:
	.byte $8a,$1e,$85,$20,$85,$22,$85,$23,$85,$25,$85,$26,$85,$27,$81,$27
	.byte $81,$27,$81,$00,$81,$27,$81,$00,$81,$27,$8d,$23,$85
@ref194:
	.byte $2c,$95,$2b,$95,$2c,$99,$23,$81,$25,$81,$27,$81,$28,$81,$2a,$81
@ref195:
	.byte $2c,$95,$2b,$8d,$2d,$85,$2c,$a9,$23,$81
@ref196:
	.byte $2a,$95,$29,$95,$2a,$99,$23,$81,$25,$81,$27,$81,$28,$81,$29,$81
@ref197:
	.byte $2a,$95,$23,$8d,$2d,$85,$2c,$a9,$23,$81
@ref198:
	.byte $2f,$95,$2f,$95,$2f,$95,$2f,$85,$31,$81,$00,$85,$2f,$81
@ref199:
	.byte $2d,$95,$2d,$95,$2d,$95,$2d,$85,$2f,$81,$00,$85,$2d,$81
@ref200:
	.byte $2c,$95,$25,$85,$27,$85,$2d,$85,$2c,$81,$2c,$81,$2c,$89,$27,$81
	.byte $28,$95
	.byte $fd
	.word @song1ch1loop

; Waterworld
@song1ch2:
@song1ch2loop:
@ref201:
	.byte $80,$00,$bd,$80,$23,$81,$00,$81,$23,$95
@ref202:
	.byte $1c,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	.byte $28,$81,$00,$81,$20,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
	.byte $ff,$30
	.word @ref202
@ref204:
	.byte $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1d,$81,$00,$81
	.byte $22,$81,$00,$81,$26,$81,$00,$81,$1e,$81,$00,$81,$23,$81,$00,$81
	.byte $27,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81
@ref205:
	.byte $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	.byte $28,$81,$00,$81,$17,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
@ref206:
	.byte $1c,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$2a,$81,$00,$81,$1a,$81,$00,$81,$23,$81,$00,$81
	.byte $29,$81,$00,$81,$1d,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81
@ref207:
	.byte $1e,$81,$00,$81,$25,$81,$00,$81,$2d,$81,$00,$81,$1d,$81,$00,$81
	.byte $25,$81,$00,$81,$2d,$81,$00,$81,$1c,$81,$00,$81,$25,$81,$00,$81
	.byte $2d,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$2d,$81,$00,$81
@ref208:
	.byte $10,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$17,$81,$00,$81
	.byte $23,$81,$00,$81,$23,$81,$00,$81,$21,$91,$1b,$81,$1c,$95
	.byte $fd
	.word @song1ch2loop

; Waterworld
@song1ch3:
@song1ch3loop:
@ref209:
	.byte $87,$86,$0c,$85,$84,$0c,$8d,$86,$0c,$81,$0c,$81,$84,$0c,$8d,$86
	.byte $0c,$85,$84,$0c,$8d,$86,$0c,$81,$0c,$81,$84,$0c,$85
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $ff,$15
	.word @ref209
	.byte $fd
	.word @song1ch3loop

; Waterworld
@song1ch4:
@song1ch4loop:
@ref217:
	.byte $df
@ref218:
	.byte $df
@ref219:
	.byte $df
@ref220:
	.byte $df
@ref221:
	.byte $df
@ref222:
	.byte $df
@ref223:
	.byte $df
@ref224:
	.byte $df
	.byte $fd
	.word @song1ch4loop


; Underworld
@song2ch0:
	.byte $fb,$03
@song2ch0loop:
@ref225:
	.byte $f9,$95
@ref226:
	.byte $f9,$95
@ref227:
	.byte $f9,$95
@ref228:
	.byte $c7
	.byte $fd
	.word @song2ch0loop

; Underworld
@song2ch1:
@song2ch1loop:
@ref229:
	.byte $88,$1c,$83,$28,$83,$19,$83,$25,$83,$1a,$83,$26,$a7,$1c,$83,$28
	.byte $83,$19,$83,$25,$83,$1a,$83,$26,$a7
@ref230:
	.byte $15,$83,$21,$83,$12,$83,$1e,$83,$13,$83,$1f,$a7,$15,$83,$21,$83
	.byte $12,$83,$1e,$83,$13,$83,$1f,$9b,$1f,$81,$1e,$81,$1d,$81
@ref231:
	.byte $1c,$89,$1f,$89,$1e,$89,$18,$89,$17,$89,$1d,$89,$1c,$81,$22,$81
	.byte $21,$81,$20,$81,$26,$81,$25,$81,$24,$85,$1f,$85,$1b,$85,$1a,$85
	.byte $19,$85,$18,$85
@ref232:
	.byte $c7
	.byte $fd
	.word @song2ch1loop

; Underworld
@song2ch2:
@song2ch2loop:
@ref233:
	.byte $82,$1c,$83,$28,$83,$19,$83,$25,$83,$1a,$83,$26,$a7,$1c,$83,$28
	.byte $83,$19,$83,$25,$83,$1a,$83,$26,$a7
	.byte $ff,$1e
	.word @ref230
	.byte $ff,$24
	.word @ref231
@ref236:
	.byte $c7
	.byte $fd
	.word @song2ch2loop

; Underworld
@song2ch3:
@song2ch3loop:
@ref237:
	.byte $f9,$95
@ref238:
	.byte $f9,$95
@ref239:
	.byte $f9,$95
@ref240:
	.byte $c7
	.byte $fd
	.word @song2ch3loop

; Underworld
@song2ch4:
@song2ch4loop:
@ref241:
	.byte $f9,$95
@ref242:
	.byte $f9,$95
@ref243:
	.byte $f9,$95
@ref244:
	.byte $c7
	.byte $fd
	.word @song2ch4loop


; Castleworld
@song3ch0:
	.byte $fb,$05
@song3ch0loop:
@ref245:
	.byte $81,$88,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81
	.byte $29
@ref246:
	.byte $81,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81,$29
@ref247:
	.byte $81,$29,$81,$28,$81,$29,$81,$2a,$81,$29,$81,$2a,$81,$29,$81,$28
	.byte $ff,$10
	.word @ref247
@ref249:
	.byte $81,$2d,$81,$2e,$81,$2d,$81,$2c,$81,$2d,$81,$2c,$81,$2b,$81,$2c
	.byte $ff,$10
	.word @ref249
	.byte $fd
	.word @song3ch0loop

; Castleworld
@song3ch1:
@song3ch1loop:
@ref251:
	.byte $88,$23,$26,$23,$25,$23,$24,$23,$25,$23,$26,$23,$27,$23,$26,$23
	.byte $25
@ref252:
	.byte $23,$26,$23,$25,$23,$24,$23,$25,$23,$26,$23,$27,$23,$26,$23,$25
@ref253:
	.byte $22,$25,$22,$24,$22,$25,$22,$26,$22,$25,$22,$26,$22,$25,$22,$24
	.byte $ff,$10
	.word @ref253
@ref255:
	.byte $26,$2a,$26,$2b,$26,$2a,$26,$29,$26,$2a,$26,$29,$26,$28,$26,$29
	.byte $ff,$10
	.word @ref255
	.byte $fd
	.word @song3ch1loop

; Castleworld
@song3ch2:
@song3ch2loop:
@ref257:
	.byte $80,$1f,$9d
@ref258:
	.byte $1e,$8d,$22,$8d
@ref259:
	.byte $21,$9d
@ref260:
	.byte $20,$8d,$26,$8d
@ref261:
	.byte $25,$8d,$20,$8d
@ref262:
	.byte $1f,$8d,$20,$8d
	.byte $fd
	.word @song3ch2loop

; Castleworld
@song3ch3:
@song3ch3loop:
@ref263:
	.byte $9f
@ref264:
	.byte $9f
@ref265:
	.byte $9f
@ref266:
	.byte $9f
@ref267:
	.byte $9f
@ref268:
	.byte $9f
	.byte $fd
	.word @song3ch3loop

; Castleworld
@song3ch4:
@song3ch4loop:
@ref269:
	.byte $9f
@ref270:
	.byte $9f
@ref271:
	.byte $9f
@ref272:
	.byte $9f
@ref273:
	.byte $9f
@ref274:
	.byte $9f
	.byte $fd
	.word @song3ch4loop


; Cloud
@song4ch0:
	.byte $fb,$02
@song4ch0loop:
@ref275:
	.byte $88,$21,$89,$21,$89,$21,$89,$1e,$83,$21,$89,$21,$89,$1e,$83,$21
	.byte $83,$1e,$83,$21,$89
@ref276:
	.byte $20,$89,$20,$89,$20,$89,$1c,$83,$20,$89,$20,$89,$1c,$83,$20,$83
	.byte $1c,$83,$20,$89
	.byte $fd
	.word @song4ch0loop

; Cloud
@song4ch1:
@song4ch1loop:
@ref277:
	.byte $88,$28,$89,$28,$89,$28,$8f,$28,$83,$00,$83,$28,$8f,$28,$89,$28
	.byte $89
@ref278:
	.byte $27,$89,$27,$89,$27,$8f,$27,$83,$00,$83,$27,$8f,$27,$89,$27,$89
	.byte $fd
	.word @song4ch1loop

; Cloud
@song4ch2:
@song4ch2loop:
@ref279:
	.byte $82,$1e,$95,$25,$8f,$2a,$9b,$25,$89,$2a,$89
@ref280:
	.byte $1c,$95,$23,$8f,$28,$9b,$23,$89,$28,$89
	.byte $fd
	.word @song4ch2loop

; Cloud
@song4ch3:
@song4ch3loop:
@ref281:
	.byte $86,$03,$89,$0c,$85,$0c,$81,$84,$0c,$89,$86,$0c,$85,$0c,$81,$03
	.byte $89,$0c,$85,$0c,$81,$84,$0c,$89,$86,$0c,$85,$0c,$81
	.byte $ff,$18
	.word @ref112
	.byte $fd
	.word @song4ch3loop

; Cloud
@song4ch4:
@song4ch4loop:
@ref283:
	.byte $df
@ref284:
	.byte $df
	.byte $fd
	.word @song4ch4loop


; Enter in a pipe
@song5ch0:
	.byte $fb,$03
	.byte $ff,$0e
	.word @ref0
@song5ch0loop:
@ref286:
	.byte $97
	.byte $fd
	.word @song5ch0loop

; Enter in a pipe
@song5ch1:
	.byte $ff,$0c
	.word @ref37
@song5ch1loop:
@ref288:
	.byte $97
	.byte $fd
	.word @song5ch1loop

; Enter in a pipe
@song5ch2:
	.byte $ff,$0e
	.word @ref74
@song5ch2loop:
@ref290:
	.byte $97
	.byte $fd
	.word @song5ch2loop

; Enter in a pipe
@song5ch3:
	.byte $ff,$14
	.word @ref111
@song5ch3loop:
@ref292:
	.byte $97
	.byte $fd
	.word @song5ch3loop

; Enter in a pipe
@song5ch4:
@ref293:
	.byte $df
@song5ch4loop:
@ref294:
	.byte $97
	.byte $fd
	.word @song5ch4loop


; Starman
@song6ch0:
	.byte $fb,$02
@song6ch0loop:
	.byte $ff,$14
	.word @ref275
	.byte $ff,$14
	.word @ref276
	.byte $fd
	.word @song6ch0loop

; Starman
@song6ch1:
@song6ch1loop:
	.byte $ff,$10
	.word @ref277
	.byte $ff,$10
	.word @ref278
	.byte $fd
	.word @song6ch1loop

; Starman
@song6ch2:
@song6ch2loop:
	.byte $ff,$0a
	.word @ref279
	.byte $ff,$0a
	.word @ref280
	.byte $fd
	.word @song6ch2loop

; Starman
@song6ch3:
@song6ch3loop:
	.byte $ff,$18
	.word @ref281
	.byte $ff,$18
	.word @ref112
	.byte $fd
	.word @song6ch3loop

; Starman
@song6ch4:
@song6ch4loop:
@ref303:
	.byte $df
@ref304:
	.byte $df
	.byte $fd
	.word @song6ch4loop


; Death
@song7ch0:
	.byte $fb,$03
@ref305:
	.byte $8e,$25,$26,$27,$90,$24,$8f
@ref306:
	.byte $8e,$22,$83,$29,$89,$29,$83,$29,$85,$27,$85,$26,$85,$22,$83,$1f
	.byte $89,$1f,$83,$1b,$8f
@song7ch0loop:
@ref307:
	.byte $97
	.byte $fd
	.word @song7ch0loop

; Death
@song7ch1:
@ref308:
	.byte $97
@ref309:
	.byte $92,$27,$83,$2d,$89,$2d,$83,$2d,$85,$2c,$85,$2a,$85,$28,$a7
@song7ch1loop:
@ref310:
	.byte $97
	.byte $fd
	.word @song7ch1loop

; Death
@song7ch2:
@ref311:
	.byte $97
@ref312:
	.byte $82,$23,$8f,$23,$83,$23,$85,$25,$85,$27,$85,$28,$89,$23,$89,$1c
	.byte $8f
@song7ch2loop:
@ref313:
	.byte $97
	.byte $fd
	.word @song7ch2loop

; Death
@song7ch3:
@ref314:
	.byte $97
@ref315:
	.byte $d9
@song7ch3loop:
@ref316:
	.byte $97
	.byte $fd
	.word @song7ch3loop

; Death
@song7ch4:
@ref317:
	.byte $97
@ref318:
	.byte $d9
@song7ch4loop:
@ref319:
	.byte $97
	.byte $fd
	.word @song7ch4loop


; Game Over
@song8ch0:
	.byte $fb,$03
@ref320:
	.byte $8a,$20,$83,$00,$89,$1c,$83,$00,$89,$17,$89,$21,$95,$21,$a1,$20
	.byte $83,$1e,$83,$20,$95,$00,$83
@song8ch0loop:
@ref321:
	.byte $97
	.byte $fd
	.word @song8ch0loop

; Game Over
@song8ch1:
@ref322:
	.byte $8a,$28,$83,$00,$89,$23,$83,$00,$89,$20,$89,$25,$85,$27,$85,$25
	.byte $85,$24,$89,$26,$89,$24,$89,$23,$a7
@song8ch1loop:
@ref323:
	.byte $97
	.byte $fd
	.word @song8ch1loop

; Game Over
@song8ch2:
@ref324:
	.byte $82,$23,$8f,$20,$8f,$80,$1c,$89,$21,$95,$1d,$a1,$1c,$a1,$00,$83
@song8ch2loop:
@ref325:
	.byte $97
	.byte $fd
	.word @song8ch2loop

; Game Over
@song8ch3:
@ref326:
	.byte $f9,$9b
@song8ch3loop:
@ref327:
	.byte $97
	.byte $fd
	.word @song8ch3loop

; Game Over
@song8ch4:
@ref328:
	.byte $f9,$9b
@song8ch4loop:
@ref329:
	.byte $97
	.byte $fd
	.word @song8ch4loop


; You saved the princess
@song9ch0:
	.byte $fb,$02
@ref330:
	.byte $8a,$23,$85,$22,$85,$23,$85
@song9ch0loop:
@ref331:
	.byte $8a,$20,$ad,$21,$95,$22,$95,$23,$ad,$28,$95,$2c,$8f,$2c,$83
@ref332:
	.byte $2a,$95,$2c,$95,$2d,$95,$27,$95,$2a,$ad,$28,$95,$23,$85,$22,$85
	.byte $23,$85
	.byte $fd
	.word @song9ch0loop

; You saved the princess
@song9ch1:
@ref333:
	.byte $97
@song9ch1loop:
@ref334:
	.byte $8a,$17,$ad,$19,$95,$1a,$95,$1b,$ad,$20,$95,$23,$95
@ref335:
	.byte $21,$95,$23,$95,$25,$95,$1e,$95,$21,$95,$00,$95,$20,$95,$00,$95
	.byte $fd
	.word @song9ch1loop

; You saved the princess
@song9ch2:
@ref336:
	.byte $80,$1b,$95
@song9ch2loop:
@ref337:
	.byte $80,$1c,$ad,$1e,$95,$1f,$95,$20,$95,$1c,$95,$25,$95,$23,$95
@ref338:
	.byte $21,$95,$20,$95,$1e,$95,$21,$95,$23,$95,$17,$95,$1c,$95,$1b,$95
	.byte $fd
	.word @song9ch2loop

; You saved the princess
@song9ch3:
@ref339:
	.byte $97
@song9ch3loop:
@ref340:
	.byte $f9,$c5
@ref341:
	.byte $f9,$c5
	.byte $fd
	.word @song9ch3loop

; You saved the princess
@song9ch4:
@ref342:
	.byte $97
@song9ch4loop:
@ref343:
	.byte $f9,$c5
@ref344:
	.byte $f9,$c5
	.byte $fd
	.word @song9ch4loop


; In an other castle
@song10ch0:
	.byte $fb,$04
@ref345:
	.byte $8c,$20,$81,$1c,$81,$17,$81,$20,$81,$1c,$81,$17,$81,$20,$81,$20
	.byte $20,$20,$81,$20,$81,$20,$81,$20,$81,$21,$81,$1d,$81,$18,$81,$21
	.byte $81,$1d,$81,$18,$81,$21,$81,$21,$21,$21,$81,$21,$81,$21,$81,$21
	.byte $81
@ref346:
	.byte $23,$81,$1f,$81,$1a,$81,$23,$81,$1f,$81,$1a,$81,$23,$81,$23,$23
	.byte $23,$81,$25,$83,$25,$83,$25,$83,$27,$9d,$00,$87
@song10ch0loop:
@ref347:
	.byte $97
	.byte $fd
	.word @song10ch0loop

; In an other castle
@song10ch1:
@ref348:
	.byte $8c,$28,$81,$23,$81,$20,$81,$28,$81,$23,$81,$20,$81,$28,$95,$29
	.byte $81,$24,$81,$21,$81,$29,$81,$24,$81,$21,$81,$29,$95
@ref349:
	.byte $2b,$81,$26,$81,$23,$81,$2b,$81,$26,$81,$23,$81,$2b,$89,$2d,$83
	.byte $2d,$83,$2d,$83,$2f,$9d,$00,$87
@song10ch1loop:
@ref350:
	.byte $97
	.byte $fd
	.word @song10ch1loop

; In an other castle
@song10ch2:
@ref351:
	.byte $80,$1c,$97,$00,$1c,$83,$00,$1c,$00,$1c,$00,$1c,$00,$1d,$97,$00
	.byte $1d,$83,$00,$1d,$00,$1d,$00,$1d,$00
@ref352:
	.byte $26,$00,$23,$00,$1f,$00,$26,$00,$23,$00,$1f,$00,$26,$00,$26,$83
	.byte $00,$28,$00,$81,$28,$00,$81,$28,$00,$81,$2a,$9d,$00,$87
@song10ch2loop:
@ref353:
	.byte $97
	.byte $fd
	.word @song10ch2loop

; In an other castle
@song10ch3:
@ref354:
	.byte $df
@ref355:
	.byte $df
@song10ch3loop:
@ref356:
	.byte $97
	.byte $fd
	.word @song10ch3loop

; In an other castle
@song10ch4:
@ref357:
	.byte $df
@ref358:
	.byte $df
@song10ch4loop:
@ref359:
	.byte $97
	.byte $fd
	.word @song10ch4loop


; Victory
@song11ch0:
	.byte $fb,$04
@ref360:
	.byte $00,$81,$8a,$14,$81,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$89,$23
	.byte $89,$00,$81,$13,$81,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$89,$24
	.byte $89
@ref361:
	.byte $00,$81,$15,$81,$1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$89,$2a,$89
	.byte $2c,$8f,$00,$9b
@song11ch0loop:
@ref362:
	.byte $af
	.byte $fd
	.word @song11ch0loop

; Victory
@song11ch1:
@ref363:
	.byte $8a,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$81,$2c,$81,$2f,$89,$2c
	.byte $89,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$81,$2b,$81,$30,$89,$2b
	.byte $89
@ref364:
	.byte $1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$81,$2d,$81,$32,$89,$32,$81
	.byte $32,$81,$32,$81,$34,$8f,$00,$9b
@song11ch1loop:
@ref365:
	.byte $af
	.byte $fd
	.word @song11ch1loop

; Victory
@song11ch2:
@ref366:
	.byte $8b,$80,$1c,$81,$20,$81,$23,$81,$2c,$89,$28,$81,$00,$91,$1c,$81
	.byte $1f,$81,$24,$81,$2b,$89,$28,$81,$00,$85
@ref367:
	.byte $8b,$1e,$81,$21,$81,$26,$81,$2d,$89,$2a,$89,$28,$8f,$00,$9b
@song11ch2loop:
@ref368:
	.byte $af
	.byte $fd
	.word @song11ch2loop

; Victory
@song11ch3:
@ref369:
	.byte $df
@ref370:
	.byte $df
@song11ch3loop:
@ref371:
	.byte $af
	.byte $fd
	.word @song11ch3loop

; Victory
@song11ch4:
@ref372:
	.byte $df
@ref373:
	.byte $df
@song11ch4loop:
@ref374:
	.byte $af
	.byte $fd
	.word @song11ch4loop


; Hurry up
@song12ch0:
	.byte $fb,$03
@ref375:
	.byte $8a,$14,$81,$24,$85,$24,$81,$24,$85,$15,$81,$25,$85,$25,$81,$25
	.byte $85,$16,$81,$26,$85,$26,$81,$26,$85,$27,$85,$27,$9d
@song12ch0loop:
@ref376:
	.byte $83
	.byte $fd
	.word @song12ch0loop

; Hurry up
@song12ch1:
@ref377:
	.byte $8a,$20,$81,$2a,$85,$2a,$81,$2a,$85,$21,$81,$2b,$85,$2b,$81,$2b
	.byte $85,$22,$81,$2c,$85,$2c,$81,$2c,$85,$2d,$85,$2d,$9d
@song12ch1loop:
@ref378:
	.byte $83
	.byte $fd
	.word @song12ch1loop

; Hurry up
@song12ch2:
@ref379:
	.byte $82,$27,$81,$33,$85,$33,$81,$33,$85,$28,$81,$34,$85,$34,$81,$34
	.byte $85,$29,$81,$35,$85,$35,$81,$35,$85,$23,$85,$80,$23,$8d,$00,$8d
@song12ch2loop:
@ref380:
	.byte $83
	.byte $fd
	.word @song12ch2loop

; Hurry up
@song12ch3:
@ref381:
	.byte $ef
@song12ch3loop:
@ref382:
	.byte $83
	.byte $fd
	.word @song12ch3loop

; Hurry up
@song12ch4:
@ref383:
	.byte $ef
@song12ch4loop:
@ref384:
	.byte $83
	.byte $fd
	.word @song12ch4loop
