<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="enemy" tilewidth="16" tileheight="24" tilecount="64" columns="16">
 <image source="enemy.png" width="256" height="96"/>
 <tile id="0" type="EN_KOOPA_COLOR_1"/>
 <tile id="1" type="EN_KOOPA_COLOR_2"/>
 <tile id="2" type="EN_BUZZY_BEETLE"/>
 <tile id="3" type="EN_KOOPA_DOESNT_FALL"/>
 <tile id="4" type="EN_UNUSED_KOOPA"/>
 <tile id="5" type="EN_HAMMER_BRO"/>
 <tile id="6" type="EN_GOOMBA"/>
 <tile id="7" type="EN_BLOOPER"/>
 <tile id="8" type="EN_BULLET_BILL"/>
 <tile id="9" type="EN_UNUSED_FLYING_KOOPA"/>
 <tile id="10" type="EN_CHEEP_CHEEP_COLOR_1"/>
 <tile id="11" type="EN_CHEEP_CHEEP_COLOR_2"/>
 <tile id="12" type="EN_POODOBOO"/>
 <tile id="13" type="EN_PIRANHA_PLANT"/>
 <tile id="14" type="EN_JUMPING_KOOPA"/>
 <tile id="15" type="EN_FLYING_KOOPA_VERTICALLY"/>
 <tile id="16" type="EN_FLYING_KOOPA_HORIZONTALLY"/>
 <tile id="17" type="EN_LAKITU"/>
 <tile id="18" type="EN_SPINY"/>
 <tile id="19" type="EN_UNUSED_1"/>
 <tile id="20" type="EN_CHEEP_CHEEP_ZONE"/>
 <tile id="21" type="EN_BOWSER_FIRE_ACTIVATOR"/>
 <tile id="22" type="EN_INTERNAL_FIREWORKS"/>
 <tile id="23" type="EN_BULLET_BILL_OR_UNDERWATER_CHEEP_CHEEP_ZONE"/>
 <tile id="24" type="EN_UNUSED_2"/>
 <tile id="25" type="EN_UNUSED_3"/>
 <tile id="26" type="EN_UNUSED_4"/>
 <tile id="27" type="EN_FIREBAR_CLOCKWISE"/>
 <tile id="28" type="EN_FIREBAR_FAST_CLOCKWISE"/>
 <tile id="29" type="EN_FIREBAR_COUNTERCLOCKWISE"/>
 <tile id="30" type="EN_FIREBAR_FAST_COUNTERCLOCKWISE"/>
 <tile id="31" type="EN_FIREBAR_CLOCKWISE_LONG"/>
 <tile id="32" type="EN_FIREBAR_FAST_CLOCKWISE_LONG"/>
 <tile id="33" type="EN_FIREBAR_COUNTERCLOCKWISE_LONG"/>
 <tile id="34" type="EN_FIREBAR_FAST_COUNTERCLOCKWISE_LONG"/>
 <tile id="35" type="EN_UNUSED_5"/>
 <tile id="36" type="EN_LIFT_BALANCE"/>
 <tile id="37" type="EN_LIFT_UP_DOWN"/>
 <tile id="38" type="EN_LIFT_UP"/>
 <tile id="39" type="EN_LIFT_DOWN"/>
 <tile id="40" type="EN_LIFT_SIDEWAYS"/>
 <tile id="41" type="EN_LIFT_FALLING"/>
 <tile id="42" type="EN_LIFT_FOR_TRAVEL"/>
 <tile id="43" type="EN_LIFT_UP_SHORT"/>
 <tile id="44" type="EN_LIFT_DOWN_SHORT"/>
 <tile id="45" type="EN_BOWSER"/>
 <tile id="46" type="EN_POWERUP"/>
 <tile id="47" type="EN_VINE"/>
 <tile id="48" type="EN_UNUSED_6"/>
 <tile id="49" type="EN_UNUSED_7"/>
 <tile id="50" type="EN_SPRINGBOARD"/>
 <tile id="51" type="EN_INTERNAL"/>
 <tile id="52" type="EN_WARP_ZONE"/>
 <tile id="53" type="EN_RETAINER"/>
 <tile id="54" type="EN_UNUSED_8"/>
 <tile id="55" type="EN_GOOMBA_GROUP_2_HIGHER"/>
 <tile id="56" type="EN_GOOMBA_GROUP_3_HIGHER"/>
 <tile id="57" type="EN_GOOMBA_GROUP_2_LOWER"/>
 <tile id="58" type="EN_GOOMBA_GROUP_3_LOWER"/>
 <tile id="59" type="EN_KOOPA_GROUP_2_HIGHER"/>
 <tile id="60" type="EN_KOOPA_GROUP_3_HIGHER"/>
 <tile id="61" type="EN_KOOPA_GROUP_2_LOWER"/>
 <tile id="62" type="EN_KOOPA_GROUP_3_LOWER"/>
 <tile id="63" type="EN_UNUSED_9"/>
</tileset>
