<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="tiled" tilewidth="16" tileheight="16" tilecount="256" columns="16">
 <image source="mtiles.png" width="256" height="256"/>
 <tile id="0" type="MT_BLANK"/>
 <tile id="1" type="MT_BLACK_METATILE"/>
 <tile id="2" type="MT_BUSH_LEFT"/>
 <tile id="3" type="MT_BUSH_MIDDLE"/>
 <tile id="4" type="MT_BUSH_RIGHT"/>
 <tile id="5" type="MT_MOUNTAIN_LEFT"/>
 <tile id="6" type="MT_MOUNTAIN_LEFT_BOTTOM_MIDDLE_CENTER"/>
 <tile id="7" type="MT_MOUNTAIN_MIDDLE_TOP"/>
 <tile id="8" type="MT_MOUNTAIN_RIGHT"/>
 <tile id="9" type="MT_MOUNTAIN_RIGHT_BOTTOM"/>
 <tile id="10" type="MT_MOUNTAIN_MIDDLE_BOTTOM"/>
 <tile id="11" type="MT_BRIDGE_GUARDRAIL"/>
 <tile id="12" type="MT_CHAIN"/>
 <tile id="13" type="MT_TALL_TREE_TOP_AND_TOP_HALF"/>
 <tile id="14" type="MT_SHORT_TREE_TOP"/>
 <tile id="15" type="MT_TALL_TREE_TOP_AND_BOTTOM_HALF"/>
 <tile id="16" type="MT_WARP_PIPE_END_LEFT_AND_POINTS_UP"/>
 <tile id="17" type="MT_WARP_PIPE_END_RIGHT_AND_POINTS_UP"/>
 <tile id="18" type="MT_DECORATION_PIPE_END_LEFT_AND_POINTS_UP"/>
 <tile id="19" type="MT_DECORATION_PIPE_END_RIGHT_AND_POINTS_UP"/>
 <tile id="20" type="MT_PIPE_SHAFT_LEFT"/>
 <tile id="21" type="MT_PIPE_SHAFT_RIGHT"/>
 <tile id="22" type="MT_TREE_LEDGE_LEFT_EDGE"/>
 <tile id="23" type="MT_TREE_LEDGE_MIDDLE"/>
 <tile id="24" type="MT_TREE_LEDGE_RIGHT_EDGE"/>
 <tile id="25" type="MT_MUSHROOM_LEFT_EDGE"/>
 <tile id="26" type="MT_MUSHROOM_MIDDLE"/>
 <tile id="27" type="MT_MUSHROOM_RIGHT_EDGE"/>
 <tile id="28" type="MT_SIDEWAYS_PIPE_END_TOP"/>
 <tile id="29" type="MT_SIDEWAYS_PIPE_SHAFT_TOP"/>
 <tile id="30" type="MT_SIDEWAYS_PIPE_JOINT_TOP"/>
 <tile id="31" type="MT_SIDEWAYS_PIPE_END_BOTTOM"/>
 <tile id="32" type="MT_SIDEWAYS_PIPE_SHAFT_BOTTOM"/>
 <tile id="33" type="MT_SIDEWAYS_PIPE_JOINT_BOTTOM"/>
 <tile id="34" type="MT_SEAPLANT"/>
 <tile id="35" type="MT_BLANK_USED_ON_BRICKS_OR_BLOCKS_THAT_ARE_HIT"/>
 <tile id="36" type="MT_FLAGPOLE_BALL"/>
 <tile id="37" type="MT_FLAGPOLE_SHAFT"/>
 <tile id="38" type="MT_BLANK_USED_IN_CONJUNCTION_WITH_VINES"/>
 <tile id="39" type="MT_VERTICAL_ROPE"/>
 <tile id="40" type="MT_HORIZONTAL_ROPE"/>
 <tile id="41" type="MT_LEFT_PULLEY"/>
 <tile id="42" type="MT_RIGHT_PULLEY"/>
 <tile id="43" type="MT_BLANK_USED_FOR_BALANCE_ROPE"/>
 <tile id="44" type="MT_CASTLE_TOP"/>
 <tile id="45" type="MT_CASTLE_WINDOW_LEFT"/>
 <tile id="46" type="MT_CASTLE_BRICK_WALL"/>
 <tile id="47" type="MT_CASTLE_WINDOW_RIGHT"/>
 <tile id="48" type="MT_CASTLE_TOP_WITH_BRICK"/>
 <tile id="49" type="MT_ENTRANCE_TOP"/>
 <tile id="50" type="MT_ENTRANCE_BOTTOM"/>
 <tile id="51" type="MT_GREEN_LEDGE_STUMP"/>
 <tile id="52" type="MT_FENCE"/>
 <tile id="53" type="MT_TREE_TRUNK"/>
 <tile id="54" type="MT_MUSHROOM_STUMP_TOP"/>
 <tile id="55" type="MT_MUSHROOM_STUMP_BOTTOM"/>
 <tile id="56" type="MT_BREAKABLE_BRICK_WITH_LINE"/>
 <tile id="57" type="MT_BREAKABLE_BRICK"/>
 <tile id="58" type="MT_BREAKABLE_BRICK_NOT_USED"/>
 <tile id="59" type="MT_CRACKED_ROCK_TERRAIN"/>
 <tile id="60" type="MT_BRICK_WITH_LINE_POWER_UP"/>
 <tile id="61" type="MT_BRICK_WITH_LINE_VINE"/>
 <tile id="62" type="MT_BRICK_WITH_LINE_STAR"/>
 <tile id="63" type="MT_BRICK_WITH_LINE_COINS"/>
 <tile id="64" type="MT_BRICK_WITH_LINE_1_UP"/>
 <tile id="65" type="MT_BRICK_POWER_UP"/>
 <tile id="66" type="MT_BRICK_VINE"/>
 <tile id="67" type="MT_BRICK_STAR"/>
 <tile id="68" type="MT_BRICK_COINS"/>
 <tile id="69" type="MT_BRICK_1_UP"/>
 <tile id="70" type="MT_HIDDEN_BLOCK_1_COIN"/>
 <tile id="71" type="MT_HIDDEN_BLOCK_1_UP"/>
 <tile id="72" type="MT_SOLID_BLOCK_3D_BLOCK"/>
 <tile id="73" type="MT_SOLID_BLOCK_WHITE_WALL"/>
 <tile id="74" type="MT_BRIDGE"/>
 <tile id="75" type="MT_BULLET_BILL_CANNON_BARREL"/>
 <tile id="76" type="MT_BULLET_BILL_CANNON_TOP"/>
 <tile id="77" type="MT_BULLET_BILL_CANNON_BOTTOM"/>
 <tile id="78" type="MT_BLANK_USED_FOR_JUMPSPRING"/>
 <tile id="79" type="MT_HALF_BRICK_USED_FOR_JUMPSPRING"/>
 <tile id="80" type="MT_SOLID_BLOCK_WATER_LEVEL_GREEN_ROCK"/>
 <tile id="81" type="MT_HALF_BRICK"/>
 <tile id="82" type="MT_WATER_PIPE_TOP"/>
 <tile id="83" type="MT_WATER_PIPE_BOTTOM"/>
 <tile id="84" type="MT_FLAG_BALL_RESIDUAL_OBJECT"/>
 <tile id="85" type="MT_CLOUD_LEFT"/>
 <tile id="86" type="MT_CLOUD_MIDDLE"/>
 <tile id="87" type="MT_CLOUD_RIGHT"/>
 <tile id="88" type="MT_CLOUD_BOTTOM_LEFT"/>
 <tile id="89" type="MT_CLOUD_BOTTOM_MIDDLE"/>
 <tile id="90" type="MT_CLOUD_BOTTOM_RIGHT"/>
 <tile id="91" type="MT_WATER_OR_LAVA_TOP"/>
 <tile id="92" type="MT_WATER_OR_LAVA"/>
 <tile id="93" type="MT_CLOUD_LEVEL_TERRAIN"/>
 <tile id="94" type="MT_BOWSERS_BRIDGE"/>
 <tile id="95" type="MT_QUESTION_BLOCK_COIN"/>
 <tile id="96" type="MT_QUESTION_BLOCK_POWER_UP"/>
 <tile id="97" type="MT_COIN"/>
 <tile id="98" type="MT_UNDERWATER_COIN"/>
 <tile id="99" type="MT_EMPTY_BLOCK"/>
 <tile id="100" type="MT_AXE"/>
</tileset>