.segment "ZEROPAGE"

ObjectOffset:           .res 1
FrameCounter:           .res 1
A_B_Buttons:            .res 1
Up_Down_Buttons:        .res 1
Left_Right_Buttons:     .res 1
PreviousA_B_Buttons:    .res 1
GameEngineSubroutine:   .res 1
Enemy_Flag:             .res 7
Enemy_ID:               .res 7
Player_State:           .res 1
Enemy_State:            .res 6
Fireball_State:         .res 2
Block_State:            .res 4
Misc_State:             .res 9
PlayerFacingDir:        .res 1
FirebarSpinDirection  = DestinationPageLoc
DestinationPageLoc:     .res 1
VictoryWalkControl:     .res 4
PowerUpType:            .res 1
FireballBouncingFlag:   .res 2
HammerBroJumpTimer:     .res 9
Player_MovingDir:       .res 1
Enemy_MovingDir:        .res 17
Player_X_Speed        = SprObject_X_Speed
Enemy_X_Speed         = SprObject_X_Speed + 1
YPlatformCenterYPos   = Enemy_X_Speed  
Jumpspring_FixedYPos  = Enemy_X_Speed
RedPTroopaCenterYPos  = Enemy_X_Speed
XMoveSecondaryCounter = Enemy_X_Speed
CheepCheepMoveMFlag   = Enemy_X_Speed
LakituMoveSpeed       = Enemy_X_Speed
FirebarSpinState_Low  = Enemy_X_Speed
BlooperMoveSpeed      = Enemy_X_Speed
PiranhaPlant_Y_Speed  = Enemy_X_Speed
ExplosionGfxCounter   = Enemy_X_Speed
SprObject_X_Speed:      .res 7
Fireball_X_Speed:       .res 2
Block_X_Speed:          .res 4
Misc_X_Speed:           .res 9
Player_PageLoc         = SprObject_PageLoc
Enemy_PageLoc          = SprObject_PageLoc + 1
SprObject_PageLoc:      .res 7
Fireball_PageLoc:       .res 2
Block_PageLoc:          .res 4
Misc_PageLoc:           .res 9
Bubble_PageLoc:         .res 3
Player_X_Position      = SprObject_X_Position
Enemy_X_Position       = SprObject_X_Position + 1
SprObject_X_Position:   .res 7
Fireball_X_Position:    .res 2
Block_X_Position:       .res 4
Misc_X_Position:        .res 9
Bubble_X_Position:      .res 3
Player_Y_Speed         = SprObject_Y_Speed
Enemy_Y_Speed          = SprObject_Y_Speed + 1
SprObject_Y_Speed:      .res 7
XMovePrimaryCounter    = Enemy_Y_Speed
LakituMoveDirection    = Enemy_Y_Speed
FirebarSpinState_High  = Enemy_Y_Speed
BlooperMoveCounter     = Enemy_Y_Speed
PiranhaPlant_MoveFlag  = Enemy_Y_Speed
ExplosionTimerCounter  = Enemy_Y_Speed
Fireball_Y_Speed:       .res 2
Block_Y_Speed:          .res 4
Misc_Y_Speed:           .res 9
Player_Y_HighPos       = SprObject_Y_HighPos
Enemy_Y_HighPos        = SprObject_Y_HighPos + 1
SprObject_Y_HighPos:    .res 7
Fireball_Y_HighPos:     .res 2
Block_Y_HighPos:        .res 4
Misc_Y_HighPos:         .res 9
Bubble_Y_HighPos:       .res 3
Player_Y_Position      = SprObject_Y_Position
Enemy_Y_Position       = SprObject_Y_Position + 1
SprObject_Y_Position:   .res 7
Fireball_Y_Position:    .res 2
Block_Y_Position:       .res 4
Misc_Y_Position:        .res 9
Bubble_Y_Position:      .res 3
AreaDataLow            = AreaData
AreaDataHigh           = AreaData + 1
AreaData:               .res 2
EnemyDataLow           = EnemyData
EnemyDataHigh          = EnemyData + 1
EnemyData:              .res 2
Local_eb:               .res 1
Local_ec:               .res 1
Local_ed:               .res 1
Local_ef:               .res 1
Local_f0:               .res 1
NoteLenLookupTblOfs:    .res 1
Square1SoundBuffer:     .res 1
Square2SoundBuffer:     .res 1
NoiseSoundBuffer:       .res 1
AreaMusicBuffer:        .res 1
MusicDataLow           = MusicData
MusicDataHigh          = MusicData + 1
MusicData:              .res 2
MusicOffset_Square2:    .res 1
MusicOffset_Square1:    .res 1
MusicOffset_Triangle:   .res 1
EventMusicQueue:        .res 1
NoiseSoundQueue:        .res 1
Square2SoundQueue:      .res 1
Square1SoundQueue:      .res 1

temp                  = $0100
songPlaying           = $0101
ScrollH               = $0102
ScrollBit	      = $0103
bank0		      = $0104
ChangeForHUD	      = $0105
PauseSoundQueue       = $0106
AreaMusicQueue        = $0107
VerticalFlipFlag      = $0109
FlagpoleFNum_Y_Pos    = $010d
FlagpoleFNum_YMFDummy = $010e
FlagpoleScore         = $010f
FloateyNum_Control    = $0110
FloateyNum_X_Pos      = $0117
FloateyNum_Y_Pos      = $011e
ShellChainCounter     = $0125
FloateyNum_Timer      = $012c
DigitModifier         = $0134
Sprite_Data           = $0200
Sprite_Y_Position     = $0200
Sprite_Tilenumber     = $0201
Sprite_Attributes     = $0202
Sprite_X_Position     = $0203
VRAM_Buffer1_Offset   = $0300
VRAM_Buffer1          = $0301
VRAM_Buffer2_Offset   = $0340
VRAM_Buffer2          = $0341
BowserBodyControls    = $0363
BowserFeetCounter     = $0364
BowserMovementSpeed   = $0365
BowserOrigXPos        = $0366
BowserFlameTimerCtrl  = $0367
BowserFront_Offset    = $0368
BridgeCollapseOffset  = $0369
BowserGfxFlag         = $036a
FirebarSpinSpeed      = $0388
VineFlagOffset        = $0398
VineHeight            = $0399
VineObjOffset         = $039a
VineStart_Y_Position  = $039d
BalPlatformAlignment  = $03a0
Platform_X_Scroll     = $03a1
HammerThrowingTimer   = $03a2
PlatformCollisionFlag = $03a2
SprObject_Rel_XPos    = $03ad
Player_Rel_XPos       = $03ad
Enemy_Rel_XPos        = $03ae
Fireball_Rel_XPos     = $03af
Bubble_Rel_XPos       = $03b0
Block_Rel_XPos        = $03b1
Misc_Rel_XPos         = $03b3
SprObject_Rel_YPos    = $03b8
Player_Rel_YPos       = $03b8
Enemy_Rel_YPos        = $03b9
Fireball_Rel_YPos     = $03ba
Bubble_Rel_YPos       = $03bb
Block_Rel_YPos        = $03bc
Misc_Rel_YPos         = $03be
SprObject_SprAttrib   = $03c4
Player_SprAttrib      = $03c4
Enemy_SprAttrib       = $03c5
SprObject_OffscrBits  = $03d0
Player_OffscreenBits  = $03d0
Enemy_OffscreenBits   = $03d1
FBall_OffscreenBits   = $03d2
Bubble_OffscreenBits  = $03d3
Block_OffscreenBits   = $03d4
Misc_OffscreenBits    = $03d6
EnemyOffscrBitsMasked = $03d8
Block_Orig_YPos       = $03e4
Block_BBuf_Low        = $03e6
Block_Metatile        = $03e8
Block_PageLoc2        = $03ea
Block_RepFlag         = $03ec
SprDataOffset_Ctrl    = $03ee
Block_ResidualCounter = $03f0
Block_Orig_XPos       = $03f1
AttributeBuffer       = $03f9
SprObject_X_MoveForce = $0400
RedPTroopaOrigXPos    = $0401
YPlatformTopYPos      = $0401
Enemy_X_MoveForce     = $0401
SprObject_YMF_Dummy   = $0416
Player_YMF_Dummy      = $0416
PiranhaPlantUpYPos    = $0417
Enemy_YMF_Dummy       = $0417
BowserFlamePRandomOfs = $0417
Bubble_YMF_Dummy      = $042c
SprObject_Y_MoveForce = $0433
Player_Y_MoveForce    = $0433
PiranhaPlantDownYPos  = $0434
CheepCheepOrigYPos    = $0434
Enemy_Y_MoveForce     = $0434
Block_Y_MoveForce     = $043c
MaximumLeftSpeed      = $0450
MaximumRightSpeed     = $0456
Cannon_Offset         = $046a
Whirlpool_Offset      = $046a
Cannon_PageLoc        = $046b
Whirlpool_PageLoc     = $046b
Cannon_X_Position     = $0471
Whirlpool_LeftExtent  = $0471
Cannon_Y_Position     = $0477
Whirlpool_Length      = $0477
Cannon_Timer          = $047d
Whirlpool_Flag        = $047d
BowserHitPoints       = $0483
StompChainCounter     = $0484
Player_CollisionBits  = $0490
Enemy_CollisionBits   = $0491
Player_BoundBoxCtrl   = $0499
SprObj_BoundBoxCtrl   = $0499
Enemy_BoundBoxCtrl    = $049a
Fireball_BoundBoxCtrl = $04a0
Misc_BoundBoxCtrl     = $04a2
BoundingBox_UL_XPos   = $04ac
BoundingBox_UL_Corner = $04ac
BoundingBox_UL_YPos   = $04ad
BoundingBox_DR_XPos   = $04ae
BoundingBox_LR_Corner = $04ae
BoundingBox_DR_YPos   = $04af
EnemyBoundingBoxCoord = $04b0
Block_Buffer_1        = $0500
Block_Buffer_2        = $05d0
BlockBufferColumnPos  = $06a0
MetatileBuffer        = $06a1
HammerEnemyOffset     = $06ae
JumpCoinMiscOffset    = $06b7
BrickCoinTimerFlag    = $06bc
Misc_Collision_Flag   = $06be
EnemyFrenzyBuffer     = $06cb
SecondaryHardMode     = $06cc
EnemyFrenzyQueue      = $06cd
FireballCounter       = $06ce
DuplicateObj_Offset   = $06cf
LakituReappearTimer   = $06d1
NumberofGroupEnemies  = $06d3
ColorRotateOffset     = $06d4
PlayerGfxOffset       = $06d5
WarpZoneControl       = $06d6
FireworksCounter      = $06d7
MultiLoopCorrectCntr  = $06d9
MultiLoopPassCntr     = $06da
JumpspringForce       = $06db
MaxRangeFromOrigin    = $06dc
BitMFilter            = $06dd
ChangeAreaTimer       = $06de
SprShuffleAmtOffset   = $06e0
SprShuffleAmt         = $06e1
Player_SprDataOffset  = $06e4
SprDataOffset         = $06e4
Enemy_SprDataOffset   = $06e5
Alt_SprDataOffset     = $06ec
Block_SprDataOffset   = $06ec
Bubble_SprDataOffset  = $06ee
FBall_SprDataOffset   = $06f1
Misc_SprDataOffset    = $06f3
SavedJoypadBits       = $06fc
SavedJoypad1Bits      = $06fc
SavedJoypad2Bits      = $06fd
Player_X_Scroll       = $06ff
Player_XSpeedAbsolute = $0700
FrictionAdderHigh     = $0701
FrictionAdderLow      = $0702
RunningSpeed          = $0703
SwimmingFlag          = $0704
Player_X_MoveForce    = $0705
DiffToHaltJump        = $0706
JumpOrigin_Y_HighPos  = $0707
JumpOrigin_Y_Position = $0708
VerticalForce         = $0709
VerticalForceDown     = $070a
PlayerChangeSizeFlag  = $070b
PlayerAnimTimerSet    = $070c
PlayerAnimCtrl        = $070d
JumpspringAnimCtrl    = $070e
FlagpoleCollisionYPos = $070f
PlayerEntranceCtrl    = $0710
FireballThrowingTimer = $0711
DeathMusicLoaded      = $0712
FlagpoleSoundQueue    = $0713
CrouchingFlag         = $0714
GameTimerSetting      = $0715
DisableCollisionDet   = $0716
DemoAction            = $0717
DemoActionTimer       = $0718
PrimaryMsgCounter     = $0719
ScreenLeft_PageLoc    = $071a
ScreenEdge_PageLoc    = $071a
ScreenRight_PageLoc   = $071b
ScreenLeft_X_Pos      = $071c
ScreenEdge_X_Pos      = $071c
ScreenRight_X_Pos     = $071d
ColumnSets            = $071e
AreaParserTaskNum     = $071f
CurrentNTAddr_High    = $0720
CurrentNTAddr_Low     = $0721
Sprite0HitDetectFlag  = $0722
ScrollLock            = $0723
CurrentPageLoc        = $0725
CurrentColumnPos      = $0726
TerrainControl        = $0727
BackloadingFlag       = $0728
BehindAreaParserFlag  = $0729
AreaObjectPageLoc     = $072a
AreaObjectPageSel     = $072b
AreaDataOffset        = $072c
AreaObjOffsetBuffer   = $072d
AreaObjectLength      = $0730
AreaStyle             = $0733
StaircaseControl      = $0734
AreaObjectHeight      = $0735
MushroomLedgeHalfLen  = $0736
EnemyDataOffset       = $0739
EnemyObjectPageLoc    = $073a
EnemyObjectPageSel    = $073b
ScreenRoutineTask     = $073c
ScrollThirtyTwo       = $073d
HorizontalScroll      = $073f
VerticalScroll        = $0740
ForegroundScenery     = $0741
BackgroundScenery     = $0742
CloudTypeOverride     = $0743
BackgroundColorCtrl   = $0744
LoopCommand           = $0745
StarFlagTaskControl   = $0746
TimerControl          = $0747
CoinTallyFor1Ups      = $0748
SecondaryMsgCounter   = $0749
JoypadBitMask         = $074a
AreaType              = $074e
AreaAddrsLOffset      = $074f
AreaPointer           = $0750
EntrancePage          = $0751
AltEntranceControl    = $0752
CurrentPlayer         = $0753
PlayerSize            = $0754
Player_Pos_ForScroll  = $0755
PlayerStatus          = $0756
FetchNewGameTimerFlag = $0757
JoypadOverride        = $0758
GameTimerExpiredFlag  = $0759
OnscreenPlayerInfo    = $075a
NumberofLives         = $075a ;used by current player
HalfwayPage           = $075b
LevelNumber           = $075c ;the actual dash number
Hidden1UpFlag         = $075d
CoinTally             = $075e
WorldNumber           = $075f
AreaNumber            = $0760 ;internal number used to find areas
OffScr_NumberofLives  = $0761 ;used by offscreen player
OffscreenPlayerInfo   = $0761
OffScr_HalfwayPage    = $0762
OffScr_LevelNumber    = $0763
OffScr_Hidden1UpFlag  = $0764
OffScr_CoinTally      = $0765
OffScr_WorldNumber    = $0766
OffScr_AreaNumber     = $0767
ScrollFractional      = $0768
DisableIntermediate   = $0769
PrimaryHardMode       = $076a
WorldSelectNumber     = $076b
OperMode              = $0770
OperMode_Task         = $0772
VRAM_Buffer_AddrCtrl  = $0773
DisableScreenFlag     = $0774
ScrollAmount          = $0775
GamePauseStatus       = $0776
GamePauseTimer        = $0777
Mirror_PPU_CTRL_REG1  = $0778
Mirror_PPU_CTRL_REG2  = $0779
NumberOfPlayers       = $077a
IntervalTimerControl  = $077f
Timers                = $0780
SelectTimer           = $0780
PlayerAnimTimer       = $0781
JumpSwimTimer         = $0782
RunningTimer          = $0783
BlockBounceTimer      = $0784
SideCollisionTimer    = $0785
JumpspringTimer       = $0786
GameTimerCtrlTimer    = $0787
ClimbSideTimer        = $0789
EnemyFrameTimer       = $078a
FrenzyEnemyTimer      = $078f
BowserFireBreathTimer = $0790
StompTimer            = $0791
AirBubbleTimer        = $0792
ScrollIntervalTimer   = $0795
EnemyIntervalTimer    = $0796
BrickCoinTimer        = $079d
InjuryTimer           = $079e
StarInvincibleTimer   = $079f
ScreenTimer           = $07a0
WorldEndTimer         = $07a1
DemoTimer             = $07a2
PseudoRandomBitReg    = $07a7
MusicOffset_Noise     = $07b0
EventMusicBuffer      = $07b1
PauseSoundBuffer      = $07b2
Squ2_NoteLenBuffer    = $07b3
Squ2_NoteLenCounter   = $07b4
Squ2_EnvelopeDataCtrl = $07b5
Squ1_NoteLenCounter   = $07b6
Squ1_EnvelopeDataCtrl = $07b7
Tri_NoteLenBuffer     = $07b8
Tri_NoteLenCounter    = $07b9
Noise_BeatLenCounter  = $07ba
Squ1_SfxLenCounter    = $07bb
Squ2_SfxLenCounter    = $07bd
Sfx_SecondaryCounter  = $07be
Noise_SfxLenCounter   = $07bf
DAC_Counter           = $07c0
NoiseDataLoopbackOfs  = $07c1
NoteLengthTblAdder    = $07c4
AreaMusicBuffer_Alt   = $07c5
PauseModeFlag         = $07c6
GroundMusicHeaderOfs  = $07c7
AltRegContentFlag     = $07ca
DisplayDigits         = $07d7
TopScoreDisplay       = $07d7
ScoreAndCoinDisplay   = $07dd
PlayerScoreDisplay    = $07dd
GameTimerDisplay      = $07f8
WorldSelectEnableFlag = $07fc
ContinueWorld         = $07fd
WarmBootValidation    = $07ff
CHRAnimWait           = $7ff7
CHRAnimCounter        = $7ff8
CHR0                  = $7ff9
CHR2                  = $7ffa
CHR4                  = $7ffb
CHR5                  = $7ffc
CHR6                  = $7ffd
CHR7                  = $7ffe
sleeping	      = $7fff


SQ2_PatternHigh = $f6
SQ2_PatternLow  = $f5
SQ1_PatternHigh = $f8
SQ1_PatternLow  = $f7
TRI_PatternHigh = $07c0
TRI_PatternLow  = $07c1
NOI_PatternHigh = $07c7
NOI_PatternLow  = $07c8
SQ2_Offset      = $f9
SQ1_Offset      = $07c9
TRI_Offset      = $07b0
NOI_Offset      = $0108
CurPattern      = $010a
Instrument_High = $0150
Instrument_Low  = $0151
TriangleMode    = $0152
Instrument_Length = $0153