; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_=music_data_
.endif

music_data_:
	.byte 13
	.word @instruments
	.word @instruments_exp
	.word @samples-4
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,@song1ch5,@song1ch6,@song1ch7,@song1ch8,@song1ch9,@song1ch10,@song1ch11,@song1ch12,@song1ch13,@song1ch14,@song1ch15,@song1ch16,@song1ch17,@song1ch18,@song1ch19 ; 01 : Waterworld
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,@song2ch5,@song2ch6,@song2ch7,@song2ch8,@song2ch9,@song2ch10,@song2ch11,@song2ch12,@song2ch13,@song2ch14,@song2ch15,@song2ch16,@song2ch17,@song2ch18,@song2ch19 ; 02 : Underworld
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,@song3ch5,@song3ch6,@song3ch7,@song3ch8,@song3ch9,@song3ch10,@song3ch11,@song3ch12,@song3ch13,@song3ch14,@song3ch15,@song3ch16,@song3ch17,@song3ch18,@song3ch19 ; 03 : Castleworld
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,@song4ch5,@song4ch6,@song4ch7,@song4ch8,@song4ch9,@song4ch10,@song4ch11,@song4ch12,@song4ch13,@song4ch14,@song4ch15,@song4ch16,@song4ch17,@song4ch18,@song4ch19 ; 04 : Cloud
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,@song5ch5,@song5ch6,@song5ch7,@song5ch8,@song5ch9,@song5ch10,@song5ch11,@song5ch12,@song5ch13,@song5ch14,@song5ch15,@song5ch16,@song5ch17,@song5ch18,@song5ch19 ; 05 : Enter in a pipe
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,@song6ch5,@song6ch6,@song6ch7,@song6ch8,@song6ch9,@song6ch10,@song6ch11,@song6ch12,@song6ch13,@song6ch14,@song6ch15,@song6ch16,@song6ch17,@song6ch18,@song6ch19 ; 06 : Starman
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,@song7ch5,@song7ch6,@song7ch7,@song7ch8,@song7ch9,@song7ch10,@song7ch11,@song7ch12,@song7ch13,@song7ch14,@song7ch15,@song7ch16,@song7ch17,@song7ch18,@song7ch19 ; 07 : Death
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,@song8ch5,@song8ch6,@song8ch7,@song8ch8,@song8ch9,@song8ch10,@song8ch11,@song8ch12,@song8ch13,@song8ch14,@song8ch15,@song8ch16,@song8ch17,@song8ch18,@song8ch19 ; 08 : Game Over
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,@song9ch5,@song9ch6,@song9ch7,@song9ch8,@song9ch9,@song9ch10,@song9ch11,@song9ch12,@song9ch13,@song9ch14,@song9ch15,@song9ch16,@song9ch17,@song9ch18,@song9ch19 ; 09 : You saved the princess
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,@song10ch5,@song10ch6,@song10ch7,@song10ch8,@song10ch9,@song10ch10,@song10ch11,@song10ch12,@song10ch13,@song10ch14,@song10ch15,@song10ch16,@song10ch17,@song10ch18,@song10ch19 ; 0a : In an other castle
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,@song11ch5,@song11ch6,@song11ch7,@song11ch8,@song11ch9,@song11ch10,@song11ch11,@song11ch12,@song11ch13,@song11ch14,@song11ch15,@song11ch16,@song11ch17,@song11ch18,@song11ch19 ; 0b : Victory
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
	.word @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,@song12ch5,@song12ch6,@song12ch7,@song12ch8,@song12ch9,@song12ch10,@song12ch11,@song12ch12,@song12ch13,@song12ch14,@song12ch15,@song12ch16,@song12ch17,@song12ch18,@song12ch19 ; 0c : Hurry up
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env17,@env19,@env24,@env0 ; 00 : Blank
	.word @env27,@env18,@env25,@env0 ; 01 : Death effect
	.word @env22,@env18,@env25,@env0 ; 02 : Death effect 2
	.word @env32,@env19,@env25,@env0 ; 03 : Death instrument
	.word @env1,@env19,@env25,@env0 ; 04 : Instrumental
	.word @env21,@env19,@env25,@env0 ; 05 : Instrumental 2
	.word @env26,@env19,@env29,@env0 ; 06 : Long instrumental
	.word @env5,@env19,@env24,@env0 ; 07 : Noise long
	.word @env20,@env19,@env24,@env0 ; 08 : Noise short
	.word @env14,@env19,@env24,@env0 ; 09 : Triangle

@instruments_exp:
	.word @env23, @env19, @env0 ; 00 : Instrument 2
	.word @env30, @env19
	.word @instrument_epsm_extra_patch10
	.byte $3c,$c0,$08,$18
	.word @env11, @env16, @env0 ; 01 : Instrument 3
	.word @env2, @env12
	.word @instrument_epsm_extra_patch11
	.byte $04,$c0,$00,$20
	.word @env7, @env31, @env0 ; 02 : Instrument 4
	.word @env4, @env15
	.word @instrument_epsm_extra_patch12
	.byte $04,$c0,$00,$20
	.word @env8, @env19, @env0 ; 03 : Instrument 5
	.word @env28, @env25
	.word @instrument_epsm_extra_patch13
	.byte $04,$c0,$00,$20
	.word @env10, @env19, @env0 ; 04 : Instrument 6
	.word @env30, @env19
	.word @instrument_epsm_extra_patch14
	.byte $3c,$c0,$08,$18
	.word @env17, @env19, @env33 ; 05 : Thin 1
	.word @env30, @env19
	.word @instrument_epsm_extra_patch15
	.byte $3e,$c0,$31,$19
	.word @env17, @env19, @env3 ; 06 : Thin 2
	.word @env30, @env19
	.word @instrument_epsm_extra_patch16
	.byte $3e,$c0,$31,$1c
	.word @env9, @env6, @env33 ; 07 : Thin 3
	.word @env30, @env19
	.word @instrument_epsm_extra_patch17
	.byte $3e,$c0,$31,$19
	.word @env17, @env13, @env3 ; 08 : Thin 4
	.word @env30, @env19
	.word @instrument_epsm_extra_patch18
	.byte $36,$c0,$30,$15

@instrument_epsm_extra_patch10:
	.byte $1f,$00,$00,$00,$00,$04,$0c,$1f,$00,$00,$04,$00,$34,$7f,$14,$00,$00,$05,$00,$3f,$7f,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch11:
	.byte $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch12:
	.byte $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch13:
	.byte $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch14:
	.byte $1f,$00,$00,$00,$00,$04,$0c,$1f,$00,$00,$04,$00,$34,$7f,$14,$00,$00,$05,$00,$3f,$7f,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch15:
	.byte $1f,$00,$00,$0f,$00,$31,$09,$1f,$00,$00,$0f,$00,$31,$7f,$1f,$00,$00,$0f,$00,$31,$18,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch16:
	.byte $1f,$00,$00,$0f,$00,$31,$0a,$1f,$00,$00,$0f,$00,$31,$7f,$1f,$00,$00,$0f,$00,$31,$21,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch17:
	.byte $1f,$00,$00,$0f,$00,$31,$09,$1f,$00,$00,$0f,$00,$31,$7f,$1f,$00,$00,$0f,$00,$31,$1a,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch18:
	.byte $1f,$00,$00,$0f,$00,$31,$0a,$1f,$00,$00,$0f,$00,$31,$7f,$1f,$00,$00,$0f,$00,$31,$21,$1f,$00,$00,$0f,$00,$00

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$09
@env2:
	.byte $c1,$c8,$c8,$c1,$00,$03
@env3:
	.byte $00,$c1,$0f,$c2,$c5,$c7,$c7,$c5,$c3,$c1,$bf,$bd,$bc,$bb,$03,$bc,$bf,$00,$03
@env4:
	.byte $c1,$c8,$02,$c1,$00,$03
@env5:
	.byte $00,$cc,$04,$c0,$00,$03
@env6:
	.byte $c0,$cc,$cc,$c0,$00,$00
@env7:
	.byte $00,$cf,$cf,$ce,$cc,$c9,$c6,$c4,$c2,$c0,$00,$09
@env8:
	.byte $00,$ce,$c0,$00,$02
@env9:
	.byte $00,$cf,$cf,$ce,$cd,$02,$cc,$cc,$cb,$02,$ca,$ca,$c9,$c9,$c8,$02,$c7,$c7,$c6,$02,$c5,$03,$c4,$02,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$1e
@env10:
	.byte $00,$cd,$cb,$00,$02
@env11:
	.byte $00,$cf,$ce,$ce,$cd,$cd,$cb,$ca,$c9,$c8,$c6,$c5,$c3,$00,$0c
@env12:
	.byte $c5,$7f,$00,$00
@env13:
	.byte $cc,$7f,$00,$00
@env14:
	.byte $00,$cf,$07,$c0,$00,$03
@env15:
	.byte $cf,$7f,$00,$00
@env16:
	.byte $c0,$c5,$c2,$c0,$00,$03
@env17:
	.byte $00,$cf,$7f,$00,$02
@env18:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env19:
	.byte $c0,$7f,$00,$01
@env20:
	.byte $00,$cc,$c0,$00,$02
@env21:
	.byte $00,$c0,$cb,$ca,$c9,$c8,$00,$05
@env22:
	.byte $00,$c8,$c4,$c0,$00,$03
@env23:
	.byte $00,$cf,$cf,$ce,$07,$cd,$00,$05
@env24:
	.byte $7f,$00,$00
@env25:
	.byte $c2,$7f,$00,$00
@env26:
	.byte $00,$c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1,$c0,$00,$11
@env27:
	.byte $00,$ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0b
@env28:
	.byte $c1,$7f,$00,$00
@env29:
	.byte $c0,$c2,$00,$01
@env30:
	.byte $c8,$7f,$00,$00
@env31:
	.byte $cf,$c5,$ba,$b1,$ae,$00,$04
@env32:
	.byte $00,$ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0c
@env33:
	.byte $00,$c1,$c0,$c0,$00,$01

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf, $47, $ff, $ff, $bf
@song0ref16:
	.byte $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f
	.byte $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f
	.byte $41, $21
	.word @song0ref16
	.byte $41, $21
	.word @song0ref16
	.byte $41, $21
	.word @song0ref16
	.byte $47, $ff, $ff, $9f
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
@song0ref78:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf
@song0ref90:
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch2loop:
	.byte $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch4loop:
	.byte $00, $42
	.word @song0ch4loop
@song0ch5:
	.byte $93, $80, $27, $99, $5a, $89, $24, $99, $5a, $89, $24, $99, $5a, $89, $24, $99, $5a, $89, $24, $85, $5a, $89, $24, $99
	.byte $5a, $89, $26, $99, $5a, $89, $27, $99, $5a, $89, $20, $99, $5a, $89, $2b, $99, $5a, $89, $20, $99, $5a, $89, $27, $99
	.byte $5a, $89, $25, $ad, $5a, $89, $25, $ad, $5a, $89, $2e, $99, $5a, $89, $29, $85, $5a, $89, $30, $85, $5a, $89, $33, $85
	.byte $5a, $89, $29, $85, $5a, $89, $30, $85, $5a, $89, $33, $85, $5a, $89, $29, $85, $5a, $89, $30, $85, $5a, $89, $32, $85
	.byte $5a, $89, $29, $85, $5a, $89, $30, $85, $5a, $89, $32, $85, $5a, $89, $32, $99, $5a, $89, $30, $99, $5a, $89, $2c, $ad
	.byte $5a, $89, $2b, $ad, $5a, $89, $2f, $99, $5a, $89, $32, $99, $5a, $89, $30, $99, $5a, $89, $30, $c1, $5a, $89, $00, $ff
	.byte $ff, $9d, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
@song0ref355:
	.byte $84, $18, $8f, $86, $24, $8f, $82, $20, $8f, $86, $24, $8f, $24, $8f, $84, $18, $8f, $82, $20, $8f, $86, $24, $8f, $84
	.byte $18, $8f, $86, $24, $8f, $82, $20, $8f, $86, $24, $8f, $24, $8f, $84, $18, $8f, $82, $20, $8f, $84, $18, $8f, $18, $8f
	.byte $86, $24, $8f, $82, $20, $8f, $86, $24, $8f, $24, $8f, $84, $18, $8f, $82, $20, $8f, $86, $24, $8f, $84, $18, $8f, $86
	.byte $24, $8f, $82, $20, $8f, $84, $18, $8f, $86, $24, $8f, $84, $18, $8f, $82, $20, $8f, $86, $24, $8f, $84, $18, $8f, $86
	.byte $24, $8f, $82, $20, $8f, $86, $24, $8f, $24, $8f, $84, $18, $8f, $82, $20, $8f, $86, $24, $8f, $84, $18, $8f, $86, $24
	.byte $8f, $82, $20, $8f, $84, $18, $8f, $86, $24, $8f, $84, $18, $8f, $82, $20, $8f, $86, $24, $8f, $84, $18, $8f, $86, $24
	.byte $8f, $82, $20, $8f, $86, $24, $8f, $24, $8f, $84, $18, $8f, $82, $20, $8f, $84, $18, $8f, $86, $24, $8f, $82, $20, $8f
	.byte $86, $24, $8f, $84, $18, $8f, $86, $24, $8f, $82, $20, $8f, $20, $8f, $20, $8f
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $41, $80
	.word @song0ref355
	.byte $00, $ff, $ff, $9d
@song0ch5loop:
	.byte $00, $42
	.word @song0ch5loop
@song0ch6:
	.byte $80, $24, $99, $5a, $89, $2b, $99, $5a, $89, $2e, $ad, $5a, $89, $2d, $ad, $5a, $89, $2b, $f5, $87, $5a, $89, $27, $99
	.byte $5a, $89, $30, $99, $5a, $89, $2f, $99, $5a, $89, $2c, $99, $5a, $89, $30, $99, $5a, $89, $2b, $99, $5a, $89, $27, $85
	.byte $5a, $89, $29, $85, $5a, $89, $2b, $85, $5a, $89, $2c, $c1, $5a, $89, $2b, $e9, $5a, $89, $2b, $99, $5a, $89, $2f, $99
	.byte $5a, $89, $2b, $99, $5a, $89, $26, $99, $5a, $89, $30, $ad, $5a, $89, $23, $ad, $5a, $89, $26, $c1, $5a, $89, $24, $c1
	.byte $5a, $89, $00, $ff, $ff, $9d, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $88
@song0ref687:
	.byte $0c, $8f, $18, $8f, $0c, $8f, $0c, $8f, $16, $8f, $0c, $8f, $18, $8f, $0c, $8f, $0c, $8f, $18, $8f, $0c, $8f, $0c, $8f
	.byte $16, $8f, $0c, $8f, $18, $8f, $0c, $8f, $08, $8f, $14, $8f, $08, $8f, $08, $8f, $14, $8f, $08, $8f, $08, $8f, $14, $8f
	.byte $0d, $8f, $19, $8f, $0d, $8f, $0d, $8f, $16, $8f, $0d, $8f, $16, $8f, $19, $8f, $1d, $8f, $11, $8f, $11, $8f, $1d, $8f
	.byte $11, $8f, $11, $8f, $11, $8f, $1d, $8f, $1c, $8f, $10, $8f, $10, $8f, $1c, $8f, $18, $8f, $10, $8f, $18, $8f, $1c, $8f
	.byte $08, $8f, $08, $8f, $18, $8f, $08, $8f, $08, $8f, $14, $8f, $1a, $8f, $0e, $8f, $1a, $8f, $1a, $8f, $0e, $8f, $1a, $8f
	.byte $18, $8f, $0c, $8f, $16, $8f, $18, $8f
	.byte $41, $80
	.word @song0ref687
	.byte $0c, $8f, $18, $8f, $0c, $8f, $0c, $8f, $16, $8f, $0c, $8f, $16, $8f, $18, $8f, $0c, $8f, $18, $8f, $0c, $8f, $0c, $8f
	.byte $16, $8f, $0c, $8f, $16, $8f, $18, $8f, $0a, $8f, $16, $8f, $0a, $8f, $0a, $8f, $15, $8f, $0a, $8f, $15, $8f, $16, $8f
	.byte $0a, $8f, $16, $8f, $0a, $8f, $0a, $8f, $15, $8f, $0a, $8f, $15, $8f, $16, $8f, $07, $8f, $13, $8f, $07, $8f, $07, $8f
	.byte $11, $8f, $07, $8f, $11, $8f, $13, $8f, $07, $8f, $13, $8f, $07, $8f, $07, $8f, $11, $8f, $07, $8f, $11, $8f, $12, $8f
	.byte $13, $8f, $07, $8f, $07, $8f, $11, $8f, $07, $8f, $07, $8f, $13, $8f, $02, $8f, $00, $8f, $02, $8f, $0e, $8f, $02, $8f
	.byte $0e, $8f, $02, $8f, $0e, $8f, $02, $8f
	.byte $41, $80
	.word @song0ref687
	.byte $41, $80
	.word @song0ref687
	.byte $41, $80
	.word @song0ref687
	.byte $41, $80
	.word @song0ref687
@song0ref958:
	.byte $0d, $8f, $19, $8f, $0d, $8f, $0d, $8f, $17, $8f, $0d, $8f, $19, $8f, $0d, $8f, $0d, $8f, $19, $8f, $0d, $8f, $0d, $8f
	.byte $17, $8f, $0d, $8f, $19, $8f, $0d, $8f, $09, $8f, $15, $8f, $09, $8f, $09, $8f, $15, $8f, $09, $8f, $09, $8f, $15, $8f
	.byte $0e, $8f, $1a, $8f, $0e, $8f, $0e, $8f, $17, $8f, $0e, $8f, $17, $8f, $1a, $8f, $1e, $8f, $12, $8f, $12, $8f, $1e, $8f
	.byte $12, $8f, $12, $8f, $12, $8f, $1e, $8f, $1c, $8f, $10, $8f, $10, $8f, $1c, $8f, $1c, $8f, $10, $8f, $1c, $8f, $1c, $8f
	.byte $09, $8f, $09, $8f, $19, $8f, $09, $8f, $09, $8f, $15, $8f, $1b, $8f, $0f, $8f, $1b, $8f, $1b, $8f, $0f, $8f, $1b, $8f
	.byte $19, $8f, $0d, $8f, $17, $8f, $19, $8f
	.byte $41, $80
	.word @song0ref958
	.byte $41, $80
	.word @song0ref958
	.byte $19, $c5, $19, $ff, $8d, $00, $c5
@song0ch6loop:
	.byte $00, $42
	.word @song0ch6loop
@song0ch7:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
	.byte $88
@song0ref1129:
	.byte $18, $8f, $24, $8f, $18, $8f, $18, $8f, $22, $8f, $18, $8f, $24, $8f, $18, $8f, $18, $8f, $24, $8f, $18, $8f, $18, $8f
	.byte $22, $8f, $18, $8f, $24, $8f, $18, $8f, $14, $8f, $20, $8f, $14, $8f, $14, $8f, $20, $8f, $14, $8f, $14, $8f, $20, $8f
	.byte $19, $8f, $25, $8f, $19, $8f, $19, $8f, $22, $8f, $19, $8f, $22, $8f, $25, $8f, $29, $8f, $1d, $8f, $1d, $8f, $29, $8f
	.byte $1d, $8f, $1d, $8f, $1d, $8f, $29, $8f, $28, $8f, $1c, $8f, $1c, $8f, $28, $8f, $24, $8f, $1c, $8f, $24, $8f, $28, $8f
	.byte $14, $8f, $14, $8f, $24, $8f, $14, $8f, $14, $8f, $20, $8f, $26, $8f, $1a, $8f, $26, $8f, $26, $8f, $1a, $8f, $26, $8f
	.byte $24, $8f, $18, $8f, $22, $8f, $24, $8f
	.byte $41, $80
	.word @song0ref1129
	.byte $18, $8f, $24, $8f, $18, $8f, $18, $8f, $22, $8f, $18, $8f, $22, $8f, $24, $8f, $18, $8f, $24, $8f, $18, $8f, $18, $8f
	.byte $22, $8f, $18, $8f, $22, $8f, $24, $8f, $16, $8f, $22, $8f, $16, $8f, $16, $8f, $21, $8f, $16, $8f, $21, $8f, $22, $8f
	.byte $16, $8f, $22, $8f, $16, $8f, $16, $8f, $21, $8f, $16, $8f, $21, $8f, $22, $8f, $13, $8f, $1f, $8f, $13, $8f, $13, $8f
	.byte $1d, $8f, $13, $8f, $1d, $8f, $1f, $8f, $13, $8f, $1f, $8f, $13, $8f, $13, $8f, $1d, $8f, $13, $8f, $1d, $8f, $1e, $8f
	.byte $1f, $8f, $13, $8f, $13, $8f, $1d, $8f, $13, $8f, $13, $8f, $00, $8f, $0e, $8f, $00, $8f, $0e, $8f, $1a, $8f, $0e, $8f
	.byte $1a, $8f, $0e, $8f, $1a, $8f, $0e, $8f
	.byte $41, $80
	.word @song0ref1129
	.byte $41, $80
	.word @song0ref1129
	.byte $00, $ff, $ff, $9d, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff
	.byte $9f
@song0ref1419:
	.byte $19, $8f, $25, $8f, $19, $8f, $19, $8f, $23, $8f, $19, $8f, $25, $8f, $19, $8f, $19, $8f, $25, $8f, $19, $8f, $19, $8f
	.byte $23, $8f, $19, $8f, $25, $8f, $19, $8f, $15, $8f, $21, $8f, $15, $8f, $15, $8f, $21, $8f, $15, $8f, $15, $8f, $21, $8f
	.byte $1a, $8f, $26, $8f, $1a, $8f, $1a, $8f, $23, $8f, $1a, $8f, $23, $8f, $26, $8f, $2a, $8f, $1e, $8f, $1e, $8f, $2a, $8f
	.byte $1e, $8f, $1e, $8f, $1e, $8f, $2a, $8f, $28, $8f, $1c, $8f, $1c, $8f, $28, $8f, $28, $8f, $1c, $8f, $28, $8f, $28, $8f
	.byte $15, $8f, $15, $8f, $25, $8f, $15, $8f, $15, $8f, $21, $8f, $27, $8f, $1b, $8f, $27, $8f, $27, $8f, $1b, $8f, $27, $8f
	.byte $25, $8f, $19, $8f, $23, $8f, $25, $8f
	.byte $41, $80
	.word @song0ref1419
	.byte $41, $80
	.word @song0ref1419
	.byte $0d, $c5, $0d, $ff, $8d, $00, $c5
@song0ch7loop:
	.byte $00, $42
	.word @song0ch7loop
@song0ch8:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $00, $8f, $8a
@song0ref1580:
	.byte $27, $9f, $5a, $24, $9f, $5a, $24, $9f, $5a, $24, $9f, $5a, $24, $8d, $5a, $24, $9f, $5a, $26, $9f, $5a, $27, $9f, $5a
	.byte $20, $9f, $5a, $2b, $9f, $5a, $20, $9f, $5a, $27, $9f, $5a, $25, $b1, $5a, $25, $b1, $5a, $2e, $9f, $5a, $29, $8d, $5a
	.byte $30, $8d, $5a, $33, $8d, $5a, $29, $8d, $5a, $30, $8d, $5a, $33, $8d, $5a, $29, $8d, $5a, $30, $8d, $5a, $32, $8d, $5a
	.byte $29, $8d, $5a, $30, $8d, $5a, $32, $8d, $5a, $32, $9f, $5a, $30, $9f, $5a, $2c, $b1, $5a, $2b, $b1, $5a, $2f, $9f, $5a
	.byte $32, $9f, $5a, $30, $9f, $5a, $30, $c3, $5a, $00, $8f
	.byte $41, $6b
	.word @song0ref1580
	.byte $41, $69
	.word @song0ref1580
@song0ref1693:
	.byte $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f, $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f, $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f
	.byte $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f, $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f, $2b, $8d, $5a
	.byte $41, $2b
	.word @song0ref1693
	.byte $2b, $8d, $5a, $2b, $8d, $5a, $00, $8f, $2b, $8d, $5a, $2b, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $2b, $8d, $5a, $26
	.byte $8d, $5a, $2b, $8d, $5a, $2b, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $2b, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $24
	.byte $e7, $5a, $26, $8d, $5a, $23, $ff, $9f, $00, $8f
	.byte $41, $6b
	.word @song0ref1580
	.byte $41, $69
	.word @song0ref1580
	.byte $88
@song0ref1804:
	.byte $0c, $8f, $0f, $8f, $13, $8f, $0c, $8f, $16, $b3, $15, $b3, $13, $a1, $0e, $a1, $0f, $a1, $08, $8f, $0f, $8f, $13, $8f
	.byte $18, $a1, $17, $a1, $14, $a1, $18, $a1, $13, $a1, $0f, $8f, $11, $8f, $13, $8f, $14, $c5, $13, $e9, $13, $a1, $17, $a1
	.byte $13, $a1, $0e, $b3, $0c, $b3, $18, $a1, $1a, $b3, $18, $d7
	.byte $41, $3c
	.word @song0ref1804
	.byte $00, $8f, $8a
@song0ref1870:
	.byte $28, $9f, $5a, $25, $9f, $5a, $25, $9f, $5a, $25, $9f, $5a, $25, $8d, $5a, $25, $9f, $5a, $27, $9f, $5a, $28, $9f, $5a
	.byte $21, $9f, $5a, $2c, $9f, $5a, $21, $9f, $5a, $28, $9f, $5a, $26, $b1, $5a, $26, $b1, $5a, $2f, $9f, $5a, $2a, $8d, $5a
	.byte $31, $8d, $5a, $34, $8d, $5a, $2a, $8d, $5a, $31, $8d, $5a, $34, $8d, $5a, $2a, $8d, $5a, $31, $8d, $5a, $34, $8d, $5a
	.byte $2a, $8d, $5a, $31, $8d, $5a, $34, $8d, $5a, $33, $9f, $5a, $31, $9f, $5a, $2d, $b1, $5a, $2c, $b1, $5a, $2f, $9f, $5a
	.byte $2f, $9f, $5a, $31, $9f, $5a, $31, $c3, $5a, $00, $8f
	.byte $41, $6b
	.word @song0ref1870
	.byte $41, $69
	.word @song0ref1870
	.byte $2f, $c5, $31, $ff, $8d, $00, $c5
@song0ch8loop:
	.byte $00, $42
	.word @song0ch8loop
@song0ch9:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $8a
@song0ref2008:
	.byte $24, $9f, $5a, $2b, $9f, $5a, $2e, $b1, $5a, $2d, $b1, $5a, $2b, $e9, $8f, $5a, $27, $9f, $5a, $30, $9f, $5a, $2f, $9f
	.byte $5a, $2c, $9f, $5a, $30, $9f, $5a, $2b, $9f, $5a, $27, $8d, $5a, $29, $8d, $5a, $2b, $8d, $5a, $2c, $c3, $5a, $2b, $e7
	.byte $5a, $2b, $9f, $5a, $2f, $9f, $5a, $2b, $9f, $5a, $26, $9f, $5a, $30, $b1, $5a, $23, $b1, $5a, $26, $c3, $5a, $24, $c3
	.byte $5a
	.byte $41, $49
	.word @song0ref2008
	.byte $41, $49
	.word @song0ref2008
	.byte $24, $8d, $5a, $27, $8d, $5a, $2b, $8d, $5a, $24, $8d, $5a, $27, $8d, $5a, $2b, $8d, $5a, $24, $8d, $5a, $27, $8d, $5a
	.byte $2b, $8d, $5a, $1f, $8d, $5a, $27, $8d, $5a, $2b, $8d, $5a, $24, $8d, $5a, $27, $8d, $5a, $2b, $8d, $5a, $1f, $8f, $8f
	.byte $5a, $26, $8d, $5a, $2b, $8d, $5a, $22, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $22, $8d, $5a, $26, $8d, $5a, $2b, $8d
	.byte $5a, $22, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $22, $8d, $5a, $26, $8d, $5a, $2b, $8d, $5a, $26, $8d, $5a, $26, $8d
	.byte $5a, $22, $8d, $5a, $26, $8d, $5a, $22, $8d, $5a, $26, $8d, $5a, $22, $8d, $5a, $26, $8d, $5a, $26, $8d, $5a, $00, $8f
	.byte $26, $8d, $5a, $26, $8d, $5a, $00, $8f, $22, $8d, $5a, $26, $8d, $5a, $00, $8f, $22, $8d, $5a, $2b, $e7, $5a, $2b, $8d
	.byte $5a, $2b, $ff, $9f
	.byte $41, $49
	.word @song0ref2008
	.byte $41, $2c
	.word @song0ref2008
	.byte $c5, $2b, $e7, $5a, $2b, $9f, $5a, $2f, $9f, $5a, $2b, $9f, $5a, $26, $9f, $5a, $30, $b1, $5a, $23, $b1, $5a, $26, $c3
	.byte $5a, $24, $c3, $5a
	.byte $41, $80
	.word @song0ref687
	.byte $41, $80
	.word @song0ref687
@song0ref2275:
	.byte $25, $9f, $5a, $2c, $9f, $5a, $2f, $b1, $5a, $2e, $b1, $5a, $2c, $e9, $8f, $5a, $28, $9f, $5a, $31, $9f, $5a, $30, $9f
	.byte $5a, $2d, $9f, $5a, $31, $9f, $5a, $2c, $9f, $5a, $28, $8d, $5a, $2a, $8d, $5a, $2c, $8d, $5a, $2d, $c5, $2c, $e7, $5a
	.byte $2c, $9f, $5a, $2f, $9f, $5a, $2c, $9f, $5a, $27, $9f, $5a, $31, $b1, $5a, $23, $b1, $5a, $27, $c3, $5a, $25, $c3, $5a
	.byte $41, $48
	.word @song0ref2275
	.byte $41, $48
	.word @song0ref2275
	.byte $25, $c5, $25, $ff, $8d, $00, $c5
@song0ch9loop:
	.byte $00, $42
	.word @song0ch9loop
@song0ch10:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $8a, $18, $ff, $ff, $9d, $14, $ff, $8d, $19, $ff, $8d, $1d
	.byte $e9, $1c, $ff, $b1, $14, $e9, $1a, $e9, $18, $c5
	.byte $41, $80
	.word @song0ref687
	.byte $00, $ff, $ff, $9d, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff
	.byte $9f
	.byte $41, $80
	.word @song0ref687
	.byte $41, $80
	.word @song0ref687
	.byte $90, $30, $f9, $5a, $35, $b1, $5a, $33, $b1, $5a, $32
@song0ref2444:
	.byte $b1, $5a, $2c, $ff, $8b, $5a, $31, $b1, $5a, $30, $b1, $5a, $2e, $9f, $5a, $27, $8d, $5a, $2c, $8d, $5a, $30, $8d, $5a
	.byte $33, $9f, $5a, $32, $8d, $5a, $30, $c3, $5a, $2b, $9f, $5a, $2f, $9f, $5a, $32, $9f, $5a, $32, $c3, $5a, $30, $c3, $5a
	.byte $2f, $8d, $5a, $2b, $8d, $5a, $00, $8f, $30, $d5, $5a, $30, $f9, $5a, $35, $b1, $5a, $33, $b1, $5a, $35
	.byte $41, $39
	.word @song0ref2444
	.byte $b3, $2f, $8f, $30, $8f, $8a
	.byte $41, $80
	.word @song0ref958
	.byte $41, $7a
	.word @song0ref958
	.byte $8c, $20, $8f, $23, $8f, $25, $8f, $20, $8f, $25, $8f, $28, $8f, $20, $8f, $2c, $b3, $2a, $b3, $28, $e9, $1c, $8f, $21
	.byte $8f, $28, $8f, $2d, $a1, $2c, $a1, $28, $a1, $2d, $a1, $26, $a1, $28, $8f, $2a, $8f, $2c, $8f, $8e, $2d, $8f, $31, $8f
	.byte $34, $8f, $2d, $8f, $31, $8f, $34, $8f, $2c, $8f, $31, $8f, $34, $8f, $2c, $8f, $31, $8f, $34, $8f, $33, $a1, $31, $a1
	.byte $2d, $a1, $00, $8f, $2c, $a1, $00, $8f, $2f, $a1, $2f, $a1, $31, $a1, $31, $b3, $00, $8f, $ff, $ff, $9f
@song0ch10loop:
	.byte $00, $42
	.word @song0ch10loop
@song0ch11:
	.byte $41, $24
	.word @song0ref78
	.byte $8c, $30, $ff, $af, $5a, $30, $9f, $5a, $32, $8d, $5a, $33, $b1, $5a, $2c, $ff, $8b, $5a, $31, $c3, $5a, $33, $c3, $5a
	.byte $30, $ff, $f7, $5a, $00, $a1, $2c, $b1, $5a, $2b, $c3, $5a, $00, $8f, $3b, $c3, $5a, $3c, $c3, $5a, $30, $e7, $5a, $2f
	.byte $8d, $5a, $30, $b1, $5a, $30, $8d, $5a, $24, $8d, $5a, $32, $8d, $5a, $33, $9f, $5a, $32, $8f, $b3, $5a, $2e, $b1, $5a
	.byte $26, $9f, $5a, $32, $9f, $5a, $30, $8d, $5a, $2e, $c3, $5a, $2e, $8d, $5a, $30, $b1, $5a, $2b, $b1, $5a, $2b, $9f, $5a
	.byte $32, $a1, $30, $8f, $2e, $b1, $5a, $30, $9f, $5a, $32, $e7, $5a, $30, $8d, $5a, $32, $ff, $9d, $5a, $00, $ff, $ff, $9d
	.byte $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $8e, $24, $8f, $27, $8f, $2b, $8f, $24, $8f, $2e, $b3, $2d, $b3, $2b, $a1
	.byte $26, $a1, $27, $a1, $20, $8f, $27, $8f, $2b, $8f, $30, $a1, $2f, $a1, $2c, $a1, $30, $a1, $2b, $a1, $27, $8f, $29, $8f
	.byte $2b, $8f, $2c, $8f, $30, $8f, $33, $8f, $2c, $8f, $30, $8f, $33, $8f, $2b, $8f, $30, $8f, $32, $8f, $2b, $8f, $30, $8f
	.byte $32, $8f, $32, $a1, $30, $a1, $2c, $a1, $24, $8f, $2b, $a1, $1f, $8f, $2f, $a1, $32, $a1, $30, $a1, $30, $c5, $00, $ff
	.byte $ff, $9d
	.byte $41, $21
	.word @song0ref90
	.byte $25, $8f, $28, $8f, $2c, $8f, $25, $8f, $2f, $b3, $2e, $b3, $2c, $a1, $27, $a1, $28, $a1, $21, $8f, $28, $8f, $2c, $8f
	.byte $31, $8f, $21, $8f, $30, $8f, $28, $8f, $2d, $8f, $26, $8f, $31, $8f, $00, $8f, $2c, $8f, $00, $8f, $28, $8f, $2a, $8f
	.byte $2c, $8f, $2d, $b3, $00, $8f, $2c, $a1, $00, $c5, $2c, $8f, $00, $8f, $2f, $8f, $00, $8f, $2c, $8f, $00, $8f, $2d, $8f
	.byte $00, $a1, $2c, $8f, $00, $a1, $2f, $8f, $00, $8f, $2f, $8f, $00, $8f, $31, $8f, $00, $8f, $31, $8f, $00, $b3, $ff, $ff
	.byte $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
@song0ch11loop:
	.byte $00, $42
	.word @song0ch11loop
@song0ch12:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch12loop:
	.byte $00, $42
	.word @song0ch12loop
@song0ch13:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch13loop:
	.byte $00, $42
	.word @song0ch13loop
@song0ch14:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch14loop:
	.byte $00, $42
	.word @song0ch14loop
@song0ch15:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch15loop:
	.byte $00, $42
	.word @song0ch15loop
@song0ch16:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch16loop:
	.byte $00, $42
	.word @song0ch16loop
@song0ch17:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch17loop:
	.byte $00, $42
	.word @song0ch17loop
@song0ch18:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch18loop:
	.byte $00, $42
	.word @song0ch18loop
@song0ch19:
	.byte $41, $2d
	.word @song0ref78
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $41, $21
	.word @song0ref90
	.byte $ff, $ff, $9f
@song0ch19loop:
	.byte $00, $42
	.word @song0ch19loop
@song1ch0:
@song1ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8c, $1b, $9d, $1a, $9d, $19, $9d, $18, $9d, $19, $9d, $1a
	.byte $9d, $1b, $8d, $1b, $8d, $1b, $8d, $00, $8d, $1d, $8d, $00, $8d, $1e, $cd, $00, $8d, $47, $20, $dd, $1f, $dd, $20, $ff
	.byte $bd, $47, $20, $dd, $1f, $bd, $22, $9d, $20, $ff, $bd, $47, $1e, $dd, $1d, $dd, $1e, $ff, $bd, $47, $1e, $dd, $18, $bd
	.byte $22, $9d, $20, $ff, $bd, $47, $29, $dd, $27, $dd, $26, $ff, $bd, $47, $27, $dd, $26, $dd, $25, $ff, $bd, $47, $19, $dd
	.byte $1e, $9d, $20, $9d, $24, $9d, $24, $8d, $24, $8d, $24, $ad, $1e, $8d, $1d, $dd, $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $8c, $1b, $9d, $1d, $9d, $1f, $9d, $20, $9d, $22, $9d, $23, $9d, $24, $8d, $24, $8d, $24, $8d, $00, $8d, $24, $8d, $00
	.byte $8d, $24, $bd, $20, $9d, $29, $dd, $28, $dd, $29, $ed, $20, $8d, $22, $8d, $24, $8d, $25, $8d, $27, $8d, $29, $dd, $28
	.byte $bd, $2a, $9d, $29, $ff, $ad, $20, $8d, $27, $dd, $26, $dd, $27, $ed, $20, $8d, $22, $8d, $24, $8d, $25, $8d, $26, $8d
	.byte $27, $dd, $20, $bd, $2a, $9d, $29, $ff, $ad, $20, $8d, $2c, $dd, $2c, $dd, $2c, $dd, $2c, $9d, $2e, $8d, $00, $9d, $2c
	.byte $8d, $2a, $dd, $2a, $dd, $2a, $dd, $2a, $9d, $2c, $8d, $00, $9d, $2a, $8d, $29, $dd, $22, $9d, $24, $9d, $2a, $9d, $29
	.byte $8d, $29, $8d, $29, $ad, $24, $8d, $25, $dd, $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $00, $ff, $fd, $80, $20, $8d, $00, $8d, $20, $dd, $19, $8d, $00, $8d, $20, $8d, $00, $8d, $25, $8d, $00, $8d
@song1ref264:
	.byte $18, $8d, $00, $8d, $20, $8d, $00, $8d, $24
@song1ref273:
	.byte $8d, $00, $8d, $19, $8d, $00, $8d, $20, $8d, $00, $8d, $25, $8d, $00, $8d, $1d, $8d, $00, $8d, $20, $8d, $00, $8d, $25
	.byte $41, $0f
	.word @song1ref273
	.byte $41, $21
	.word @song1ref264
@song1ref303:
	.byte $8d, $00, $8d, $1b, $8d, $00, $8d, $20, $8d, $00, $8d, $24, $8d, $00, $8d, $1a, $8d, $00, $8d, $1f, $8d, $00, $8d, $23
	.byte $41, $0f
	.word @song1ref303
	.byte $18, $8d, $00, $8d, $20, $8d, $00, $8d, $24
	.byte $41, $0f
	.word @song1ref303
	.byte $41, $18
	.word @song1ref264
	.byte $14, $8d, $00, $8d, $20, $8d, $00, $8d, $25, $8d, $00, $8d, $19, $8d, $00, $8d, $20, $8d, $00, $8d, $29, $8d, $00, $8d
	.byte $18, $8d, $00, $8d, $20, $8d, $00, $8d, $27, $8d, $00, $8d, $17, $8d, $00, $8d, $20, $8d, $00, $8d, $26, $8d, $00, $8d
	.byte $1a, $8d, $00, $8d, $20, $8d, $00, $8d, $29, $8d, $00, $8d, $1b, $8d, $00, $8d, $22, $8d, $00, $8d, $2a, $8d, $00, $8d
	.byte $1a, $8d, $00, $8d, $22, $8d, $00, $8d, $2a, $8d, $00, $8d, $19, $8d, $00, $8d, $22, $8d, $00, $8d, $2a, $8d, $00, $8d
	.byte $18, $8d, $00, $8d, $20, $8d, $00, $8d, $2a, $8d, $00, $8d, $0d, $8d, $00, $8d, $20, $8d, $00, $8d, $29, $8d, $00, $8d
	.byte $14, $8d, $00, $8d, $20, $8d, $00, $8d, $20, $8d, $00, $8d, $1e, $cd, $18, $8d, $19, $dd, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref487:
	.byte $9f, $90, $20, $9d, $8e, $20, $bd, $90, $20, $8d, $20, $8d, $8e, $20, $bd, $90, $20, $9d, $8e, $20, $bd, $90, $20, $8d
	.byte $20, $8d, $8e, $20, $9d
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $41, $15
	.word @song1ref487
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref541:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
	.byte $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch5loop
@song1ch6:
@song1ch6loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch6loop
@song1ch7:
@song1ch7loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch7loop
@song1ch8:
@song1ch8loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch8loop
@song1ch9:
@song1ch9loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch9loop
@song1ch10:
@song1ch10loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch10loop
@song1ch11:
@song1ch11loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch11loop
@song1ch12:
@song1ch12loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch12loop
@song1ch13:
@song1ch13loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch13loop
@song1ch14:
@song1ch14loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch14loop
@song1ch15:
@song1ch15loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch15loop
@song1ch16:
@song1ch16loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch16loop
@song1ch17:
@song1ch17loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch17loop
@song1ch18:
@song1ch18loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch18loop
@song1ch19:
@song1ch19loop:
	.byte $41, $18
	.word @song1ref541
	.byte $42
	.word @song1ch19loop
@song2ch0:
@song2ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $ff, $af, $47, $ff, $ff, $ff, $af, $47, $ff, $ff
	.byte $ff, $af, $47, $ff, $d7, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $88
@song2ref27:
	.byte $19, $8f, $25, $8f, $16, $8f, $22, $8f, $17, $8f, $23, $fb, $19, $8f, $25, $8f, $16, $8f, $22, $8f, $17, $8f, $23, $fb
	.byte $12, $8f, $1e, $8f, $0f, $8f, $1b, $8f, $10, $8f, $1c, $fb, $12, $8f, $1e, $8f, $0f, $8f, $1b, $8f, $10, $8f, $1c, $d7
	.byte $1c, $89, $1b, $89, $1a, $89, $19, $a1, $1c, $a1, $1b, $a1, $15, $a1, $14, $a1, $1a, $a1, $19, $89, $1f, $89, $1e, $89
	.byte $1d, $89, $23, $89, $22, $89, $21, $95, $1c, $95, $18, $95, $17, $95, $16, $95, $15, $95, $ff, $d7, $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $92
	.byte $41, $5c
	.word @song2ref27
	.byte $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref131:
	.byte $ff, $ff, $ff, $af, $ff, $ff, $ff, $af, $ff, $ff, $ff, $af, $ff, $d7, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch6loop
@song2ch7:
@song2ch7loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch7loop
@song2ch8:
@song2ch8loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch8loop
@song2ch9:
@song2ch9loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch9loop
@song2ch10:
@song2ch10loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch10loop
@song2ch11:
@song2ch11loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch11loop
@song2ch12:
@song2ch12loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch12loop
@song2ch13:
@song2ch13loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch13loop
@song2ch14:
@song2ch14loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch14loop
@song2ch15:
@song2ch15loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch15loop
@song2ch16:
@song2ch16loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch16loop
@song2ch17:
@song2ch17loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch17loop
@song2ch18:
@song2ch18loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch18loop
@song2ch19:
@song2ch19loop:
	.byte $41, $0e
	.word @song2ref131
	.byte $42
	.word @song2ch19loop
@song3ch0:
@song3ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $89, $88
@song3ref7:
	.byte $27, $91
@song3ref9:
	.byte $26, $91, $25, $91, $26, $91, $27, $91, $28, $91, $27, $91, $26, $91
	.byte $41, $0f
	.word @song3ref7
	.byte $87, $47, $89
	.byte $41, $08
	.word @song3ref9
	.byte $26, $91
	.byte $41, $08
	.word @song3ref7
	.byte $25, $91, $26, $91, $27, $91, $26, $91, $27, $91, $26, $91, $25, $87, $47, $89
@song3ref53:
	.byte $2a, $91, $2b, $91, $2a, $91, $29, $91, $2a, $91, $29, $91, $28, $91, $29, $91
	.byte $41, $0f
	.word @song3ref53
	.byte $87, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $88
@song3ref78:
	.byte $20, $87
@song3ref80:
	.byte $23, $87, $20, $87, $22, $87, $20, $87, $21, $87, $20, $87, $22, $87, $20, $87, $23, $87, $20, $87, $24, $87
	.byte $41, $0a
	.word @song3ref78
	.byte $41, $16
	.word @song3ref80
	.byte $41, $08
	.word @song3ref78
@song3ref111:
	.byte $1f, $87, $22, $87, $1f, $87
@song3ref117:
	.byte $21
@song3ref118:
	.byte $87, $1f, $87, $22, $87, $1f, $87, $23
	.byte $41, $08
	.word @song3ref118
	.byte $87
	.byte $41, $0e
	.word @song3ref111
	.byte $41, $09
	.word @song3ref117
	.byte $41, $08
	.word @song3ref118
	.byte $87
	.byte $41, $08
	.word @song3ref111
@song3ref143:
	.byte $23, $87, $27, $87, $23, $87, $28
@song3ref150:
	.byte $87, $23, $87, $27, $87, $23, $87, $26
	.byte $41, $08
	.word @song3ref150
@song3ref161:
	.byte $87, $23, $87, $25, $87, $23, $87, $26, $87
	.byte $41, $0f
	.word @song3ref143
	.byte $41, $08
	.word @song3ref150
	.byte $41, $09
	.word @song3ref161
	.byte $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $80, $1c, $ff, $9d, $1b, $cd, $1f, $cd, $1e, $ff, $9d, $1d, $cd, $23, $cd, $22, $cd, $1d, $cd, $1c, $cd, $1d, $cd, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref210:
	.byte $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch4loop
@song3ch5:
@song3ch5loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch5loop
@song3ch6:
@song3ch6loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch6loop
@song3ch7:
@song3ch7loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch7loop
@song3ch8:
@song3ch8loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch8loop
@song3ch9:
@song3ch9loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch9loop
@song3ch10:
@song3ch10loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch10loop
@song3ch11:
@song3ch11loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch11loop
@song3ch12:
@song3ch12loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch12loop
@song3ch13:
@song3ch13loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch13loop
@song3ch14:
@song3ch14loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch14loop
@song3ch15:
@song3ch15loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch15loop
@song3ch16:
@song3ch16loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch16loop
@song3ch17:
@song3ch17loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch17loop
@song3ch18:
@song3ch18loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch18loop
@song3ch19:
@song3ch19loop:
	.byte $41, $09
	.word @song3ref210
	.byte $42
	.word @song3ch19loop
@song4ch0:
@song4ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $88, $1e, $95, $1e, $95, $1e, $95, $1b, $89, $1e, $95, $1e
	.byte $95, $1b, $89, $1e, $89, $1b, $89, $1e, $95, $47, $1d, $95, $1d, $95, $1d, $95, $19, $89, $1d, $95, $1d, $95, $19, $89
	.byte $1d, $89, $19, $89, $1d, $95, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $88, $25, $95, $25, $95, $25, $a1, $25, $89, $00, $89, $25, $a1, $25, $95, $25, $95, $24, $95, $24, $95, $24, $a1, $24
	.byte $89, $00, $89, $24, $a1, $24, $95, $24, $95, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $92, $1b, $ad, $22, $a1, $27, $b9, $22, $95, $27, $95, $19, $ad, $20, $a1, $25, $b9, $20, $95, $25, $95, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $90
@song4ref114:
	.byte $17, $95, $20, $8d, $20, $85, $8e, $20, $95, $90, $20, $8d, $20, $85
	.byte $41, $0c
	.word @song4ref114
	.byte $41, $0c
	.word @song4ref114
	.byte $41, $0c
	.word @song4ref114
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch4loop
@song4ch5:
@song4ch5loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch5loop
@song4ch6:
@song4ch6loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch6loop
@song4ch7:
@song4ch7loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch7loop
@song4ch8:
@song4ch8loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch8loop
@song4ch9:
@song4ch9loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch9loop
@song4ch10:
@song4ch10loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch10loop
@song4ch11:
@song4ch11loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch11loop
@song4ch12:
@song4ch12loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch12loop
@song4ch13:
@song4ch13loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch13loop
@song4ch14:
@song4ch14loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch14loop
@song4ch15:
@song4ch15loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch15loop
@song4ch16:
@song4ch16loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch16loop
@song4ch17:
@song4ch17loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch17loop
@song4ch18:
@song4ch18loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch18loop
@song4ch19:
@song4ch19loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song4ch19loop
@song5ch0:
	.byte $88, $1f, $8f, $1f, $a1, $1f, $a1, $1f, $8f, $1f, $a1, $24, $c5, $20, $c5
@song5ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song5ch0loop
@song5ch1:
	.byte $88, $29, $8f, $29, $a1, $29, $a1, $25, $8f, $29, $a1, $2c, $ff, $8d
@song5ch1loop:
	.byte $c7, $42
	.word @song5ch1loop
@song5ch2:
	.byte $92, $1b, $8f, $1b, $a1, $1b, $a1, $1b, $8f, $1b, $a1, $2c, $c5, $20, $c5
@song5ch2loop:
	.byte $c7, $42
	.word @song5ch2loop
@song5ch3:
	.byte $8e, $20, $a1, $90, $20, $8f, $8e, $20, $a1, $90, $20, $8f, $8e, $20, $a1, $20, $b3, $20, $a1, $90, $20, $8f, $20, $8f
	.byte $20, $8f
@song5ch3loop:
	.byte $c7, $42
	.word @song5ch3loop
@song5ch4:
	.byte $ff, $ff, $9f
@song5ch4loop:
	.byte $c7, $42
	.word @song5ch4loop
@song5ch5:
	.byte $ff, $ff, $9f
@song5ch5loop:
	.byte $c7, $42
	.word @song5ch5loop
@song5ch6:
	.byte $ff, $ff, $9f
@song5ch6loop:
	.byte $c7, $42
	.word @song5ch6loop
@song5ch7:
	.byte $ff, $ff, $9f
@song5ch7loop:
	.byte $c7, $42
	.word @song5ch7loop
@song5ch8:
	.byte $ff, $ff, $9f
@song5ch8loop:
	.byte $c7, $42
	.word @song5ch8loop
@song5ch9:
	.byte $ff, $ff, $9f
@song5ch9loop:
	.byte $c7, $42
	.word @song5ch9loop
@song5ch10:
	.byte $ff, $ff, $9f
@song5ch10loop:
	.byte $c7, $42
	.word @song5ch10loop
@song5ch11:
	.byte $ff, $ff, $9f
@song5ch11loop:
	.byte $c7, $42
	.word @song5ch11loop
@song5ch12:
	.byte $ff, $ff, $9f
@song5ch12loop:
	.byte $c7, $42
	.word @song5ch12loop
@song5ch13:
	.byte $ff, $ff, $9f
@song5ch13loop:
	.byte $c7, $42
	.word @song5ch13loop
@song5ch14:
	.byte $ff, $ff, $9f
@song5ch14loop:
	.byte $c7, $42
	.word @song5ch14loop
@song5ch15:
	.byte $ff, $ff, $9f
@song5ch15loop:
	.byte $c7, $42
	.word @song5ch15loop
@song5ch16:
	.byte $ff, $ff, $9f
@song5ch16loop:
	.byte $c7, $42
	.word @song5ch16loop
@song5ch17:
	.byte $ff, $ff, $9f
@song5ch17loop:
	.byte $c7, $42
	.word @song5ch17loop
@song5ch18:
	.byte $ff, $ff, $9f
@song5ch18loop:
	.byte $c7, $42
	.word @song5ch18loop
@song5ch19:
	.byte $ff, $ff, $9f
@song5ch19loop:
	.byte $c7, $42
	.word @song5ch19loop
@song6ch0:
@song6ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $88, $1e, $95, $1e, $95, $1e, $95, $1b, $89, $1e, $95, $1e
	.byte $95, $1b, $89, $1e, $89, $1b, $89, $1e, $95, $47, $1d, $95, $1d, $95, $1d, $95, $19, $89, $1d, $95, $1d, $95, $19, $89
	.byte $1d, $89, $19, $89, $1d, $95, $42
	.word @song6ch0loop
@song6ch1:
@song6ch1loop:
	.byte $88, $25, $95, $25, $95, $25, $a1, $25, $89, $00, $89, $25, $a1, $25, $95, $25, $95, $24, $95, $24, $95, $24, $a1, $24
	.byte $89, $00, $89, $24, $a1, $24, $95, $24, $95, $42
	.word @song6ch1loop
@song6ch2:
@song6ch2loop:
	.byte $92, $1b, $ad, $22, $a1, $27, $b9, $22, $95, $27, $95, $19, $ad, $20, $a1, $25, $b9, $20, $95, $25, $95, $42
	.word @song6ch2loop
@song6ch3:
@song6ch3loop:
	.byte $90
@song6ref114:
	.byte $17, $95, $20, $8d, $20, $85, $8e, $20, $95, $90, $20, $8d, $20, $85
	.byte $41, $0c
	.word @song6ref114
	.byte $41, $0c
	.word @song6ref114
	.byte $41, $0c
	.word @song6ref114
	.byte $42
	.word @song6ch3loop
@song6ch4:
@song6ch4loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch4loop
@song6ch5:
@song6ch5loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch5loop
@song6ch6:
@song6ch6loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch6loop
@song6ch7:
@song6ch7loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch7loop
@song6ch8:
@song6ch8loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch8loop
@song6ch9:
@song6ch9loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch9loop
@song6ch10:
@song6ch10loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch10loop
@song6ch11:
@song6ch11loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch11loop
@song6ch12:
@song6ch12loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch12loop
@song6ch13:
@song6ch13loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch13loop
@song6ch14:
@song6ch14loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch14loop
@song6ch15:
@song6ch15loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch15loop
@song6ch16:
@song6ch16loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch16loop
@song6ch17:
@song6ch17loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch17loop
@song6ch18:
@song6ch18loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch18loop
@song6ch19:
@song6ch19loop:
	.byte $ff, $bf, $ff, $bf, $42
	.word @song6ch19loop
@song7ch0:
	.byte $82, $22, $83, $23, $83, $24, $83, $84, $21, $b3, $47, $82, $1f, $8f, $26, $a1, $26, $8f, $26, $95, $24, $95, $23, $95
	.byte $1f, $8f, $1c, $a1, $1c, $8f, $18, $b3
@song7ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song7ch0loop
@song7ch1:
	.byte $c7, $86, $24, $8f, $2a, $a1, $2a, $8f, $2a, $95, $29, $95, $27, $95, $25, $fb
@song7ch1loop:
	.byte $c7, $42
	.word @song7ch1loop
@song7ch2:
	.byte $c7, $92, $20, $b3, $20, $8f, $20, $95, $22, $95, $24, $95, $25, $a1, $20, $a1, $19, $b3
@song7ch2loop:
	.byte $c7, $42
	.word @song7ch2loop
@song7ch3:
	.byte $c7, $ff, $ff, $8d
@song7ch3loop:
	.byte $c7, $42
	.word @song7ch3loop
@song7ch4:
	.byte $c7, $ff, $ff, $8d
@song7ch4loop:
	.byte $c7, $42
	.word @song7ch4loop
@song7ch5:
	.byte $c7, $ff, $ff, $8d
@song7ch5loop:
	.byte $c7, $42
	.word @song7ch5loop
@song7ch6:
	.byte $c7, $ff, $ff, $8d
@song7ch6loop:
	.byte $c7, $42
	.word @song7ch6loop
@song7ch7:
	.byte $c7, $ff, $ff, $8d
@song7ch7loop:
	.byte $c7, $42
	.word @song7ch7loop
@song7ch8:
	.byte $c7, $ff, $ff, $8d
@song7ch8loop:
	.byte $c7, $42
	.word @song7ch8loop
@song7ch9:
	.byte $c7, $ff, $ff, $8d
@song7ch9loop:
	.byte $c7, $42
	.word @song7ch9loop
@song7ch10:
	.byte $c7, $ff, $ff, $8d
@song7ch10loop:
	.byte $c7, $42
	.word @song7ch10loop
@song7ch11:
	.byte $c7, $ff, $ff, $8d
@song7ch11loop:
	.byte $c7, $42
	.word @song7ch11loop
@song7ch12:
	.byte $c7, $ff, $ff, $8d
@song7ch12loop:
	.byte $c7, $42
	.word @song7ch12loop
@song7ch13:
	.byte $c7, $ff, $ff, $8d
@song7ch13loop:
	.byte $c7, $42
	.word @song7ch13loop
@song7ch14:
	.byte $c7, $ff, $ff, $8d
@song7ch14loop:
	.byte $c7, $42
	.word @song7ch14loop
@song7ch15:
	.byte $c7, $ff, $ff, $8d
@song7ch15loop:
	.byte $c7, $42
	.word @song7ch15loop
@song7ch16:
	.byte $c7, $ff, $ff, $8d
@song7ch16loop:
	.byte $c7, $42
	.word @song7ch16loop
@song7ch17:
	.byte $c7, $ff, $ff, $8d
@song7ch17loop:
	.byte $c7, $42
	.word @song7ch17loop
@song7ch18:
	.byte $c7, $ff, $ff, $8d
@song7ch18loop:
	.byte $c7, $42
	.word @song7ch18loop
@song7ch19:
	.byte $c7, $ff, $ff, $8d
@song7ch19loop:
	.byte $c7, $42
	.word @song7ch19loop
@song8ch0:
	.byte $8c, $1d, $8f, $00, $a1, $19, $8f, $00, $a1, $14, $a1, $1e, $c5, $1e, $e9, $1d, $8f, $1b, $8f, $1d, $c5, $00, $8f
@song8ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $c7, $42
	.word @song8ch0loop
@song8ch1:
	.byte $8c, $25, $8f, $00, $a1, $20, $8f, $00, $a1, $1d, $a1, $22, $95, $24, $95, $22, $95, $21, $a1, $23, $a1, $21, $a1, $20
	.byte $fb
@song8ch1loop:
	.byte $c7, $42
	.word @song8ch1loop
@song8ch2:
	.byte $92, $20, $b3, $1d, $b3, $80, $19, $a1, $1e, $c5, $1a, $e9, $19, $e9, $00, $8f
@song8ch2loop:
	.byte $c7, $42
	.word @song8ch2loop
@song8ch3:
	.byte $ff, $ff, $ff, $c1
@song8ch3loop:
	.byte $c7, $42
	.word @song8ch3loop
@song8ch4:
	.byte $ff, $ff, $ff, $c1
@song8ch4loop:
	.byte $c7, $42
	.word @song8ch4loop
@song8ch5:
	.byte $ff, $ff, $ff, $c1
@song8ch5loop:
	.byte $c7, $42
	.word @song8ch5loop
@song8ch6:
	.byte $ff, $ff, $ff, $c1
@song8ch6loop:
	.byte $c7, $42
	.word @song8ch6loop
@song8ch7:
	.byte $ff, $ff, $ff, $c1
@song8ch7loop:
	.byte $c7, $42
	.word @song8ch7loop
@song8ch8:
	.byte $ff, $ff, $ff, $c1
@song8ch8loop:
	.byte $c7, $42
	.word @song8ch8loop
@song8ch9:
	.byte $ff, $ff, $ff, $c1
@song8ch9loop:
	.byte $c7, $42
	.word @song8ch9loop
@song8ch10:
	.byte $ff, $ff, $ff, $c1
@song8ch10loop:
	.byte $c7, $42
	.word @song8ch10loop
@song8ch11:
	.byte $ff, $ff, $ff, $c1
@song8ch11loop:
	.byte $c7, $42
	.word @song8ch11loop
@song8ch12:
	.byte $ff, $ff, $ff, $c1
@song8ch12loop:
	.byte $c7, $42
	.word @song8ch12loop
@song8ch13:
	.byte $ff, $ff, $ff, $c1
@song8ch13loop:
	.byte $c7, $42
	.word @song8ch13loop
@song8ch14:
	.byte $ff, $ff, $ff, $c1
@song8ch14loop:
	.byte $c7, $42
	.word @song8ch14loop
@song8ch15:
	.byte $ff, $ff, $ff, $c1
@song8ch15loop:
	.byte $c7, $42
	.word @song8ch15loop
@song8ch16:
	.byte $ff, $ff, $ff, $c1
@song8ch16loop:
	.byte $c7, $42
	.word @song8ch16loop
@song8ch17:
	.byte $ff, $ff, $ff, $c1
@song8ch17loop:
	.byte $c7, $42
	.word @song8ch17loop
@song8ch18:
	.byte $ff, $ff, $ff, $c1
@song8ch18loop:
	.byte $c7, $42
	.word @song8ch18loop
@song8ch19:
	.byte $ff, $ff, $ff, $c1
@song8ch19loop:
	.byte $c7, $42
	.word @song8ch19loop
@song9ch0:
	.byte $8c, $20, $8d, $1f, $8d, $20, $8d
@song9ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $1d, $dd, $1e, $ad, $1f, $ad, $20, $dd, $25, $ad, $29, $a1
	.byte $29, $89, $47, $27, $ad, $29, $ad, $2a, $ad, $24, $ad, $27, $dd, $25, $ad, $20, $8d, $1f, $8d, $20, $8d, $42
	.word @song9ch0loop
@song9ch1:
	.byte $af
@song9ch1loop:
	.byte $8c, $14, $dd, $16, $ad, $17, $ad, $18, $dd, $1d, $ad, $20, $ad, $1e, $ad, $20, $ad, $22, $ad, $1b, $ad, $1e, $ad, $00
	.byte $ad, $1d, $ad, $00, $ad, $42
	.word @song9ch1loop
@song9ch2:
	.byte $80, $18, $ad
@song9ch2loop:
	.byte $19, $dd, $1b, $ad, $1c, $ad, $1d, $ad, $19, $ad, $22, $ad, $20, $ad, $1e, $ad, $1d, $ad, $1b, $ad, $1e, $ad, $20, $ad
	.byte $14, $ad, $19, $ad, $18, $ad, $42
	.word @song9ch2loop
@song9ch3:
	.byte $af
@song9ch3loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch3loop
@song9ch4:
	.byte $af
@song9ch4loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch4loop
@song9ch5:
	.byte $af
@song9ch5loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch5loop
@song9ch6:
	.byte $af
@song9ch6loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch6loop
@song9ch7:
	.byte $af
@song9ch7loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch7loop
@song9ch8:
	.byte $af
@song9ch8loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch8loop
@song9ch9:
	.byte $af
@song9ch9loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch9loop
@song9ch10:
	.byte $af
@song9ch10loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch10loop
@song9ch11:
	.byte $af
@song9ch11loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch11loop
@song9ch12:
	.byte $af
@song9ch12loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch12loop
@song9ch13:
	.byte $af
@song9ch13loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch13loop
@song9ch14:
	.byte $af
@song9ch14loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch14loop
@song9ch15:
	.byte $af
@song9ch15loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch15loop
@song9ch16:
	.byte $af
@song9ch16loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch16loop
@song9ch17:
	.byte $af
@song9ch17loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch17loop
@song9ch18:
	.byte $af
@song9ch18loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch18loop
@song9ch19:
	.byte $af
@song9ch19loop:
	.byte $ff, $ff, $ff, $ff, $ff, $ff, $42
	.word @song9ch19loop
@song10ch0:
	.byte $8a, $1d, $8d, $19, $8d, $14, $8d, $1d, $8d, $19, $8d, $14, $8d, $1d, $8d, $1d, $85, $1d, $85, $1d, $8d, $1d, $8d, $1d
	.byte $8d, $1d, $8d, $1e, $8d, $1a, $8d, $15, $8d, $1e, $8d, $1a, $8d, $15, $8d, $1e, $8d, $1e, $85, $1e, $85, $1e, $8d, $1e
	.byte $8d, $1e, $8d, $1e, $8d, $47, $20, $8d, $1c, $8d, $17, $8d, $20, $8d, $1c, $8d, $17, $8d, $20, $8d, $20, $85, $20, $85
	.byte $20, $8d, $22, $95, $22, $95, $22, $95, $24, $fd, $00, $a5
@song10ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $df, $42
	.word @song10ch0loop
@song10ch1:
	.byte $8a, $25, $8d, $20, $8d, $1d, $8d, $25, $8d, $20, $8d, $1d, $8d, $25, $dd, $26, $8d, $21, $8d, $1e, $8d, $26, $8d, $21
	.byte $8d, $1e, $8d, $26, $dd, $28, $8d, $23, $8d, $20, $8d, $28, $8d, $23, $8d, $20, $8d, $28, $ad, $2a, $95, $2a, $95, $2a
	.byte $95, $2c, $fd, $00, $a5
@song10ch1loop:
	.byte $df, $42
	.word @song10ch1loop
@song10ch2:
	.byte $80, $19, $e5, $00, $85, $19, $95, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $19, $85, $00, $85, $1a, $e5, $00
	.byte $85, $1a, $95, $00, $85, $1a, $85, $00, $85, $1a, $85, $00, $85, $1a
@song10ref189:
	.byte $85, $00, $85, $23, $85, $00, $85, $20, $85, $00, $85, $1c
	.byte $41, $0c
	.word @song10ref189
	.byte $85, $00, $85, $23, $85, $00, $85, $23, $95, $00, $85, $25, $85, $00, $8d, $25, $85, $00, $8d, $25, $85, $00, $8d, $27
	.byte $fd, $00, $a5
@song10ch2loop:
	.byte $df, $42
	.word @song10ch2loop
@song10ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch3loop:
	.byte $df, $42
	.word @song10ch3loop
@song10ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch4loop:
	.byte $df, $42
	.word @song10ch4loop
@song10ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch5loop:
	.byte $df, $42
	.word @song10ch5loop
@song10ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch6loop:
	.byte $df, $42
	.word @song10ch6loop
@song10ch7:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch7loop:
	.byte $df, $42
	.word @song10ch7loop
@song10ch8:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch8loop:
	.byte $df, $42
	.word @song10ch8loop
@song10ch9:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch9loop:
	.byte $df, $42
	.word @song10ch9loop
@song10ch10:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch10loop:
	.byte $df, $42
	.word @song10ch10loop
@song10ch11:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch11loop:
	.byte $df, $42
	.word @song10ch11loop
@song10ch12:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch12loop:
	.byte $df, $42
	.word @song10ch12loop
@song10ch13:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch13loop:
	.byte $df, $42
	.word @song10ch13loop
@song10ch14:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch14loop:
	.byte $df, $42
	.word @song10ch14loop
@song10ch15:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch15loop:
	.byte $df, $42
	.word @song10ch15loop
@song10ch16:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch16loop:
	.byte $df, $42
	.word @song10ch16loop
@song10ch17:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch17loop:
	.byte $df, $42
	.word @song10ch17loop
@song10ch18:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch18loop:
	.byte $df, $42
	.word @song10ch18loop
@song10ch19:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song10ch19loop:
	.byte $df, $42
	.word @song10ch19loop
@song11ch0:
	.byte $8f, $8c, $11, $8d
@song11ref5:
	.byte $14, $8d, $19, $8d, $1d, $8d, $20, $8d, $25, $ad, $20, $ad, $00, $8d, $10, $8d
@song11ref21:
	.byte $15, $8d, $19, $8d, $1c, $8d, $21, $8d, $25, $ad, $21, $ad, $47, $00, $8d, $12, $8d
@song11ref38:
	.byte $17, $8d, $1b, $8d, $1e, $8d, $23, $8d, $27, $ad, $27, $ad, $29, $c5, $00, $f5
@song11ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $bf, $42
	.word @song11ch0loop
@song11ch1:
	.byte $8c
	.byte $41, $09
	.word @song11ref5
	.byte $8d, $29, $8d, $2c, $ad, $29, $ad
	.byte $41, $09
	.word @song11ref21
	.byte $8d, $28, $8d, $2d, $ad, $28, $ad
	.byte $41, $09
	.word @song11ref38
	.byte $8d, $2a, $8d, $2f, $ad, $2f, $8d, $2f, $8d, $2f, $8d, $31, $c5, $00, $f5
@song11ch1loop:
	.byte $ff, $bf, $42
	.word @song11ch1loop
@song11ch2:
	.byte $af, $80, $19, $8d, $1d, $8d, $20, $8d, $29, $ad, $25, $8d, $00, $cd, $19, $8d, $1c, $8d, $21, $8d, $28, $ad, $25, $8d
	.byte $00, $9d, $af, $1b, $8d, $1e, $8d, $23, $8d, $2a, $ad, $27, $ad, $25, $c5, $00, $f5
@song11ch2loop:
	.byte $ff, $bf, $42
	.word @song11ch2loop
@song11ch3:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch3loop:
	.byte $ff, $bf, $42
	.word @song11ch3loop
@song11ch4:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch4loop:
	.byte $ff, $bf, $42
	.word @song11ch4loop
@song11ch5:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch5loop:
	.byte $ff, $bf, $42
	.word @song11ch5loop
@song11ch6:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch6loop:
	.byte $ff, $bf, $42
	.word @song11ch6loop
@song11ch7:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch7loop:
	.byte $ff, $bf, $42
	.word @song11ch7loop
@song11ch8:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch8loop:
	.byte $ff, $bf, $42
	.word @song11ch8loop
@song11ch9:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch9loop:
	.byte $ff, $bf, $42
	.word @song11ch9loop
@song11ch10:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch10loop:
	.byte $ff, $bf, $42
	.word @song11ch10loop
@song11ch11:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch11loop:
	.byte $ff, $bf, $42
	.word @song11ch11loop
@song11ch12:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch12loop:
	.byte $ff, $bf, $42
	.word @song11ch12loop
@song11ch13:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch13loop:
	.byte $ff, $bf, $42
	.word @song11ch13loop
@song11ch14:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch14loop:
	.byte $ff, $bf, $42
	.word @song11ch14loop
@song11ch15:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch15loop:
	.byte $ff, $bf, $42
	.word @song11ch15loop
@song11ch16:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch16loop:
	.byte $ff, $bf, $42
	.word @song11ch16loop
@song11ch17:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch17loop:
	.byte $ff, $bf, $42
	.word @song11ch17loop
@song11ch18:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch18loop:
	.byte $ff, $bf, $42
	.word @song11ch18loop
@song11ch19:
	.byte $ff, $ff, $ff, $ff, $ff, $ff
@song11ch19loop:
	.byte $ff, $bf, $42
	.word @song11ch19loop
@song12ch0:
	.byte $8c, $11, $89, $21, $95, $21, $89, $21, $95, $12, $89, $22, $95, $22, $89, $22, $95, $13, $89, $23, $95, $23, $89, $23
	.byte $95, $24, $95, $24, $dd
@song12ch0loop:
	.byte $46, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $8b, $42
	.word @song12ch0loop
@song12ch1:
	.byte $8c, $1d, $89, $27, $95, $27, $89, $27, $95, $1e, $89, $28, $95, $28, $89, $28, $95, $1f, $89, $29, $95, $29, $89, $29
	.byte $95, $2a, $95, $2a, $dd
@song12ch1loop:
	.byte $8b, $42
	.word @song12ch1loop
@song12ch2:
	.byte $92, $24, $89, $30, $95, $30, $89, $30, $95, $25, $89, $31, $95, $31, $89, $31, $95, $26, $89, $32, $95, $32, $89, $32
	.byte $95, $20, $95, $80, $20, $ad, $00, $ad
@song12ch2loop:
	.byte $8b, $42
	.word @song12ch2loop
@song12ch3:
	.byte $ff, $ff, $cf
@song12ch3loop:
	.byte $8b, $42
	.word @song12ch3loop
@song12ch4:
	.byte $ff, $ff, $cf
@song12ch4loop:
	.byte $8b, $42
	.word @song12ch4loop
@song12ch5:
	.byte $ff, $ff, $cf
@song12ch5loop:
	.byte $8b, $42
	.word @song12ch5loop
@song12ch6:
	.byte $ff, $ff, $cf
@song12ch6loop:
	.byte $8b, $42
	.word @song12ch6loop
@song12ch7:
	.byte $ff, $ff, $cf
@song12ch7loop:
	.byte $8b, $42
	.word @song12ch7loop
@song12ch8:
	.byte $ff, $ff, $cf
@song12ch8loop:
	.byte $8b, $42
	.word @song12ch8loop
@song12ch9:
	.byte $ff, $ff, $cf
@song12ch9loop:
	.byte $8b, $42
	.word @song12ch9loop
@song12ch10:
	.byte $ff, $ff, $cf
@song12ch10loop:
	.byte $8b, $42
	.word @song12ch10loop
@song12ch11:
	.byte $ff, $ff, $cf
@song12ch11loop:
	.byte $8b, $42
	.word @song12ch11loop
@song12ch12:
	.byte $ff, $ff, $cf
@song12ch12loop:
	.byte $8b, $42
	.word @song12ch12loop
@song12ch13:
	.byte $ff, $ff, $cf
@song12ch13loop:
	.byte $8b, $42
	.word @song12ch13loop
@song12ch14:
	.byte $ff, $ff, $cf
@song12ch14loop:
	.byte $8b, $42
	.word @song12ch14loop
@song12ch15:
	.byte $ff, $ff, $cf
@song12ch15loop:
	.byte $8b, $42
	.word @song12ch15loop
@song12ch16:
	.byte $ff, $ff, $cf
@song12ch16loop:
	.byte $8b, $42
	.word @song12ch16loop
@song12ch17:
	.byte $ff, $ff, $cf
@song12ch17loop:
	.byte $8b, $42
	.word @song12ch17loop
@song12ch18:
	.byte $ff, $ff, $cf
@song12ch18loop:
	.byte $8b, $42
	.word @song12ch18loop
@song12ch19:
	.byte $ff, $ff, $cf
@song12ch19loop:
	.byte $8b, $42
	.word @song12ch19loop
