;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


castle_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Castleworld

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c2,$00,$00


; Castleworld
@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $81,$82,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81
	.byte $29
@ref1:
	.byte $81,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81,$29
@ref2:
	.byte $81,$29,$81,$28,$81,$29,$81,$2a,$81,$29,$81,$2a,$81,$29,$81,$28
	.byte $ff,$10
	.word @ref2
@ref4:
	.byte $81,$2d,$81,$2e,$81,$2d,$81,$2c,$81,$2d,$81,$2c,$81,$2b,$81,$2c
	.byte $ff,$10
	.word @ref4
	.byte $fd
	.word @song0ch0loop

; Castleworld
@song0ch1:
@song0ch1loop:
@ref6:
	.byte $82,$23,$26,$23,$25,$23,$24,$23,$25,$23,$26,$23,$27,$23,$26,$23
	.byte $25
@ref7:
	.byte $23,$26,$23,$25,$23,$24,$23,$25,$23,$26,$23,$27,$23,$26,$23,$25
@ref8:
	.byte $22,$25,$22,$24,$22,$25,$22,$26,$22,$25,$22,$26,$22,$25,$22,$24
	.byte $ff,$10
	.word @ref8
@ref10:
	.byte $26,$2a,$26,$2b,$26,$2a,$26,$29,$26,$2a,$26,$29,$26,$28,$26,$29
	.byte $ff,$10
	.word @ref10
	.byte $fd
	.word @song0ch1loop

; Castleworld
@song0ch2:
@song0ch2loop:
@ref12:
	.byte $80,$1f,$9d
@ref13:
	.byte $1e,$8d,$22,$8d
@ref14:
	.byte $21,$9d
@ref15:
	.byte $20,$8d,$26,$8d
@ref16:
	.byte $25,$8d,$20,$8d
@ref17:
	.byte $1f,$8d,$20,$8d
	.byte $fd
	.word @song0ch2loop

; Castleworld
@song0ch3:
@song0ch3loop:
@ref18:
	.byte $9f
@ref19:
	.byte $9f
@ref20:
	.byte $9f
@ref21:
	.byte $9f
@ref22:
	.byte $9f
@ref23:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

; Castleworld
@song0ch4:
@song0ch4loop:
@ref24:
	.byte $9f
@ref25:
	.byte $9f
@ref26:
	.byte $9f
@ref27:
	.byte $9f
@ref28:
	.byte $9f
@ref29:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
