;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


cloud_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Cloud

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env0
	.word @env4,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env5

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$07,$c0,$00,$02
@env3:
	.byte $cc,$04,$c0,$00,$02
@env4:
	.byte $cc,$c0,$00,$01
@env5:
	.byte $c2,$00,$00


; Cloud
@song0ch0:
	.byte $fb,$02
@song0ch0loop:
@ref0:
	.byte $86,$21,$89,$21,$89,$21,$89,$1e,$83,$21,$83
@ref1:
	.byte $85,$21,$89,$1e,$83,$21,$83,$1e,$83,$21,$89
@ref2:
	.byte $20,$89,$20,$89,$20,$89,$1c,$83,$20,$83
@ref3:
	.byte $85,$20,$89,$1c,$83,$20,$83,$1c,$83,$20,$89
	.byte $fd
	.word @song0ch0loop

; Cloud
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $86,$28,$89,$28,$89,$28,$8f,$28,$83
@ref5:
	.byte $00,$83,$28,$8f,$28,$89,$28,$89
@ref6:
	.byte $27,$89,$27,$89,$27,$8f,$27,$83
@ref7:
	.byte $00,$83,$27,$8f,$27,$89,$27,$89
	.byte $fd
	.word @song0ch1loop

; Cloud
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $80,$1e,$95,$25,$8f,$2a,$83
@ref9:
	.byte $97,$25,$89,$2a,$89
@ref10:
	.byte $1c,$95,$23,$8f,$28,$83
@ref11:
	.byte $97,$23,$89,$28,$89
	.byte $fd
	.word @song0ch2loop

; Cloud
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $84,$03,$89,$0c,$85,$0c,$81,$82,$0c,$89,$84,$0c,$85,$0c,$81
@ref13:
	.byte $03,$89,$0c,$85,$0c,$81,$82,$0c,$89,$84,$0c,$85,$0c,$81
	.byte $ff,$0c
	.word @ref13
	.byte $ff,$0c
	.word @ref13
	.byte $fd
	.word @song0ch3loop

; Cloud
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $af
@ref17:
	.byte $af
@ref18:
	.byte $af
@ref19:
	.byte $af
	.byte $fd
	.word @song0ch4loop
