;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


death_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Death

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env5,@env0,@env6
	.word @env3,@env5,@env0,@env6
	.word @env4,@env0,@env0,@env6

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$07,$c0,$00,$02
@env2:
	.byte $ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0a
@env3:
	.byte $c8,$c4,$c0,$00,$02
@env4:
	.byte $ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0b
@env5:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env6:
	.byte $c2,$00,$00


; Death
@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $82,$25,$26,$27,$84,$24,$8f
@ref1:
	.byte $82,$22,$83,$29,$89,$29,$83,$29,$85,$27,$85,$26,$85,$22,$83,$1f
	.byte $89,$1f,$83,$1b,$8f
@song0ch0loop:
@ref2:
	.byte $97
	.byte $fd
	.word @song0ch0loop

; Death
@song0ch1:
@ref3:
	.byte $97
@ref4:
	.byte $86,$27,$83,$2d,$89,$2d,$83,$2d,$85,$2c,$85,$2a,$85,$28,$a7
@song0ch1loop:
@ref5:
	.byte $97
	.byte $fd
	.word @song0ch1loop

; Death
@song0ch2:
@ref6:
	.byte $97
@ref7:
	.byte $80,$23,$8f,$23,$83,$23,$85,$25,$85,$27,$85,$28,$89,$23,$89,$1c
	.byte $8f
@song0ch2loop:
@ref8:
	.byte $97
	.byte $fd
	.word @song0ch2loop

; Death
@song0ch3:
@ref9:
	.byte $97
@ref10:
	.byte $d9
@song0ch3loop:
@ref11:
	.byte $97
	.byte $fd
	.word @song0ch3loop

; Death
@song0ch4:
@ref12:
	.byte $97
@ref13:
	.byte $d9
@song0ch4loop:
@ref14:
	.byte $97
	.byte $fd
	.word @song0ch4loop
