;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


enter_a_pipe_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Enter in a pipe

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env0
	.word @env4,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env5

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$07,$c0,$00,$02
@env3:
	.byte $cc,$04,$c0,$00,$02
@env4:
	.byte $cc,$c0,$00,$01
@env5:
	.byte $c2,$00,$00


; Enter in a pipe
@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $86,$22,$83,$22,$89,$22,$89,$22,$83,$22,$89,$27,$95,$23,$95
@song0ch0loop:
@ref1:
	.byte $97
	.byte $fd
	.word @song0ch0loop

; Enter in a pipe
@song0ch1:
@ref2:
	.byte $86,$2c,$83,$2c,$89,$2c,$89,$28,$83,$2c,$89,$2f,$ad
@song0ch1loop:
@ref3:
	.byte $97
	.byte $fd
	.word @song0ch1loop

; Enter in a pipe
@song0ch2:
@ref4:
	.byte $80,$1e,$83,$1e,$89,$1e,$89,$1e,$83,$1e,$89,$2f,$95,$23,$95
@song0ch2loop:
@ref5:
	.byte $97
	.byte $fd
	.word @song0ch2loop

; Enter in a pipe
@song0ch3:
@ref6:
	.byte $82,$0c,$89,$84,$0c,$83,$82,$0c,$89,$84,$0c,$83,$82,$0c,$89,$0c
	.byte $8f,$0c,$89,$84,$0c,$83,$0c,$83,$0c,$83
@song0ch3loop:
@ref7:
	.byte $97
	.byte $fd
	.word @song0ch3loop

; Enter in a pipe
@song0ch4:
@ref8:
	.byte $df
@song0ch4loop:
@ref9:
	.byte $97
	.byte $fd
	.word @song0ch4loop
