;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


game_over_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Game Over

@instruments:
	.word @env3,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env4

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$07,$c0,$00,$02
@env2:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $c0,$c2,$00,$01


; Game Over
@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $84,$20,$83,$00,$89,$1c,$83,$00,$89,$17,$89,$21,$95,$21,$a1,$20
	.byte $83,$1e,$83,$20,$95,$00,$83
@song0ch0loop:
@ref1:
	.byte $97
	.byte $fd
	.word @song0ch0loop

; Game Over
@song0ch1:
@ref2:
	.byte $84,$28,$83,$00,$89,$23,$83,$00,$89,$20,$89,$25,$85,$27,$85,$25
	.byte $85,$24,$89,$26,$89,$24,$89,$23,$a7
@song0ch1loop:
@ref3:
	.byte $97
	.byte $fd
	.word @song0ch1loop

; Game Over
@song0ch2:
@ref4:
	.byte $82,$23,$8f,$20,$8f,$80,$1c,$89,$21,$95,$1d,$a1,$1c,$a1,$00,$83
@song0ch2loop:
@ref5:
	.byte $97
	.byte $fd
	.word @song0ch2loop

; Game Over
@song0ch3:
@ref6:
	.byte $f9,$9b
@song0ch3loop:
@ref7:
	.byte $97
	.byte $fd
	.word @song0ch3loop

; Game Over
@song0ch4:
@ref8:
	.byte $f9,$9b
@song0ch4loop:
@ref9:
	.byte $97
	.byte $fd
	.word @song0ch4loop
