;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


hurry_up_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Hurry up

@instruments:
	.word @env3,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env4

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$07,$c0,$00,$02
@env2:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env3:
	.byte $cf,$00,$00
@env4:
	.byte $c0,$c2,$00,$01


; Hurry up
@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $84,$14,$81,$24,$85,$24,$81,$24,$85,$15,$81,$25,$85,$25,$81,$25
	.byte $85,$16,$81,$26,$85,$26,$81,$26,$85,$27,$85,$27,$9d
@song0ch0loop:
@ref1:
	.byte $83
	.byte $fd
	.word @song0ch0loop

; Hurry up
@song0ch1:
@ref2:
	.byte $84,$20,$81,$2a,$85,$2a,$81,$2a,$85,$21,$81,$2b,$85,$2b,$81,$2b
	.byte $85,$22,$81,$2c,$85,$2c,$81,$2c,$85,$2d,$85,$2d,$9d
@song0ch1loop:
@ref3:
	.byte $83
	.byte $fd
	.word @song0ch1loop

; Hurry up
@song0ch2:
@ref4:
	.byte $82,$27,$81,$33,$85,$33,$81,$33,$85,$28,$81,$34,$85,$34,$81,$34
	.byte $85,$29,$81,$35,$85,$35,$81,$35,$85,$23,$85,$80,$23,$8d,$00,$8d
@song0ch2loop:
@ref5:
	.byte $83
	.byte $fd
	.word @song0ch2loop

; Hurry up
@song0ch3:
@ref6:
	.byte $ef
@song0ch3loop:
@ref7:
	.byte $83
	.byte $fd
	.word @song0ch3loop

; Hurry up
@song0ch4:
@ref8:
	.byte $ef
@song0ch4loop:
@ref9:
	.byte $83
	.byte $fd
	.word @song0ch4loop
