;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


in_another_castle_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; In an other castle

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$cb,$ca,$c9,$c8,$00,$04
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c2,$00,$00


; In an other castle
@song0ch0:
	.byte $fb,$04
@ref0:
	.byte $82,$20,$81,$1c,$81,$17,$81,$20,$81,$1c,$81,$17,$81,$20,$81,$20
	.byte $20,$20,$81,$20,$81,$20,$81,$20,$81,$21,$81,$1d,$81,$18,$81,$21
	.byte $81,$1d,$81,$18,$81,$21,$81,$21,$21,$21,$81,$21,$81,$21,$81,$21
	.byte $81
@ref1:
	.byte $23,$81,$1f,$81,$1a,$81,$23,$81,$1f,$81,$1a,$81,$23,$81,$23,$23
	.byte $23,$81,$25,$83,$25,$83,$25,$83,$27,$9d,$00,$87
@song0ch0loop:
@ref2:
	.byte $97
	.byte $fd
	.word @song0ch0loop

; In an other castle
@song0ch1:
@ref3:
	.byte $82,$28,$81,$23,$81,$20,$81,$28,$81,$23,$81,$20,$81,$28,$95,$29
	.byte $81,$24,$81,$21,$81,$29,$81,$24,$81,$21,$81,$29,$95
@ref4:
	.byte $2b,$81,$26,$81,$23,$81,$2b,$81,$26,$81,$23,$81,$2b,$89,$2d,$83
	.byte $2d,$83,$2d,$83,$2f,$9d,$00,$87
@song0ch1loop:
@ref5:
	.byte $97
	.byte $fd
	.word @song0ch1loop

; In an other castle
@song0ch2:
@ref6:
	.byte $80,$1c,$97,$00,$1c,$83,$00,$1c,$00,$1c,$00,$1c,$00,$1d,$97,$00
	.byte $1d,$83,$00,$1d,$00,$1d,$00,$1d,$00
@ref7:
	.byte $26,$00,$23,$00,$1f,$00,$26,$00,$23,$00,$1f,$00,$26,$00,$26,$83
	.byte $00,$28,$00,$81,$28,$00,$81,$28,$00,$81,$2a,$9d,$00,$87
@song0ch2loop:
@ref8:
	.byte $97
	.byte $fd
	.word @song0ch2loop

; In an other castle
@song0ch3:
@ref9:
	.byte $df
@ref10:
	.byte $df
@song0ch3loop:
@ref11:
	.byte $97
	.byte $fd
	.word @song0ch3loop

; In an other castle
@song0ch4:
@ref12:
	.byte $df
@ref13:
	.byte $df
@song0ch4loop:
@ref14:
	.byte $97
	.byte $fd
	.word @song0ch4loop
