;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


level_clear_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Victory

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c0,$c2,$00,$01


; Victory
@song0ch0:
	.byte $fb,$04
@ref0:
	.byte $00,$81,$82,$14,$81,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$89,$23
	.byte $89,$00,$81,$13,$81,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$89,$24
	.byte $89
@ref1:
	.byte $00,$81,$15,$81,$1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$89,$2a,$89
	.byte $2c,$8f,$00,$9b
@song0ch0loop:
@ref2:
	.byte $af
	.byte $fd
	.word @song0ch0loop

; Victory
@song0ch1:
@ref3:
	.byte $82,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$81,$2c,$81,$2f,$89,$2c
	.byte $89,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$81,$2b,$81,$30,$89,$2b
	.byte $89
@ref4:
	.byte $1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$81,$2d,$81,$32,$89,$32,$81
	.byte $32,$81,$32,$81,$34,$8f,$00,$9b
@song0ch1loop:
@ref5:
	.byte $af
	.byte $fd
	.word @song0ch1loop

; Victory
@song0ch2:
@ref6:
	.byte $8b,$80,$1c,$81,$20,$81,$23,$81,$2c,$89,$28,$81,$00,$91,$1c,$81
	.byte $1f,$81,$24,$81,$2b,$89,$28,$81,$00,$85
@ref7:
	.byte $8b,$1e,$81,$21,$81,$26,$81,$2d,$89,$2a,$89,$28,$8f,$00,$9b
@song0ch2loop:
@ref8:
	.byte $af
	.byte $fd
	.word @song0ch2loop

; Victory
@song0ch3:
@ref9:
	.byte $df
@ref10:
	.byte $df
@song0ch3loop:
@ref11:
	.byte $af
	.byte $fd
	.word @song0ch3loop

; Victory
@song0ch4:
@ref12:
	.byte $df
@ref13:
	.byte $df
@song0ch4loop:
@ref14:
	.byte $af
	.byte $fd
	.word @song0ch4loop
