;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


overworld_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Overworld

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env0
	.word @env4,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env5

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$07,$c0,$00,$02
@env3:
	.byte $cc,$04,$c0,$00,$02
@env4:
	.byte $cc,$c0,$00,$01
@env5:
	.byte $c2,$00,$00


; Overworld
@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $86,$22,$83,$22,$89,$22,$89,$22,$83,$22,$89,$27,$95,$23,$95
@ref1:
	.byte $20,$8f,$1c,$8f,$17,$8f,$1c,$89,$1e,$89,$1d,$83,$1c,$89
@ref2:
	.byte $1c,$85,$23,$85,$27,$85,$28,$89,$25,$83,$27,$89,$25,$89,$20,$83
	.byte $21,$83,$1e,$8f
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
@ref5:
	.byte $8b,$2c,$83,$2b,$83,$2a,$83,$27,$89,$28,$89,$20,$83,$21,$83,$23
	.byte $89,$1c,$83,$20,$83,$21,$83
@ref6:
	.byte $8b,$2c,$83,$2b,$83,$2a,$83,$27,$89,$28,$89,$2d,$89,$2d,$83,$2d
	.byte $95
	.byte $ff,$17
	.word @ref5
@ref8:
	.byte $8b,$24,$8f,$21,$8f,$20,$ad
	.byte $ff,$17
	.word @ref5
	.byte $ff,$11
	.word @ref6
	.byte $ff,$17
	.word @ref5
	.byte $ff,$07
	.word @ref8
@ref13:
	.byte $24,$83,$24,$89,$24,$89,$24,$83,$26,$89,$23,$83,$20,$89,$20,$83
	.byte $1c,$95
@ref14:
	.byte $24,$83,$24,$89,$24,$89,$24,$83,$26,$83,$23,$b3
	.byte $ff,$12
	.word @ref13
@ref16:
	.byte $22,$83,$22,$89,$22,$89,$22,$83,$22,$89,$27,$95,$23,$95
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
	.byte $ff,$0e
	.word @ref1
	.byte $ff,$14
	.word @ref2
@ref21:
	.byte $28,$83,$25,$89,$20,$8f,$20,$89,$21,$83,$28,$89,$28,$83,$21,$95
@ref22:
	.byte $23,$85,$2d,$85,$2d,$85,$2d,$85,$2c,$85,$2a,$85,$28,$85,$25,$85
	.byte $21,$85,$20,$95
	.byte $ff,$10
	.word @ref21
@ref24:
	.byte $23,$85,$2a,$87,$2a,$83,$2a,$85,$28,$85,$27,$85,$23,$83,$20,$89
	.byte $20,$83,$1c,$95
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref22
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref24
	.byte $ff,$12
	.word @ref13
	.byte $ff,$0c
	.word @ref14
	.byte $ff,$12
	.word @ref13
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref22
	.byte $ff,$10
	.word @ref21
	.byte $ff,$14
	.word @ref24
	.byte $fd
	.word @song0ch0loop

; Overworld
@song0ch1:
@song0ch1loop:
@ref37:
	.byte $86,$2c,$83,$2c,$89,$2c,$89,$28,$83,$2c,$89,$2f,$ad
@ref38:
	.byte $28,$8f,$23,$8f,$20,$8f,$25,$89,$27,$89,$26,$83,$25,$89
@ref39:
	.byte $23,$85,$2c,$85,$2f,$85,$31,$89,$2d,$83,$2f,$89,$2c,$89,$28,$83
	.byte $2a,$83,$27,$8f
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
@ref42:
	.byte $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$24,$83,$25,$83,$28
	.byte $89,$25,$83,$28,$83,$2a,$83
@ref43:
	.byte $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$34,$89,$34,$83,$34
	.byte $95
	.byte $ff,$17
	.word @ref42
@ref45:
	.byte $8b,$2b,$8f,$2a,$8f,$28,$ad
	.byte $ff,$17
	.word @ref42
	.byte $ff,$11
	.word @ref43
	.byte $ff,$17
	.word @ref42
	.byte $ff,$07
	.word @ref45
@ref50:
	.byte $28,$83,$28,$89,$28,$89,$28,$83,$2a,$89,$2c,$83,$28,$89,$25,$83
	.byte $23,$95
@ref51:
	.byte $28,$83,$28,$89,$28,$89,$28,$83,$2a,$83,$2c,$b3
	.byte $ff,$12
	.word @ref50
@ref53:
	.byte $2c,$83,$2c,$89,$2c,$89,$28,$83,$2c,$89,$2f,$ad
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$14
	.word @ref39
@ref58:
	.byte $2c,$83,$28,$89,$23,$8f,$24,$89,$25,$83,$2d,$89,$2d,$83,$25,$95
@ref59:
	.byte $27,$85,$31,$85,$31,$85,$31,$85,$2f,$85,$2d,$85,$2c,$85,$28,$85
	.byte $25,$85,$23,$95
	.byte $ff,$10
	.word @ref58
@ref61:
	.byte $27,$85,$2d,$87,$2d,$83,$2d,$85,$2c,$85,$2a,$85,$28,$ad
	.byte $ff,$10
	.word @ref58
	.byte $ff,$14
	.word @ref59
	.byte $ff,$10
	.word @ref58
	.byte $ff,$0e
	.word @ref61
	.byte $ff,$12
	.word @ref50
	.byte $ff,$0c
	.word @ref51
	.byte $ff,$12
	.word @ref50
	.byte $ff,$0c
	.word @ref53
	.byte $ff,$10
	.word @ref58
	.byte $ff,$14
	.word @ref59
	.byte $ff,$10
	.word @ref58
	.byte $ff,$0e
	.word @ref61
	.byte $fd
	.word @song0ch1loop

; Overworld
@song0ch2:
@song0ch2loop:
@ref74:
	.byte $80,$1e,$83,$1e,$89,$1e,$89,$1e,$83,$1e,$89,$2f,$95,$23,$95
@ref75:
	.byte $23,$8f,$20,$8f,$1c,$8f,$21,$89,$23,$89,$22,$83,$21,$89
@ref76:
	.byte $86,$20,$85,$28,$85,$2c,$85,$2d,$89,$2a,$83,$2c,$89,$28,$89,$25
	.byte $83,$27,$83,$23,$8f
@ref77:
	.byte $80,$23,$8f,$20,$8f,$1c,$8f,$21,$89,$23,$89,$22,$83,$21,$89
	.byte $ff,$14
	.word @ref76
@ref79:
	.byte $1c,$8f,$23,$8f,$28,$89,$21,$8f,$28,$83,$28,$89,$21,$89
@ref80:
	.byte $1c,$8f,$20,$8f,$23,$83,$28,$89,$3b,$89,$3b,$83,$3b,$89,$23,$89
	.byte $ff,$0e
	.word @ref79
@ref82:
	.byte $80,$1c,$89,$24,$8f,$26,$8f,$28,$8f,$23,$83,$23,$89,$1c,$89
@ref83:
	.byte $86,$1c,$8f,$23,$8f,$28,$89,$21,$8f,$28,$83,$28,$89,$21,$89
	.byte $ff,$10
	.word @ref80
	.byte $ff,$0e
	.word @ref79
	.byte $ff,$0e
	.word @ref82
@ref87:
	.byte $18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0c
	.word @ref87
@ref90:
	.byte $1e,$83,$1e,$89,$1e,$89,$1e,$83,$1e,$89,$2f,$95,$23,$95
	.byte $ff,$0e
	.word @ref75
	.byte $ff,$14
	.word @ref76
	.byte $ff,$0e
	.word @ref77
	.byte $ff,$14
	.word @ref76
@ref95:
	.byte $80,$1c,$8f,$22,$83,$23,$89,$28,$89,$21,$89,$21,$89,$28,$83,$28
	.byte $83,$21,$89
@ref96:
	.byte $1e,$8f,$21,$83,$23,$89,$27,$89,$23,$89,$23,$89,$28,$83,$28,$83
	.byte $23,$89
@ref97:
	.byte $1c,$8f,$22,$83,$23,$89,$28,$89,$21,$89,$21,$89,$28,$83,$28,$83
	.byte $21,$89
@ref98:
	.byte $86,$23,$8f,$23,$83,$23,$85,$25,$85,$27,$85,$28,$89,$23,$89,$1c
	.byte $95
	.byte $ff,$12
	.word @ref95
	.byte $ff,$12
	.word @ref96
	.byte $ff,$12
	.word @ref97
	.byte $ff,$10
	.word @ref98
@ref103:
	.byte $80,$18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0c
	.word @ref87
	.byte $ff,$0e
	.word @ref90
	.byte $ff,$12
	.word @ref97
	.byte $ff,$12
	.word @ref96
	.byte $ff,$12
	.word @ref97
	.byte $ff,$10
	.word @ref98
	.byte $fd
	.word @song0ch2loop

; Overworld
@song0ch3:
@song0ch3loop:
@ref111:
	.byte $82,$0c,$89,$84,$0c,$83,$82,$0c,$89,$84,$0c,$83,$82,$0c,$89,$0c
	.byte $8f,$0c,$89,$84,$0c,$83,$0c,$83,$0c,$83
@ref112:
	.byte $03,$89,$0c,$85,$0c,$81,$82,$0c,$89,$84,$0c,$85,$0c,$81,$03,$89
	.byte $0c,$85,$0c,$81,$82,$0c,$89,$84,$0c,$85,$0c,$81
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
	.byte $ff,$18
	.word @ref112
@ref132:
	.byte $0c,$8f,$0c,$83,$82,$0c,$89,$84,$0c,$89,$0c,$8f,$0c,$83,$82,$0c
	.byte $89,$84,$0c,$89
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$14
	.word @ref111
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $ff,$10
	.word @ref132
	.byte $fd
	.word @song0ch3loop

; Overworld
@song0ch4:
@song0ch4loop:
@ref148:
	.byte $df
@ref149:
	.byte $df
@ref150:
	.byte $df
@ref151:
	.byte $df
@ref152:
	.byte $df
@ref153:
	.byte $df
@ref154:
	.byte $df
@ref155:
	.byte $df
@ref156:
	.byte $df
@ref157:
	.byte $df
@ref158:
	.byte $df
@ref159:
	.byte $df
@ref160:
	.byte $df
@ref161:
	.byte $df
@ref162:
	.byte $df
@ref163:
	.byte $df
@ref164:
	.byte $df
@ref165:
	.byte $df
@ref166:
	.byte $df
@ref167:
	.byte $df
@ref168:
	.byte $df
@ref169:
	.byte $df
@ref170:
	.byte $df
@ref171:
	.byte $df
@ref172:
	.byte $df
@ref173:
	.byte $df
@ref174:
	.byte $df
@ref175:
	.byte $df
@ref176:
	.byte $df
@ref177:
	.byte $df
@ref178:
	.byte $df
@ref179:
	.byte $df
@ref180:
	.byte $df
@ref181:
	.byte $df
@ref182:
	.byte $df
@ref183:
	.byte $df
@ref184:
	.byte $df
	.byte $fd
	.word @song0ch4loop
