;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


princess_saved_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; You saved the princess

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c0,$c2,$00,$01


; You saved the princess
@song0ch0:
	.byte $fb,$02
@ref0:
	.byte $82,$23,$85,$22,$85,$23,$85
@song0ch0loop:
@ref1:
	.byte $82,$20,$ad,$21,$95,$22,$95,$23,$ad,$28,$95,$2c,$8f,$2c,$83
@ref2:
	.byte $2a,$95,$2c,$95,$2d,$95,$27,$95,$2a,$ad,$28,$95,$23,$85,$22,$85
	.byte $23,$85
	.byte $fd
	.word @song0ch0loop

; You saved the princess
@song0ch1:
@ref3:
	.byte $97
@song0ch1loop:
@ref4:
	.byte $82,$17,$ad,$19,$95,$1a,$95,$1b,$ad,$20,$95,$23,$95
@ref5:
	.byte $21,$95,$23,$95,$25,$95,$1e,$95,$21,$95,$00,$95,$20,$95,$00,$95
	.byte $fd
	.word @song0ch1loop

; You saved the princess
@song0ch2:
@ref6:
	.byte $80,$1b,$95
@song0ch2loop:
@ref7:
	.byte $80,$1c,$ad,$1e,$95,$1f,$95,$20,$95,$1c,$95,$25,$95,$23,$95
@ref8:
	.byte $21,$95,$20,$95,$1e,$95,$21,$95,$23,$95,$17,$95,$1c,$95,$1b,$95
	.byte $fd
	.word @song0ch2loop

; You saved the princess
@song0ch3:
@ref9:
	.byte $97
@song0ch3loop:
@ref10:
	.byte $f9,$c5
@ref11:
	.byte $f9,$c5
	.byte $fd
	.word @song0ch3loop

; You saved the princess
@song0ch4:
@ref12:
	.byte $97
@song0ch4loop:
@ref13:
	.byte $f9,$c5
@ref14:
	.byte $f9,$c5
	.byte $fd
	.word @song0ch4loop
