;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


underground_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Underworld

@instruments:
	.word @env2,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$c8,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	.byte $cf,$07,$c0,$00,$02
@env3:
	.byte $c2,$00,$00


; Underworld
@song0ch0:
	.byte $fb,$03
@song0ch0loop:
@ref0:
	.byte $f9,$95
@ref1:
	.byte $f9,$95
@ref2:
	.byte $f9,$95
@ref3:
	.byte $c7
	.byte $fd
	.word @song0ch0loop

; Underworld
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $82,$1c,$83,$28,$83,$19,$83,$25,$83,$1a,$83,$26,$a7,$1c,$83,$28
	.byte $83,$19,$83,$25,$83,$1a,$83,$26,$a7
@ref5:
	.byte $15,$83,$21,$83,$12,$83,$1e,$83,$13,$83,$1f,$a7,$15,$83,$21,$83
	.byte $12,$83,$1e,$83,$13,$83,$1f,$9b,$1f,$81,$1e,$81,$1d,$81
@ref6:
	.byte $1c,$89,$1f,$89,$1e,$89,$18,$89,$17,$89,$1d,$89,$1c,$81,$22,$81
	.byte $21,$81,$20,$81,$26,$81,$25,$81,$24,$85,$1f,$85,$1b,$85,$1a,$85
	.byte $19,$85,$18,$85
@ref7:
	.byte $c7
	.byte $fd
	.word @song0ch1loop

; Underworld
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $80,$1c,$83,$28,$83,$19,$83,$25,$83,$1a,$83,$26,$a7,$1c,$83,$28
	.byte $83,$19,$83,$25,$83,$1a,$83,$26,$a7
	.byte $ff,$1e
	.word @ref5
	.byte $ff,$24
	.word @ref6
@ref11:
	.byte $c7
	.byte $fd
	.word @song0ch2loop

; Underworld
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $f9,$95
@ref13:
	.byte $f9,$95
@ref14:
	.byte $f9,$95
@ref15:
	.byte $c7
	.byte $fd
	.word @song0ch3loop

; Underworld
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $f9,$95
@ref17:
	.byte $f9,$95
@ref18:
	.byte $f9,$95
@ref19:
	.byte $c7
	.byte $fd
	.word @song0ch4loop
