;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


water_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Waterworld

@instruments:
	.word @env4,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env0
	.word @env3,@env0,@env0,@env5

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$04,$c0,$00,$02
@env2:
	.byte $cc,$c0,$00,$01
@env3:
	.byte $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	.byte $c0,$00,$10
@env4:
	.byte $cf,$00,$00
@env5:
	.byte $c0,$c2,$00,$01


; Waterworld
@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $86,$1e,$85,$1d,$85,$1c,$85,$1b,$85,$1c,$85,$1d,$85,$1e,$81,$1e
	.byte $81,$1e,$81,$00,$81,$20,$81,$00,$81,$21,$91,$00,$81
@ref1:
	.byte $23,$95,$22,$95,$23,$ad
@ref2:
	.byte $23,$95,$22,$8d,$25,$85,$23,$ad
@ref3:
	.byte $21,$95,$20,$95,$21,$ad
@ref4:
	.byte $21,$95,$1b,$8d,$25,$85,$23,$ad
@ref5:
	.byte $2c,$95,$2a,$95,$29,$ad
@ref6:
	.byte $2a,$95,$29,$95,$28,$ad
@ref7:
	.byte $1c,$95,$21,$85,$23,$85,$27,$85,$27,$81,$27,$81,$27,$89,$21,$81
	.byte $20,$95
	.byte $fd
	.word @song0ch0loop

; Waterworld
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $86,$1e,$85,$20,$85,$22,$85,$23,$85,$25,$85,$26,$85,$27,$81,$27
	.byte $81,$27,$81,$00,$81,$27,$81,$00,$81,$27,$8d,$23,$85
@ref9:
	.byte $2c,$95,$2b,$95,$2c,$99,$23,$81,$25,$81,$27,$81,$28,$81,$2a,$81
@ref10:
	.byte $2c,$95,$2b,$8d,$2d,$85,$2c,$a9,$23,$81
@ref11:
	.byte $2a,$95,$29,$95,$2a,$99,$23,$81,$25,$81,$27,$81,$28,$81,$29,$81
@ref12:
	.byte $2a,$95,$23,$8d,$2d,$85,$2c,$a9,$23,$81
@ref13:
	.byte $2f,$95,$2f,$95,$2f,$95,$2f,$85,$31,$81,$00,$85,$2f,$81
@ref14:
	.byte $2d,$95,$2d,$95,$2d,$95,$2d,$85,$2f,$81,$00,$85,$2d,$81
@ref15:
	.byte $2c,$95,$25,$85,$27,$85,$2d,$85,$2c,$81,$2c,$81,$2c,$89,$27,$81
	.byte $28,$95
	.byte $fd
	.word @song0ch1loop

; Waterworld
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $80,$00,$bd,$80,$23,$81,$00,$81,$23,$95
@ref17:
	.byte $1c,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	.byte $28,$81,$00,$81,$20,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
	.byte $ff,$30
	.word @ref17
@ref19:
	.byte $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1d,$81,$00,$81
	.byte $22,$81,$00,$81,$26,$81,$00,$81,$1e,$81,$00,$81,$23,$81,$00,$81
	.byte $27,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81
@ref20:
	.byte $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	.byte $28,$81,$00,$81,$17,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
@ref21:
	.byte $1c,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$1b,$81,$00,$81
	.byte $23,$81,$00,$81,$2a,$81,$00,$81,$1a,$81,$00,$81,$23,$81,$00,$81
	.byte $29,$81,$00,$81,$1d,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81
@ref22:
	.byte $1e,$81,$00,$81,$25,$81,$00,$81,$2d,$81,$00,$81,$1d,$81,$00,$81
	.byte $25,$81,$00,$81,$2d,$81,$00,$81,$1c,$81,$00,$81,$25,$81,$00,$81
	.byte $2d,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$2d,$81,$00,$81
@ref23:
	.byte $10,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$17,$81,$00,$81
	.byte $23,$81,$00,$81,$23,$81,$00,$81,$21,$91,$1b,$81,$1c,$95
	.byte $fd
	.word @song0ch2loop

; Waterworld
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $87,$84,$0c,$85,$82,$0c,$8d,$84,$0c,$81,$0c,$81,$82,$0c,$8d,$84
	.byte $0c,$85,$82,$0c,$8d,$84,$0c,$81,$0c,$81,$82,$0c,$85
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $ff,$15
	.word @ref24
	.byte $fd
	.word @song0ch3loop

; Waterworld
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $df
@ref33:
	.byte $df
@ref34:
	.byte $df
@ref35:
	.byte $df
@ref36:
	.byte $df
@ref37:
	.byte $df
@ref38:
	.byte $df
@ref39:
	.byte $df
	.byte $fd
	.word @song0ch4loop
