;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


music_music_data:
	db 17
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Overworld
	dw @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; Waterworld
	dw @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256 ; Underworld
	dw @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; Castleworld
	dw @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,331,276 ; Starman
	dw @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256 ; Death
	dw @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,249,208 ; You saved the princess
	dw @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256 ; In an other castle
	dw @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256 ; Victory
	dw @song9ch0,@song9ch1,@song9ch2,@song9ch3,@song9ch4,307,256 ; Hurry up
	dw @song10ch0,@song10ch1,@song10ch2,@song10ch3,@song10ch4,307,256 ; W2
	dw @song11ch0,@song11ch1,@song11ch2,@song11ch3,@song11ch4,307,256 ; W3
	dw @song12ch0,@song12ch1,@song12ch2,@song12ch3,@song12ch4,307,256 ; W4
	dw @song13ch0,@song13ch1,@song13ch2,@song13ch3,@song13ch4,307,256 ; W5
	dw @song14ch0,@song14ch1,@song14ch2,@song14ch3,@song14ch4,307,256 ; W6
	dw @song15ch0,@song15ch1,@song15ch2,@song15ch3,@song15ch4,307,256 ; W7
	dw @song16ch0,@song16ch1,@song16ch2,@song16ch3,@song16ch4,307,256 ; W8

@instruments:
	dw @env10,@env0,@env0,@env0
	dw @env2,@env0,@env0,@env0
	dw @env3,@env0,@env0,@env0
	dw @env4,@env0,@env0,@env0
	dw @env1,@env0,@env0,@env20
	dw @env5,@env0,@env0,@env19
	dw @env6,@env0,@env0,@env20
	dw @env7,@env17,@env0,@env20
	dw @env8,@env17,@env0,@env20
	dw @env9,@env0,@env0,@env20
	dw @env11,@env0,@env0,@env0
	dw @env13,@env18,@env0,@env0
	dw @env14,@env0,@env0,@env20
	dw @env14,@env0,@env0,@env20
	dw @env12,@env0,@env0,@env21
	dw @env15,@env0,@env0,@env22
	dw @env16,@env0,@env0,@env23

@samples:
@env0:
	db $c0,$00,$00
@env1:
	db $cf,$cf,$c7,$c6,$c5,$c5,$c4,$c4,$c0,$00,$08
@env2:
	db $cf,$07,$c0,$00,$02
@env3:
	db $cc,$04,$c0,$00,$02
@env4:
	db $cc,$c0,$00,$01
@env5:
	db $c5,$c3,$c4,$c5,$c5,$c6,$10,$c5,$05,$c4,$05,$c3,$02,$c2,$c2,$c1
	db $c0,$00,$10
@env6:
	db $c0,$cb,$ca,$c9,$c8,$00,$04
@env7:
	db $ce,$cc,$cb,$ca,$c8,$c7,$c6,$c4,$c3,$c2,$c0,$00,$0a
@env8:
	db $c8,$c4,$c0,$00,$02
@env9:
	db $ce,$cd,$cb,$ca,$c9,$c7,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0b
@env10:
	db $cf,$00,$00
@env11:
	db $ce,$c2,$c0,$00,$02
@env12:
	db $ca,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$05
	db $c0,$00,$10
@env13:
	db $cd,$c5,$c4,$c2,$c1,$c0,$c0,$00,$06
@env14:
	db $ca,$c5,$c4,$c3,$c4,$c2,$c1,$02,$c0,$09,$c0,$00,$0a
@env15:
	db $ca,$c9,$c8,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$c7
	db $c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$02,$c1,$c1,$c0,$c5,$c4,$c4
	db $c3,$02,$c2,$03,$c1,$03,$c0,$c0,$c3,$c2,$02,$c1,$08,$c0,$00,$2d
@env16:
	db $ca,$c8,$c7,$c5,$c6,$c6,$c5,$36,$c4,$c2,$c0,$00,$0a
@env17:
	db $c0,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$00,$0a
@env18:
	db $c8,$c9,$c9,$cc,$00,$03
@env19:
	db $c0,$c2,$00,$01
@env20:
	db $c2,$00,$00
@env21:
	db $c0,$c1,$00,$01
@env22:
	db $c1,$00,$00
@env23:
	db $c0,$c1,$c0,$c0,$c2,$00,$04


; Overworld
@song0ch0:
	db $fb,$03
@song0ch0loop:
@ref0:
	db $88,$16,$83,$16,$89,$16,$89,$16,$83,$16,$89,$1b,$95,$17,$95
@ref1:
	db $14,$8f,$10,$8f,$0b,$8f,$10,$89,$12,$89,$11,$83,$10,$89
@ref2:
	db $10,$85,$17,$85,$1b,$85,$1c,$89,$19,$83,$1b,$89,$19,$89,$14,$83
	db $15,$83,$12,$8f
	db $ff,$0e
	dw @ref1
	db $ff,$14
	dw @ref2
@ref5:
	db $8b,$20,$83,$1f,$83,$1e,$83,$1b,$89,$1c,$89,$14,$83,$15,$83,$17
	db $89,$10,$83,$14,$83,$15,$83
@ref6:
	db $8b,$20,$83,$1f,$83,$1e,$83,$1b,$89,$1c,$89,$21,$89,$21,$83,$21
	db $95
	db $ff,$17
	dw @ref5
@ref8:
	db $8b,$18,$8f,$15,$8f,$14,$ad
@ref9:
	db $18,$83,$18,$89,$18,$89,$18,$83,$1a,$89,$17,$83,$14,$89,$14,$83
	db $10,$95
@ref10:
	db $18,$83,$18,$89,$18,$89,$18,$83,$1a,$83,$17,$b3
	db $ff,$12
	dw @ref9
@ref12:
	db $16,$83,$16,$89,$16,$89,$16,$83,$16,$89,$1b,$95,$17,$95
	db $ff,$0e
	dw @ref1
	db $ff,$14
	dw @ref2
	db $ff,$0e
	dw @ref1
	db $ff,$14
	dw @ref2
@ref17:
	db $1c,$83,$19,$89,$14,$8f,$14,$89,$15,$83,$1c,$89,$1c,$83,$15,$95
@ref18:
	db $17,$85,$21,$85,$21,$85,$21,$85,$20,$85,$1e,$85,$1c,$85,$19,$85
	db $15,$85,$14,$95
	db $ff,$10
	dw @ref17
@ref20:
	db $17,$85,$1e,$87,$1e,$83,$1e,$85,$1c,$85,$1b,$85,$17,$83,$14,$89
	db $14,$83,$10,$95
	db $ff,$12
	dw @ref9
	db $ff,$0c
	dw @ref10
	db $ff,$12
	dw @ref9
	db $fd
	dw @song0ch0loop

; Overworld
@song0ch1:
@song0ch1loop:
@ref24:
	db $88,$20,$83,$20,$89,$20,$89,$1c,$83,$20,$89,$23,$ad
@ref25:
	db $1c,$8f,$17,$8f,$14,$8f,$19,$89,$1b,$89,$1a,$83,$19,$89
@ref26:
	db $17,$85,$20,$85,$23,$85,$25,$89,$21,$83,$23,$89,$20,$89,$1c,$83
	db $1e,$83,$1b,$8f
	db $ff,$0e
	dw @ref25
	db $ff,$14
	dw @ref26
@ref29:
	db $8b,$23,$83,$22,$83,$21,$83,$1f,$89,$20,$89,$18,$83,$19,$83,$1c
	db $89,$19,$83,$1c,$83,$1e,$83
@ref30:
	db $8b,$23,$83,$22,$83,$21,$83,$1f,$89,$20,$89,$28,$89,$28,$83,$28
	db $95
	db $ff,$17
	dw @ref29
@ref32:
	db $8b,$1f,$8f,$1e,$8f,$1c,$ad
@ref33:
	db $1c,$83,$1c,$89,$1c,$89,$1c,$83,$1e,$89,$20,$83,$1c,$89,$19,$83
	db $17,$95
@ref34:
	db $1c,$83,$1c,$89,$1c,$89,$1c,$83,$1e,$83,$20,$b3
	db $ff,$12
	dw @ref33
@ref36:
	db $20,$83,$20,$89,$20,$89,$1c,$83,$20,$89,$23,$ad
	db $ff,$0e
	dw @ref25
	db $ff,$14
	dw @ref26
	db $ff,$0e
	dw @ref25
	db $ff,$14
	dw @ref26
@ref41:
	db $20,$83,$1c,$89,$17,$8f,$18,$89,$19,$83,$21,$89,$21,$83,$19,$95
@ref42:
	db $1b,$85,$25,$85,$25,$85,$25,$85,$23,$85,$21,$85,$20,$85,$1c,$85
	db $19,$85,$17,$95
	db $ff,$10
	dw @ref41
@ref44:
	db $1b,$85,$21,$87,$21,$83,$21,$85,$20,$85,$1e,$85,$1c,$ad
	db $ff,$12
	dw @ref33
	db $ff,$0c
	dw @ref34
	db $ff,$12
	dw @ref33
	db $fd
	dw @song0ch1loop

; Overworld
@song0ch2:
@song0ch2loop:
@ref48:
	db $82,$12,$83,$12,$89,$12,$89,$12,$83,$12,$89,$23,$95,$17,$95
@ref49:
	db $17,$8f,$14,$8f,$10,$8f,$15,$89,$17,$89,$16,$83,$15,$89
@ref50:
	db $88,$14,$85,$1c,$85,$20,$85,$21,$89,$1e,$83,$20,$89,$1c,$89,$19
	db $83,$1b,$83,$17,$8f
@ref51:
	db $82,$17,$8f,$14,$8f,$10,$8f,$15,$89,$17,$89,$16,$83,$15,$89
	db $ff,$14
	dw @ref50
@ref53:
	db $10,$8f,$17,$8f,$1c,$89,$15,$8f,$1c,$83,$1c,$89,$15,$89
@ref54:
	db $10,$8f,$14,$8f,$17,$83,$1c,$89,$2f,$89,$2f,$83,$2f,$89,$17,$89
	db $ff,$0e
	dw @ref53
@ref56:
	db $82,$10,$89,$18,$8f,$1a,$8f,$1c,$8f,$17,$83,$17,$89,$10,$89
@ref57:
	db $18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	db $ff,$0c
	dw @ref57
	db $ff,$0c
	dw @ref57
@ref60:
	db $12,$83,$12,$89,$12,$89,$12,$83,$12,$89,$23,$95,$17,$95
	db $ff,$0e
	dw @ref49
	db $ff,$14
	dw @ref50
	db $ff,$0e
	dw @ref51
	db $ff,$14
	dw @ref50
@ref65:
	db $82,$10,$8f,$16,$83,$17,$89,$1c,$89,$15,$89,$15,$89,$1c,$83,$1c
	db $83,$15,$89
@ref66:
	db $12,$8f,$15,$83,$17,$89,$1b,$89,$17,$89,$17,$89,$1c,$83,$1c,$83
	db $17,$89
@ref67:
	db $10,$8f,$16,$83,$17,$89,$1c,$89,$15,$89,$15,$89,$1c,$83,$1c,$83
	db $15,$89
@ref68:
	db $88,$17,$8f,$17,$83,$17,$85,$19,$85,$1b,$85,$1c,$89,$17,$89,$10
	db $95
@ref69:
	db $82,$18,$8f,$1f,$8f,$24,$89,$23,$8f,$1c,$8f,$17,$89
	db $ff,$0c
	dw @ref57
	db $ff,$0c
	dw @ref57
	db $fd
	dw @song0ch2loop

; Overworld
@song0ch3:
@song0ch3loop:
@ref72:
	db $84,$0b,$89,$86,$0b,$83,$84,$0b,$89,$86,$0b,$83,$84,$0b,$89,$0b
	db $8f,$0b,$89,$86,$0b,$83,$0b,$83,$0b,$83
@ref73:
	db $02,$89,$0b,$85,$0b,$81,$84,$0b,$89,$86,$0b,$85,$0b,$81,$02,$89
	db $0b,$85,$0b,$81,$84,$0b,$89,$86,$0b,$85,$0b,$81
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$14
	dw @ref72
	db $ff,$14
	dw @ref72
	db $ff,$14
	dw @ref72
	db $ff,$14
	dw @ref72
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
	db $ff,$18
	dw @ref73
@ref89:
	db $0c,$8f,$0c,$83,$84,$0c,$89,$86,$0c,$89,$0c,$8f,$0c,$83,$84,$0c
	db $89,$86,$0c,$89
	db $ff,$10
	dw @ref89
	db $ff,$10
	dw @ref89
	db $ff,$10
	dw @ref89
	db $ff,$14
	dw @ref72
	db $ff,$14
	dw @ref72
	db $ff,$14
	dw @ref72
	db $fd
	dw @song0ch3loop

; Overworld
@song0ch4:
@song0ch4loop:
@ref96:
	db $df
@ref97:
	db $df
@ref98:
	db $df
@ref99:
	db $df
@ref100:
	db $df
@ref101:
	db $df
@ref102:
	db $df
@ref103:
	db $df
@ref104:
	db $df
@ref105:
	db $df
@ref106:
	db $df
@ref107:
	db $df
@ref108:
	db $df
@ref109:
	db $df
@ref110:
	db $df
@ref111:
	db $df
@ref112:
	db $df
@ref113:
	db $df
@ref114:
	db $df
@ref115:
	db $df
@ref116:
	db $df
@ref117:
	db $df
@ref118:
	db $df
@ref119:
	db $df
	db $fd
	dw @song0ch4loop


; Waterworld
@song1ch0:
	db $fb,$04
@song1ch0loop:
@ref120:
	db $9e,$1e,$85,$1d,$85,$1c,$85,$1b,$85,$1c,$85,$1d,$85,$1e,$81,$1e
	db $81,$1e,$81,$00,$81,$20,$81,$00,$81,$86,$21,$91,$00,$81
@ref121:
	db $9e,$23,$95,$22,$95,$23,$ad
@ref122:
	db $23,$95,$22,$8d,$25,$85,$23,$ad
@ref123:
	db $21,$95,$20,$95,$21,$ad
@ref124:
	db $21,$95,$1b,$8d,$25,$85,$23,$ad
@ref125:
	db $2c,$95,$2a,$95,$29,$ad
@ref126:
	db $2a,$95,$29,$95,$28,$ad
@ref127:
	db $1c,$95,$21,$85,$23,$85,$27,$85,$27,$81,$27,$81,$27,$89,$21,$81
	db $20,$95
	db $fd
	dw @song1ch0loop

; Waterworld
@song1ch1:
@song1ch1loop:
@ref128:
	db $9e,$1e,$85,$20,$85,$22,$85,$23,$85,$25,$85,$26,$85,$27,$81,$27
	db $81,$27,$81,$00,$81,$27,$81,$00,$81,$27,$8d,$23,$85
@ref129:
	db $2c,$95,$2b,$95,$2c,$99,$23,$81,$25,$81,$27,$81,$28,$81,$2a,$81
@ref130:
	db $2c,$95,$2b,$8d,$2d,$85,$2c,$a9,$23,$81
@ref131:
	db $2a,$95,$29,$95,$2a,$99,$23,$81,$25,$81,$27,$81,$28,$81,$29,$81
@ref132:
	db $2a,$95,$23,$8d,$2d,$85,$2c,$a9,$23,$81
@ref133:
	db $2f,$95,$2f,$95,$2f,$95,$2f,$85,$31,$81,$00,$85,$2f,$81
@ref134:
	db $2d,$95,$2d,$95,$2d,$95,$2d,$85,$2f,$81,$00,$85,$2d,$81
@ref135:
	db $2c,$95,$25,$85,$27,$85,$2d,$85,$2c,$81,$2c,$81,$2c,$89,$27,$81
	db $28,$95
	db $fd
	dw @song1ch1loop

; Waterworld
@song1ch2:
@song1ch2loop:
@ref136:
	db $80,$00,$bd,$80,$23,$81,$00,$81,$23,$95
@ref137:
	db $1c,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81,$1b,$81,$00,$81
	db $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	db $28,$81,$00,$81,$20,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
	db $ff,$30
	dw @ref137
@ref139:
	db $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1d,$81,$00,$81
	db $22,$81,$00,$81,$26,$81,$00,$81,$1e,$81,$00,$81,$23,$81,$00,$81
	db $27,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81
@ref140:
	db $1e,$81,$00,$81,$23,$81,$00,$81,$27,$81,$00,$81,$1b,$81,$00,$81
	db $23,$81,$00,$81,$27,$81,$00,$81,$1c,$81,$00,$81,$23,$81,$00,$81
	db $28,$81,$00,$81,$17,$81,$00,$81,$23,$81,$00,$81,$28,$81,$00,$81
@ref141:
	db $1c,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$1b,$81,$00,$81
	db $23,$81,$00,$81,$2a,$81,$00,$81,$1a,$81,$00,$81,$23,$81,$00,$81
	db $29,$81,$00,$81,$1d,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81
@ref142:
	db $1e,$81,$00,$81,$25,$81,$00,$81,$2d,$81,$00,$81,$1d,$81,$00,$81
	db $25,$81,$00,$81,$2d,$81,$00,$81,$1c,$81,$00,$81,$25,$81,$00,$81
	db $2d,$81,$00,$81,$1b,$81,$00,$81,$23,$81,$00,$81,$2d,$81,$00,$81
@ref143:
	db $10,$81,$00,$81,$23,$81,$00,$81,$2c,$81,$00,$81,$17,$81,$00,$81
	db $23,$81,$00,$81,$23,$81,$00,$81,$21,$91,$1b,$81,$1c,$95
	db $fd
	dw @song1ch2loop

; Waterworld
@song1ch3:
@song1ch3loop:
@ref144:
	db $87,$86,$0c,$85,$84,$0c,$8d,$86,$0c,$81,$0c,$81,$84,$0c,$8d,$86
	db $0c,$85,$84,$0c,$8d,$86,$0c,$81,$0c,$81,$84,$0c,$85
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $ff,$15
	dw @ref144
	db $fd
	dw @song1ch3loop

; Waterworld
@song1ch4:
@song1ch4loop:
@ref152:
	db $df
@ref153:
	db $df
@ref154:
	db $df
@ref155:
	db $df
@ref156:
	db $df
@ref157:
	db $df
@ref158:
	db $df
@ref159:
	db $df
	db $fd
	dw @song1ch4loop


; Underworld
@song2ch0:
	db $fb,$03
@song2ch0loop:
@ref160:
	db $af
@ref161:
	db $af
@ref162:
	db $98,$00,$83,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$89
@ref163:
	db $81,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$8d
@ref164:
	db $00,$83,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$89
	db $ff,$0d
	dw @ref163
@ref166:
	db $00,$83,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$89
@ref167:
	db $81,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$8d
	db $ff,$0e
	dw @ref166
@ref169:
	db $81,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$83,$28,$81,$27
	db $1c,$26
@ref170:
	db $81,$25,$87,$19,$28,$87,$1c,$27,$87,$1b,$21,$87
@ref171:
	db $15,$20,$87,$14,$26,$87,$1a,$25,$81,$2b,$81,$2a,$19,$29,$1f,$2f
	db $1e,$2e
@ref172:
	db $23,$2d,$83,$21,$28,$83,$1c,$24,$83,$18,$23,$83,$17,$22,$83,$16
	db $21,$83
@ref173:
	db $00,$93,$00,$97
@ref174:
	db $af
@ref175:
	db $af
	db $fd
	dw @song2ch0loop

; Underworld
@song2ch1:
@song2ch1loop:
@ref176:
	db $af
@ref177:
	db $af
@ref178:
	db $88,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$8f
@ref179:
	db $98,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$8f
	db $ff,$0c
	dw @ref178
	db $ff,$0c
	dw @ref179
@ref182:
	db $88,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$8f
@ref183:
	db $98,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$8f
	db $ff,$0c
	dw @ref182
@ref185:
	db $98,$12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$83,$88,$1c,$81
	db $1b,$81,$1a,$81
@ref186:
	db $19,$89,$1c,$89,$1b,$89,$15,$89
@ref187:
	db $14,$89,$1a,$89,$19,$81,$1f,$81,$1e,$81,$1d,$81,$23,$81,$22,$81
@ref188:
	db $21,$85,$1c,$85,$18,$85,$17,$85,$16,$85,$15,$85
@ref189:
	db $af
@ref190:
	db $af
@ref191:
	db $af
	db $fd
	dw @song2ch1loop

; Underworld
@song2ch2:
@song2ch2loop:
@ref192:
	db $af
@ref193:
	db $af
@ref194:
	db $82,$19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$8f
@ref195:
	db $af
@ref196:
	db $19,$83,$25,$83,$16,$83,$22,$83,$17,$83,$23,$8f
@ref197:
	db $af
@ref198:
	db $12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$85,$00,$87
@ref199:
	db $af
@ref200:
	db $12,$83,$1e,$83,$0f,$83,$1b,$83,$10,$83,$1c,$8f
@ref201:
	db $00,$95,$00,$89,$1c,$81,$1b,$81,$1a,$81
	db $ff,$08
	dw @ref186
	db $ff,$10
	dw @ref187
	db $ff,$0c
	dw @ref188
@ref205:
	db $00,$95,$00,$95
@ref206:
	db $af
@ref207:
	db $af
	db $fd
	dw @song2ch2loop

; Underworld
@song2ch3:
@song2ch3loop:
@ref208:
	db $7f,$94,$10,$00,$81,$73,$0b,$83,$0b,$83,$0b,$83,$7f,$96,$09,$83
	db $73,$94,$0b,$83,$0b,$83,$0b,$83
@ref209:
	db $7f,$10,$83,$7d,$01,$00,$81,$7f,$10,$83,$73,$0b,$83,$7f,$96,$09
	db $83,$73,$94,$0b,$83,$73,$0b,$83,$73,$0b,$83
@ref210:
	db $7f,$10,$00,$81,$73,$0b,$83,$0b,$83,$0b,$83,$7f,$96,$09,$83,$73
	db $94,$0b,$83,$0b,$83,$0b,$83
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $ff,$11
	dw @ref210
	db $ff,$11
	dw @ref209
	db $fd
	dw @song2ch3loop

; Underworld
@song2ch4:
@song2ch4loop:
@ref224:
	db $af
@ref225:
	db $af
@ref226:
	db $af
@ref227:
	db $af
@ref228:
	db $af
@ref229:
	db $af
@ref230:
	db $af
@ref231:
	db $af
@ref232:
	db $af
@ref233:
	db $af
@ref234:
	db $af
@ref235:
	db $af
@ref236:
	db $af
@ref237:
	db $af
@ref238:
	db $af
@ref239:
	db $af
	db $fd
	dw @song2ch4loop


; Castleworld
@song3ch0:
	db $fb,$05
@song3ch0loop:
@ref240:
	db $81,$76,$98,$1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e
	db $81,$1d
@ref241:
	db $81,$1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e,$81,$1d
@ref242:
	db $81,$74,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81
	db $29
@ref243:
	db $81,$2a,$81,$29,$81,$28,$81,$29,$81,$2a,$81,$2b,$81,$2a,$81,$29
@ref244:
	db $81,$78,$1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e,$81
	db $1d
	db $ff,$10
	dw @ref241
@ref246:
	db $81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1d,$81,$1e,$81,$1d,$81,$1c
	db $ff,$10
	dw @ref246
@ref248:
	db $81,$21,$81,$22,$81,$21,$81,$20,$81,$21,$81,$20,$81,$1f,$81,$20
	db $ff,$10
	dw @ref248
	db $ff,$10
	dw @ref244
	db $ff,$10
	dw @ref241
	db $ff,$10
	dw @ref246
	db $ff,$10
	dw @ref246
	db $ff,$10
	dw @ref248
	db $ff,$10
	dw @ref248
	db $fd
	dw @song3ch0loop

; Castleworld
@song3ch1:
@song3ch1loop:
@ref256:
	db $76,$92,$1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e,$81
	db $1d,$81
@ref257:
	db $1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e,$81,$1d,$81
@ref258:
	db $78,$1e,$81,$1d,$81,$1c,$81,$1d,$81,$1e,$81,$1f,$81,$1e,$81,$1d
	db $81
	db $ff,$10
	dw @ref257
	db $ff,$10
	dw @ref257
	db $ff,$10
	dw @ref257
@ref262:
	db $1d,$81,$1c,$81,$1d,$81,$1e,$81,$1d,$81,$1e,$81,$1d,$81,$1c,$81
	db $ff,$10
	dw @ref262
@ref264:
	db $21,$81,$22,$81,$21,$81,$20,$81,$21,$81,$20,$81,$1f,$81,$20,$81
	db $ff,$10
	dw @ref264
	db $ff,$10
	dw @ref257
	db $ff,$10
	dw @ref257
	db $ff,$10
	dw @ref262
	db $ff,$10
	dw @ref262
	db $ff,$10
	dw @ref264
	db $ff,$10
	dw @ref264
	db $fd
	dw @song3ch1loop

; Castleworld
@song3ch2:
@song3ch2loop:
@ref272:
	db $00,$9d
@ref273:
	db $9f
@ref274:
	db $9f
@ref275:
	db $9f
@ref276:
	db $80,$13,$9d
@ref277:
	db $12,$8d,$16,$8d
@ref278:
	db $15,$9d
@ref279:
	db $14,$8d,$1a,$8d
@ref280:
	db $19,$8d,$14,$8d
@ref281:
	db $13,$8d,$14,$8d
@ref282:
	db $13,$9d
@ref283:
	db $12,$8d,$16,$8d
@ref284:
	db $15,$9d
@ref285:
	db $14,$8d,$1a,$8d
@ref286:
	db $19,$8d,$14,$8d
@ref287:
	db $13,$8d,$14,$8d
	db $fd
	dw @song3ch2loop

; Castleworld
@song3ch3:
@song3ch3loop:
@ref288:
	db $76,$94,$10,$00,$8b,$96,$09,$8d
@ref289:
	db $94,$10,$00,$8b,$96,$09,$8d
@ref290:
	db $78,$94,$10,$00,$10,$00,$96,$07,$81,$78,$07,$81,$94,$10,$00,$79
	db $10,$00,$96,$07,$7a,$81,$07,$81
@ref291:
	db $7b,$94,$10,$00,$10,$7c,$00,$96,$07,$81,$07,$81,$7f,$07,$81,$07
	db $81,$07,$81,$07,$81
@ref292:
	db $94,$10,$00,$10,$00,$96,$07,$81,$07,$81,$09,$85,$07,$85
@ref293:
	db $94,$10,$00,$83,$96,$07,$85,$09,$85,$07,$85
@ref294:
	db $94,$10,$00,$83,$96,$07,$81,$07,$81,$09,$85,$07,$85
	db $ff,$09
	dw @ref293
	db $ff,$0c
	dw @ref292
	db $ff,$09
	dw @ref293
	db $ff,$0c
	dw @ref292
	db $ff,$09
	dw @ref293
	db $ff,$0b
	dw @ref294
	db $ff,$09
	dw @ref293
	db $ff,$10
	dw @ref290
	db $ff,$10
	dw @ref291
	db $fd
	dw @song3ch3loop

; Castleworld
@song3ch4:
@song3ch4loop:
@ref304:
	db $9f
@ref305:
	db $9f
@ref306:
	db $9f
@ref307:
	db $9f
@ref308:
	db $9f
@ref309:
	db $9f
@ref310:
	db $9f
@ref311:
	db $9f
@ref312:
	db $9f
@ref313:
	db $9f
@ref314:
	db $9f
@ref315:
	db $9f
@ref316:
	db $9f
@ref317:
	db $9f
@ref318:
	db $9f
@ref319:
	db $9f
	db $fd
	dw @song3ch4loop


; Starman
@song4ch0:
	db $fb,$03
@song4ch0loop:
@ref320:
	db $7a,$9c,$15,$89,$15,$89,$15,$89,$12,$83,$15,$89,$15,$89,$12,$83
	db $15,$83,$12,$83,$15,$89
@ref321:
	db $14,$89,$14,$89,$14,$89,$10,$83,$14,$89,$14,$89,$10,$83,$14,$83
	db $10,$83,$14,$89
@ref322:
	db $7a,$15,$89,$15,$89,$15,$89,$12,$83,$15,$89,$15,$89,$12,$83,$15
	db $83,$12,$83,$15,$89
	db $ff,$14
	dw @ref321
	db $ff,$14
	dw @ref322
	db $ff,$14
	dw @ref321
	db $ff,$14
	dw @ref322
	db $ff,$14
	dw @ref321
	db $fd
	dw @song4ch0loop

; Starman
@song4ch1:
@song4ch1loop:
@ref328:
	db $7d,$9c,$1c,$89,$1c,$89,$1c,$8f,$1c,$83,$00,$83,$1c,$8f,$1c,$89
	db $1c,$89
@ref329:
	db $1b,$89,$1b,$89,$1b,$8f,$1b,$83,$00,$83,$1b,$8f,$1b,$89,$1b,$89
@ref330:
	db $7d,$1c,$89,$1c,$89,$1c,$8f,$1c,$83,$00,$83,$1c,$8f,$1c,$89,$1c
	db $89
	db $ff,$10
	dw @ref329
	db $ff,$10
	dw @ref330
	db $ff,$10
	dw @ref329
	db $ff,$10
	dw @ref330
	db $ff,$10
	dw @ref329
	db $fd
	dw @song4ch1loop

; Starman
@song4ch2:
@song4ch2loop:
@ref336:
	db $80,$31,$c3,$37,$38,$95
@ref337:
	db $33,$ad,$2f,$95,$30,$95
@ref338:
	db $31,$c3,$37,$38,$95
	db $ff,$06
	dw @ref337
@ref340:
	db $12,$91,$19,$8d,$1e,$8f,$19,$8f,$1e,$89,$19,$89
@ref341:
	db $10,$8f,$17,$8f,$1c,$8f,$17,$8f,$1c,$89,$17,$89
	db $ff,$0c
	dw @ref340
@ref343:
	db $10,$8f,$17,$8f,$1c,$8f,$10,$8f,$2f,$89,$30,$89
	db $fd
	dw @song4ch2loop

; Starman
@song4ch3:
@song4ch3loop:
@ref344:
	db $86,$01,$89,$0a,$85,$0a,$81,$79,$84,$0a,$89,$7f,$86,$0a,$85,$0a
	db $81,$01,$89,$0a,$85,$0a,$81,$79,$84,$0a,$89,$7f,$86,$0a,$85,$0a
	db $81
@ref345:
	db $01,$89,$0a,$85,$0a,$81,$79,$84,$0a,$89,$7f,$86,$0a,$85,$0a,$81
	db $01,$89,$0a,$85,$0a,$81,$79,$84,$0a,$89,$7f,$86,$0a,$85,$0a,$81
	db $ff,$18
	dw @ref345
	db $ff,$18
	dw @ref345
	db $ff,$18
	dw @ref345
	db $ff,$18
	dw @ref345
	db $ff,$18
	dw @ref345
@ref351:
	db $01,$89,$0a,$85,$0a,$81,$79,$84,$0a,$89,$7f,$86,$0a,$85,$0a,$81
	db $01,$85,$01,$81,$0a,$85,$0a,$81,$79,$84,$0a,$81,$86,$01,$81,$01
	db $81,$7f,$0a,$85,$79,$84,$0a,$81
	db $fd
	dw @song4ch3loop

; Starman
@song4ch4:
@song4ch4loop:
@ref352:
	db $df
@ref353:
	db $df
@ref354:
	db $df
@ref355:
	db $df
@ref356:
	db $df
@ref357:
	db $df
@ref358:
	db $df
@ref359:
	db $df
	db $fd
	dw @song4ch4loop


; Death
@song5ch0:
	db $fb,$03
@ref360:
	db $8e,$25,$26,$27,$90,$24,$8f
@ref361:
	db $8e,$22,$83,$29,$89,$29,$83,$29,$85,$27,$85,$26,$85,$22,$83,$1f
	db $89,$1f,$83,$1b,$8f
@song5ch0loop:
@ref362:
	db $97
	db $fd
	dw @song5ch0loop

; Death
@song5ch1:
@ref363:
	db $97
@ref364:
	db $92,$27,$83,$2d,$89,$2d,$83,$2d,$85,$2c,$85,$2a,$85,$28,$a7
@song5ch1loop:
@ref365:
	db $97
	db $fd
	dw @song5ch1loop

; Death
@song5ch2:
@ref366:
	db $97
@ref367:
	db $82,$23,$8f,$23,$83,$23,$85,$25,$85,$27,$85,$28,$89,$23,$89,$1c
	db $8f
@song5ch2loop:
@ref368:
	db $97
	db $fd
	dw @song5ch2loop

; Death
@song5ch3:
@ref369:
	db $97
@ref370:
	db $d9
@song5ch3loop:
@ref371:
	db $97
	db $fd
	dw @song5ch3loop

; Death
@song5ch4:
@ref372:
	db $97
@ref373:
	db $d9
@song5ch4loop:
@ref374:
	db $97
	db $fd
	dw @song5ch4loop


; You saved the princess
@song6ch0:
	db $fb,$08
@song6ch0loop:
@ref375:
	db $7d,$8c,$27,$25,$22,$23,$89,$28,$83,$22,$83,$23,$89,$23,$83
@ref376:
	db $2a,$83,$28,$83,$2a,$83,$28,$83,$22,$83,$28,$89,$27,$83
@ref377:
	db $7d,$27,$25,$22,$23,$89,$28,$83,$22,$83,$23,$89,$23,$83
	db $ff,$0e
	dw @ref376
@ref379:
	db $2b,$81,$2b,$2b,$89,$27,$83,$2b,$83,$2e,$85,$2f,$2e,$2c,$83
@ref380:
	db $2e,$81,$2e,$31,$83,$2f,$83,$2e,$83,$2c,$83,$22,$87,$19,$2a,$83
	db $fd
	dw @song6ch0loop

; You saved the princess
@song6ch1:
@song6ch1loop:
@ref381:
	db $7d,$8c,$23,$1e,$19,$1e,$89,$20,$83,$1c,$83,$17,$89,$1b,$83
@ref382:
	db $1e,$81,$1e,$1c,$83,$1e,$83,$20,$83,$19,$83,$1c,$89,$1b,$83
@ref383:
	db $7d,$23,$1e,$19,$1e,$89,$20,$83,$1c,$83,$17,$89,$1b,$83
	db $ff,$0f
	dw @ref382
@ref385:
	db $22,$81,$22,$22,$89,$1f,$83,$22,$83,$25,$85,$27,$25,$23,$83
@ref386:
	db $25,$81,$25,$28,$83,$27,$83,$25,$83,$23,$83,$25,$87,$25,$25,$83
	db $fd
	dw @song6ch1loop

; You saved the princess
@song6ch2:
@song6ch2loop:
@ref387:
	db $8c,$12,$12,$12,$17,$83,$17,$17,$17,$17,$83,$17,$83,$17,$83,$17
	db $17,$17,$17,$83
@ref388:
	db $17,$83,$1c,$83,$1c,$1c,$1c,$19,$83,$19,$19,$19,$1e,$83,$12,$1e
	db $12,$17,$83
@ref389:
	db $12,$12,$12,$17,$83,$17,$17,$17,$17,$83,$17,$83,$17,$83,$17,$17
	db $17,$17,$83
	db $ff,$13
	dw @ref388
@ref391:
	db $1b,$1b,$1b,$22,$83,$20,$83,$1f,$83,$1b,$83,$20,$83,$14,$20,$14
	db $20,$83
@ref392:
	db $20,$20,$20,$25,$83,$23,$83,$22,$83,$20,$83,$1e,$2a,$12,$1e,$2a
	db $12,$1e,$2a,$12
	db $fd
	dw @song6ch2loop

; You saved the princess
@song6ch3:
@song6ch3loop:
@ref393:
	db $af
@ref394:
	db $af
@ref395:
	db $af
@ref396:
	db $af
@ref397:
	db $af
@ref398:
	db $af
	db $fd
	dw @song6ch3loop

; You saved the princess
@song6ch4:
@song6ch4loop:
@ref399:
	db $af
@ref400:
	db $af
@ref401:
	db $af
@ref402:
	db $af
@ref403:
	db $af
@ref404:
	db $af
	db $fd
	dw @song6ch4loop


; In an other castle
@song7ch0:
	db $fb,$04
@ref405:
	db $8c,$18,$81,$14,$81,$0f,$81,$18,$81,$14,$81,$0f,$81,$18,$81,$88
	db $18,$18,$18,$81,$8c,$18,$81,$18,$81,$18,$81,$19,$81,$15,$81,$10
	db $81,$19,$81,$15,$81,$10,$81,$19,$81,$88,$19,$19,$19,$81,$19,$81
	db $19,$81,$19,$81,$8c,$1b,$81,$17,$81,$12,$81,$1b,$81,$17,$81,$12
	db $81,$1b,$81,$1b,$88,$1b,$1b,$1c,$8c,$1d,$83,$1d,$83,$1d,$89,$00
	db $87,$1d,$1e,$1f,$97,$00
@song7ch0loop:
@ref406:
	db $99
	db $fd
	dw @song7ch0loop

; In an other castle
@song7ch1:
@ref407:
	db $8c,$20,$81,$1b,$81,$18,$81,$20,$81,$1b,$81,$18,$81,$20,$95,$21
	db $81,$1c,$81,$19,$81,$21,$81,$1c,$81,$19,$81,$21,$95,$23,$81,$1e
	db $81,$1b,$81,$23,$81,$1e,$81,$1b,$81,$23,$89,$25,$83,$25,$83,$25
	db $89,$00,$87,$25,$26,$27,$97,$00
@song7ch1loop:
@ref408:
	db $99
	db $fd
	dw @song7ch1loop

; In an other castle
@song7ch2:
@ref409:
	db $8a,$14,$97,$00,$14,$14,$14,$00,$14,$00,$14,$00,$14,$00,$15,$97
	db $00,$15,$15,$15,$00,$15,$00,$15,$00,$15,$00,$1e,$00,$1b,$00,$17
	db $00,$1e,$00,$1b,$00,$17,$00,$1e,$00,$1e,$1e,$1e,$00,$20,$00,$81
	db $20,$00,$81,$20,$89,$00,$87,$20,$21,$22,$97,$00
@song7ch2loop:
@ref410:
	db $99
	db $fd
	dw @song7ch2loop

; In an other castle
@song7ch3:
@ref411:
	db $96,$05,$00,$05,$00,$01,$00,$01,$00,$0f,$00,$01,$00,$05,$00,$01
	db $00,$01,$00,$01,$00,$0f,$00,$01,$00,$05,$00,$05,$00,$01,$00,$01
	db $00,$0f,$00,$01,$00,$05,$00,$01,$00,$01,$00,$01,$00,$0f,$00,$01
	db $00,$05,$00,$05,$00,$01,$00,$01,$00,$0f,$00,$01,$00,$05,$00,$01
	db $00,$01,$00,$03,$00,$81,$03,$81,$00,$03,$91,$73,$03,$73,$03,$73
	db $03,$75,$03,$76,$03,$77,$03,$78,$03,$79,$03,$7a,$03,$7a,$03,$7a
	db $03,$7a,$03,$76,$03,$75,$03,$74,$03,$81,$7a,$03
@song7ch3loop:
@ref412:
	db $99
	db $fd
	dw @song7ch3loop

; In an other castle
@song7ch4:
@ref413:
	db $f9,$cb
@song7ch4loop:
@ref414:
	db $99
	db $fd
	dw @song7ch4loop


; Victory
@song8ch0:
	db $fb,$04
@ref415:
	db $9c,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$81,$2c,$81,$2f,$89,$2c
	db $89,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$81,$2b,$81,$30,$89,$2b
	db $89
@ref416:
	db $1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$81,$2d,$81,$32,$89,$32,$81
	db $32,$81,$32,$81,$2c,$8f,$00,$9b
@song8ch0loop:
@ref417:
	db $af
	db $fd
	dw @song8ch0loop

; Victory
@song8ch1:
@ref418:
	db $00,$81,$9c,$14,$81,$17,$81,$1c,$81,$20,$81,$23,$81,$28,$89,$23
	db $89,$00,$81,$13,$81,$18,$81,$1c,$81,$1f,$81,$24,$81,$28,$89,$24
	db $89
@ref419:
	db $00,$81,$15,$81,$1a,$81,$1e,$81,$21,$81,$26,$81,$2a,$89,$2a,$89
	db $34,$8f,$00,$9b
@song8ch1loop:
@ref420:
	db $af
	db $fd
	dw @song8ch1loop

; Victory
@song8ch2:
@ref421:
	db $8b,$80,$1c,$81,$20,$81,$23,$81,$2c,$89,$28,$81,$00,$91,$1c,$81
	db $1f,$81,$24,$81,$2b,$89,$28,$81,$00,$85
@ref422:
	db $8b,$1e,$81,$21,$81,$26,$81,$2d,$89,$2a,$89,$28,$8f,$00,$9b
@song8ch2loop:
@ref423:
	db $af
	db $fd
	dw @song8ch2loop

; Victory
@song8ch3:
@ref424:
	db $df
@ref425:
	db $df
@song8ch3loop:
@ref426:
	db $af
	db $fd
	dw @song8ch3loop

; Victory
@song8ch4:
@ref427:
	db $df
@ref428:
	db $df
@song8ch4loop:
@ref429:
	db $af
	db $fd
	dw @song8ch4loop


; Hurry up
@song9ch0:
	db $fb,$02
@ref430:
	db $8a,$14,$81,$24,$81,$00,$24,$81,$24,$83,$00,$15,$81,$25,$83,$00
	db $25,$81,$25,$83,$00,$16,$81,$26,$83,$00,$26,$81,$26,$83,$00,$27
	db $83,$00,$27,$9b,$00,$81
@song9ch0loop:
@ref431:
	db $83
	db $fd
	dw @song9ch0loop

; Hurry up
@song9ch1:
@ref432:
	db $8a,$20,$81,$2a,$83,$2a,$81,$2a,$85,$21,$81,$2b,$85,$2b,$81,$2b
	db $85,$22,$81,$2c,$85,$2c,$81,$2c,$85,$2d,$83,$00,$2d,$9b,$00,$81
@song9ch1loop:
@ref433:
	db $83
	db $fd
	dw @song9ch1loop

; Hurry up
@song9ch2:
@ref434:
	db $82,$27,$81,$33,$83,$33,$81,$33,$85,$28,$81,$34,$85,$34,$81,$34
	db $85,$29,$81,$35,$85,$35,$81,$35,$85,$23,$85,$80,$23,$9b,$00,$81
@song9ch2loop:
@ref435:
	db $83
	db $fd
	dw @song9ch2loop

; Hurry up
@song9ch3:
@ref436:
	db $ef
@song9ch3loop:
@ref437:
	db $83
	db $fd
	dw @song9ch3loop

; Hurry up
@song9ch4:
@ref438:
	db $ef
@song9ch4loop:
@ref439:
	db $83
	db $fd
	dw @song9ch4loop


; W2
@song10ch0:
	db $fb,$04
@song10ch0loop:
@ref440:
	db $8b,$88,$2c,$98,$2f,$81,$88,$2b,$98,$2e,$81,$88,$2a,$98,$2d,$81
	db $88,$27,$98,$2b,$87,$88,$28,$98,$2c,$87,$88,$20,$98,$24,$81,$88
	db $21,$98,$25,$81,$88,$23,$98,$28,$87,$88,$1c,$98,$25,$81,$88,$20
	db $98,$28,$81,$88,$21,$98,$2a,$81
@ref441:
	db $8b,$88,$2c,$98,$2f,$81,$88,$2b,$98,$2e,$81,$88,$2a,$98,$2d,$81
	db $88,$27,$98,$2b,$87,$88,$28,$98,$2c,$87,$88,$2d,$98,$34,$87,$88
	db $2d,$98,$34,$81,$88,$2d,$98,$34,$93
	db $ff,$22
	dw @ref440
	db $ff,$19
	dw @ref441
@ref444:
	db $df
@ref445:
	db $df
	db $fd
	dw @song10ch0loop

; W2
@song10ch1:
@song10ch1loop:
@ref446:
	db $8b,$88,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$24,$83,$25,$83
	db $28,$89,$25,$83,$28,$83,$2a,$83
@ref447:
	db $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$34,$89,$34,$83,$34
	db $95
@ref448:
	db $8b,$2f,$83,$2e,$83,$2d,$83,$2b,$89,$2c,$89,$24,$83,$25,$83,$28
	db $89,$25,$83,$28,$83,$2a,$83
	db $ff,$11
	dw @ref447
@ref450:
	db $df
@ref451:
	db $df
	db $fd
	dw @song10ch1loop

; W2
@song10ch2:
@song10ch2loop:
@ref452:
	db $88,$10,$8f,$17,$8f,$1c,$89,$15,$8f,$1c,$83,$1c,$89,$15,$89
@ref453:
	db $10,$8f,$17,$8f,$1c,$89,$15,$8f,$15,$83,$15,$89,$17,$89
	db $ff,$0e
	dw @ref53
	db $ff,$0e
	dw @ref453
	db $ff,$0e
	dw @ref53
	db $ff,$0e
	dw @ref453
	db $fd
	dw @song10ch2loop

; W2
@song10ch3:
@song10ch3loop:
@ref458:
	db $86,$02,$8f,$02,$8f,$02,$89,$02,$8f,$02,$83,$02,$89,$02,$89
@ref459:
	db $02,$83,$02,$89,$02,$83,$94,$02,$89,$05,$89,$86,$02,$8f,$94,$05
	db $83,$05,$83,$02,$83,$05,$89
	db $ff,$0e
	dw @ref458
	db $ff,$14
	dw @ref459
	db $ff,$0e
	dw @ref458
	db $ff,$14
	dw @ref459
	db $fd
	dw @song10ch3loop

; W2
@song10ch4:
@song10ch4loop:
@ref464:
	db $df
@ref465:
	db $df
@ref466:
	db $df
@ref467:
	db $df
@ref468:
	db $df
@ref469:
	db $df
	db $fd
	dw @song10ch4loop


; W3
@song11ch0:
	db $fb,$02
@song11ch0loop:
@ref470:
	db $f9,$85
@ref471:
	db $f9,$85
@ref472:
	db $f9,$85
@ref473:
	db $f9,$85
@ref474:
	db $7f,$88,$25,$95,$76,$25,$95,$74,$25,$95,$73,$25,$95,$72,$25,$8d
	db $71,$25,$8d
@ref475:
	db $7f,$23,$95,$76,$23,$95,$74,$23,$95,$73,$23,$95,$72,$23,$8d,$71
	db $23,$8d
@ref476:
	db $7f,$25,$95,$76,$25,$95,$74,$25,$95,$73,$25,$95,$72,$25,$8d,$71
	db $25,$8d
	db $ff,$0c
	dw @ref475
@ref478:
	db $f9,$85
@ref479:
	db $f9,$85
@ref480:
	db $f9,$85
@ref481:
	db $f9,$85
	db $ff,$0c
	dw @ref476
	db $ff,$0c
	dw @ref475
	db $ff,$0c
	dw @ref476
	db $ff,$0c
	dw @ref475
@ref486:
	db $7f,$21,$95,$76,$21,$95,$74,$21,$95,$73,$21,$95,$72,$21,$8d,$71
	db $21,$8d
@ref487:
	db $7f,$24,$95,$76,$24,$95,$74,$24,$95,$73,$24,$95,$72,$24,$8d,$71
	db $24,$8d
	db $ff,$0c
	dw @ref486
@ref489:
	db $7f,$24,$85,$7f,$24,$8d,$7f,$26,$85,$7f,$26,$8d,$7f,$28,$85,$7f
	db $28,$93,$7f,$2b,$8d,$7f,$2b,$9f
	db $fd
	dw @song11ch0loop

; W3
@song11ch1:
@song11ch1loop:
@ref490:
	db $f9,$85
@ref491:
	db $f9,$85
@ref492:
	db $f9,$85
@ref493:
	db $f9,$85
@ref494:
	db $7f,$88,$2a,$95,$78,$2a,$95,$76,$2a,$95,$74,$2a,$95,$72,$2a,$8d
	db $71,$2a,$8d
@ref495:
	db $7f,$28,$95,$78,$28,$95,$76,$28,$95,$74,$28,$95,$72,$28,$8d,$71
	db $28,$8d
@ref496:
	db $7f,$2a,$95,$78,$2a,$95,$76,$2a,$95,$74,$2a,$95,$72,$2a,$8d,$71
	db $2a,$8d
	db $ff,$0c
	dw @ref495
@ref498:
	db $f9,$85
@ref499:
	db $f9,$85
@ref500:
	db $f9,$85
@ref501:
	db $f9,$85
	db $ff,$0c
	dw @ref496
	db $ff,$0c
	dw @ref495
	db $ff,$0c
	dw @ref496
	db $ff,$0c
	dw @ref495
@ref506:
	db $7f,$26,$95,$78,$26,$95,$76,$26,$95,$74,$26,$95,$72,$26,$8d,$71
	db $26,$8d
@ref507:
	db $7f,$29,$95,$78,$29,$95,$76,$29,$95,$74,$29,$95,$72,$29,$8d,$71
	db $29,$8d
	db $ff,$0c
	dw @ref506
@ref509:
	db $7f,$29,$85,$7f,$29,$8d,$7f,$2b,$85,$7f,$2b,$8d,$7f,$2d,$85,$7f
	db $2d,$93,$7f,$30,$8d,$7f,$30,$9f
	db $fd
	dw @song11ch1loop

; W3
@song11ch2:
@song11ch2loop:
@ref510:
	db $8a,$17,$8d,$00,$85,$1e,$93,$00,$23,$95,$17,$95,$23,$8b,$81,$1e
	db $8d
@ref511:
	db $15,$8d,$00,$85,$1c,$93,$00,$21,$95,$15,$95,$21,$8d,$1c,$8d
@ref512:
	db $17,$8d,$00,$85,$1e,$93,$00,$23,$95,$17,$95,$23,$8b,$81,$1e,$8d
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
	db $ff,$10
	dw @ref512
	db $ff,$0f
	dw @ref511
@ref526:
	db $13,$8d,$00,$85,$1a,$93,$00,$1f,$95,$13,$95,$1f,$8b,$81,$1a,$8d
@ref527:
	db $11,$8d,$00,$85,$18,$93,$00,$1d,$95,$11,$95,$1d,$8d,$18,$8d
	db $ff,$10
	dw @ref526
	db $ff,$0f
	dw @ref527
	db $fd
	dw @song11ch2loop

; W3
@song11ch3:
@song11ch3loop:
@ref530:
	db $7f,$94,$10,$81,$00,$89,$77,$06,$87,$02,$83,$79,$09,$81,$77,$00
	db $89,$02,$87,$02,$83,$02,$8d,$02,$87,$02,$83,$79,$09,$81,$77,$00
	db $83,$02,$83,$79,$09,$81,$77,$00,$83,$02,$83
@ref531:
	db $7f,$10,$81,$00,$89,$77,$02,$87,$02,$83,$79,$09,$81,$77,$00,$89
	db $02,$87,$02,$83,$02,$8d,$02,$87,$02,$83,$79,$09,$81,$77,$00,$83
	db $02,$83,$79,$09,$81,$77,$00,$83,$02,$83
@ref532:
	db $7f,$10,$81,$00,$89,$77,$06,$87,$02,$83,$79,$09,$81,$77,$00,$89
	db $02,$87,$02,$83,$02,$8d,$02,$87,$02,$83,$79,$09,$81,$77,$00,$83
	db $02,$83,$79,$09,$81,$77,$00,$83,$02,$83
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $ff,$22
	dw @ref532
	db $ff,$22
	dw @ref531
	db $fd
	dw @song11ch3loop

; W3
@song11ch4:
@song11ch4loop:
@ref550:
	db $f9,$85
@ref551:
	db $f9,$85
@ref552:
	db $f9,$85
@ref553:
	db $f9,$85
@ref554:
	db $f9,$85
@ref555:
	db $f9,$85
@ref556:
	db $f9,$85
@ref557:
	db $f9,$85
@ref558:
	db $f9,$85
@ref559:
	db $f9,$85
@ref560:
	db $f9,$85
@ref561:
	db $f9,$85
@ref562:
	db $f9,$85
@ref563:
	db $f9,$85
@ref564:
	db $f9,$85
@ref565:
	db $f9,$85
@ref566:
	db $f9,$85
@ref567:
	db $f9,$85
@ref568:
	db $f9,$85
@ref569:
	db $f9,$85
	db $fd
	dw @song11ch4loop


; W4
@song12ch0:
	db $fb,$03
@song12ch0loop:
@ref570:
	db $df
@ref571:
	db $df
@ref572:
	db $88,$20,$8f,$1c,$8f,$17,$8f,$1c,$89,$1e,$89,$1d,$83,$1c,$89
@ref573:
	db $20,$8f,$1c,$8f,$17,$8f,$1c,$89,$1e,$89,$1d,$83,$1c,$89
@ref574:
	db $20,$b3,$20,$83,$1c,$89,$1e,$95
@ref575:
	db $df
@ref576:
	db $df
	db $ff,$0e
	dw @ref573
	db $ff,$0e
	dw @ref573
	db $ff,$08
	dw @ref574
	db $fd
	dw @song12ch0loop

; W4
@song12ch1:
@song12ch1loop:
@ref580:
	db $df
@ref581:
	db $df
@ref582:
	db $88,$1c,$8f,$17,$8f,$14,$8f,$19,$89,$1b,$89,$1a,$83,$19,$89
	db $ff,$0e
	dw @ref25
@ref584:
	db $1c,$b3,$1c,$83,$19,$89,$1b,$95
@ref585:
	db $df
@ref586:
	db $df
	db $ff,$0e
	dw @ref25
	db $ff,$0e
	dw @ref25
	db $ff,$08
	dw @ref584
	db $fd
	dw @song12ch1loop

; W4
@song12ch2:
@song12ch2loop:
	db $ff,$0e
	dw @ref51
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $ff,$0e
	dw @ref49
	db $fd
	dw @song12ch2loop

; W4
@song12ch3:
@song12ch3loop:
@ref600:
	db $79,$94,$0b,$89,$0b,$83,$0b,$89,$0b,$83,$0b,$89,$0b,$8f,$0b,$89
	db $0b,$83,$0b,$83,$0b,$83
@ref601:
	db $79,$0b,$89,$0b,$83,$0b,$89,$0b,$83,$0b,$89,$0b,$8f,$0b,$89,$0b
	db $83,$0b,$83,$0b,$83
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $ff,$14
	dw @ref601
	db $fd
	dw @song12ch3loop

; W4
@song12ch4:
@song12ch4loop:
@ref610:
	db $df
@ref611:
	db $df
@ref612:
	db $df
@ref613:
	db $df
@ref614:
	db $df
@ref615:
	db $df
@ref616:
	db $df
@ref617:
	db $df
@ref618:
	db $df
@ref619:
	db $df
	db $fd
	dw @song12ch4loop


; W5
@song13ch0:
	db $fb,$04
@song13ch0loop:
@ref620:
	db $85,$9e,$2c,$9d,$2a,$9d,$2d,$b7
@ref621:
	db $85,$2c,$9d,$2a,$9d,$2d,$b7
	db $ff,$07
	dw @ref621
	db $ff,$07
	dw @ref621
@ref624:
	db $85,$2d,$9d,$2b,$9d,$2e,$b7
	db $ff,$07
	dw @ref621
	db $ff,$07
	dw @ref621
	db $fd
	dw @song13ch0loop

; W5
@song13ch1:
@song13ch1loop:
@ref627:
	db $9e,$38,$9d,$36,$9d,$39,$bd
@ref628:
	db $38,$9d,$36,$9d,$39,$bd
	db $ff,$06
	dw @ref628
	db $ff,$06
	dw @ref628
@ref631:
	db $39,$9d,$37,$9d,$3a,$bd
	db $ff,$06
	dw @ref628
	db $ff,$06
	dw @ref628
	db $fd
	dw @song13ch1loop

; W5
@song13ch2:
@song13ch2loop:
@ref634:
	db $f9,$85
@ref635:
	db $f9,$85
@ref636:
	db $80,$20,$9d,$1e,$9d,$21,$9d,$00,$9d
@ref637:
	db $20,$9d,$1e,$9d,$21,$9d,$00,$9d
@ref638:
	db $21,$9d,$1f,$9d,$22,$9d,$00,$9d
@ref639:
	db $f9,$85
@ref640:
	db $f9,$85
	db $fd
	dw @song13ch2loop

; W5
@song13ch3:
@song13ch3loop:
@ref641:
	db $f9,$85
@ref642:
	db $f9,$85
@ref643:
	db $98,$10,$10,$10,$89,$0e,$8d,$10,$85,$10,$85,$0e,$8d,$10,$10,$10
	db $89,$0e,$8d,$10,$85,$10,$85,$0e,$8d
@ref644:
	db $10,$10,$10,$89,$0e,$8d,$10,$85,$10,$85,$0e,$8d,$10,$10,$10,$89
	db $0e,$8d,$10,$85,$10,$85,$0e,$8d
	db $ff,$18
	dw @ref644
	db $ff,$18
	dw @ref644
	db $ff,$18
	dw @ref644
	db $fd
	dw @song13ch3loop

; W5
@song13ch4:
@song13ch4loop:
@ref648:
	db $f9,$85
@ref649:
	db $f9,$85
@ref650:
	db $f9,$85
@ref651:
	db $f9,$85
@ref652:
	db $f9,$85
@ref653:
	db $f9,$85
@ref654:
	db $f9,$85
	db $fd
	dw @song13ch4loop


; W6
@song14ch0:
	db $fb,$08
@song14ch0loop:
@ref655:
	db $87,$9c,$18,$85,$15,$8d,$14,$85,$14,$81,$15,$91
@ref656:
	db $87,$18,$85,$15,$8d,$14,$85,$14,$81,$15,$91
	db $ff,$0b
	dw @ref656
	db $ff,$0b
	dw @ref656
@ref659:
	db $87,$1d,$85,$1a,$8d,$19,$85,$19,$81,$1a,$91
	db $ff,$0b
	dw @ref659
	db $fd
	dw @song14ch0loop

; W6
@song14ch1:
@song14ch1loop:
@ref661:
	db $87,$9c,$13,$85,$10,$8d,$0f,$85,$0f,$81,$10,$91
@ref662:
	db $87,$13,$85,$10,$8d,$0f,$85,$0f,$81,$10,$91
	db $ff,$0b
	dw @ref662
	db $ff,$0b
	dw @ref662
	db $ff,$0b
	dw @ref656
	db $ff,$0b
	dw @ref656
	db $fd
	dw @song14ch1loop

; W6
@song14ch2:
@song14ch2loop:
@ref667:
	db $82,$21,$21,$87,$21,$21,$83,$1c,$81,$1f,$81,$20,$81,$21,$21,$87
	db $21,$21,$83,$1c,$81,$1f,$81,$20,$81
@ref668:
	db $21,$21,$87,$21,$21,$83,$1c,$81,$1f,$81,$20,$81,$21,$21,$87,$21
	db $21,$83,$1c,$81,$1f,$81,$20,$81
	db $ff,$18
	dw @ref668
@ref670:
	db $21,$21,$87,$21,$21,$83,$1c,$81,$1f,$81,$20,$81,$21,$21,$87,$21
	db $21,$83,$21,$81,$24,$81,$25,$81
@ref671:
	db $26,$26,$87,$26,$26,$83,$21,$81,$24,$81,$25,$81,$26,$26,$87,$26
	db $26,$83,$21,$81,$24,$81,$25,$81
	db $ff,$18
	dw @ref671
	db $fd
	dw @song14ch2loop

; W6
@song14ch3:
@song14ch3loop:
@ref673:
	db $7f,$9a,$0f,$81,$7f,$0f,$81,$7f,$0f,$81,$77,$06,$81,$7f,$0f,$81
	db $77,$06,$81,$77,$06,$81,$77,$06,$81,$7f,$0f,$81,$77,$06,$81,$7f
	db $0f,$81,$77,$06,$81,$7f,$0f,$81,$77,$06,$81,$77,$06,$81,$77,$06
	db $81
@ref674:
	db $7f,$0f,$81,$7f,$0f,$81,$7f,$0f,$81,$77,$06,$81,$7f,$0f,$81,$77
	db $06,$81,$77,$06,$81,$77,$06,$81,$7f,$0f,$81,$77,$06,$81,$7f,$0f
	db $81,$77,$06,$81,$7f,$0f,$81,$77,$06,$81,$77,$06,$81,$77,$06,$81
	db $ff,$20
	dw @ref674
	db $ff,$20
	dw @ref674
	db $ff,$20
	dw @ref674
	db $ff,$20
	dw @ref674
	db $fd
	dw @song14ch3loop

; W6
@song14ch4:
@song14ch4loop:
@ref679:
	db $bf
@ref680:
	db $bf
@ref681:
	db $bf
@ref682:
	db $bf
@ref683:
	db $bf
@ref684:
	db $bf
	db $fd
	dw @song14ch4loop


; W7
@song15ch0:
	db $fb,$08
@song15ch0loop:
@ref685:
	db $7f,$9e,$23,$85,$2f,$8d,$23,$85,$24,$85,$30,$8d,$32,$85
@ref686:
	db $2f,$85,$23,$8d,$2f,$85,$2d,$85,$24,$8d,$26,$81,$25,$24
@ref687:
	db $7f,$23,$85,$2f,$8d,$23,$85,$24,$85,$30,$8d,$32,$85
	db $ff,$0e
	dw @ref686
@ref689:
	db $20,$85,$2c,$8d,$20,$85,$21,$85,$2d,$8d,$2f,$85
@ref690:
	db $2c,$85,$20,$8d,$2c,$85,$29,$85,$21,$8d,$20,$85
@ref691:
	db $00,$bd
@ref692:
	db $bf
	db $ff,$0c
	dw @ref687
	db $ff,$0e
	dw @ref686
	db $ff,$0c
	dw @ref687
	db $ff,$0e
	dw @ref686
@ref697:
	db $00,$bd
@ref698:
	db $bf
	db $fd
	dw @song15ch0loop

; W7
@song15ch1:
@song15ch1loop:
@ref699:
	db $7f,$9e,$20,$85,$2c,$8d,$20,$85,$21,$85,$2d,$8d,$2f,$85
@ref700:
	db $2c,$85,$20,$8d,$2c,$85,$29,$85,$21,$8d,$21,$85
@ref701:
	db $7f,$20,$85,$2c,$8d,$20,$85,$21,$85,$2d,$8d,$2f,$85
	db $ff,$0c
	dw @ref700
@ref703:
	db $2f,$81,$28,$85,$2f,$85,$28,$81,$2c,$81,$2f,$81,$29,$81,$2d,$81
	db $32,$81,$30,$91
@ref704:
	db $78,$2f,$81,$28,$85,$2f,$85,$28,$81,$2c,$81,$2f,$81,$29,$81,$2d
	db $81,$32,$81,$30,$89,$2f,$85
@ref705:
	db $20,$bd
@ref706:
	db $bf
	db $ff,$0c
	dw @ref701
	db $ff,$0c
	dw @ref700
	db $ff,$0c
	dw @ref701
	db $ff,$0c
	dw @ref700
@ref711:
	db $20,$bd
@ref712:
	db $bf
	db $fd
	dw @song15ch1loop

; W7
@song15ch2:
@song15ch2loop:
@ref713:
	db $82,$1c,$81,$23,$81,$23,$81,$28,$81,$28,$81,$2c,$81,$2c,$81,$2f
	db $81,$1d,$81,$24,$81,$24,$81,$29,$81,$29,$81,$2d,$81,$2d,$81,$30
	db $81
@ref714:
	db $1c,$81,$23,$81,$23,$81,$28,$81,$28,$81,$2c,$81,$2c,$81,$2f,$81
	db $1d,$81,$24,$81,$24,$81,$29,$81,$29,$81,$2d,$81,$2d,$81,$30,$81
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
@ref721:
	db $10,$81,$17,$81,$17,$81,$1c,$81,$1c,$81,$20,$81,$20,$81,$23,$81
	db $11,$81,$18,$81,$18,$81,$1d,$81,$1d,$81,$21,$81,$21,$81,$24,$81
	db $ff,$20
	dw @ref721
	db $ff,$20
	dw @ref721
	db $ff,$20
	dw @ref721
	db $ff,$20
	dw @ref714
	db $ff,$20
	dw @ref714
	db $fd
	dw @song15ch2loop

; W7
@song15ch3:
@song15ch3loop:
@ref727:
	db $bf
@ref728:
	db $bf
@ref729:
	db $bf
@ref730:
	db $bf
@ref731:
	db $bf
@ref732:
	db $bf
@ref733:
	db $bf
@ref734:
	db $bf
@ref735:
	db $bf
@ref736:
	db $bf
@ref737:
	db $bf
@ref738:
	db $bf
@ref739:
	db $bf
@ref740:
	db $bf
	db $fd
	dw @song15ch3loop

; W7
@song15ch4:
@song15ch4loop:
@ref741:
	db $bf
@ref742:
	db $bf
@ref743:
	db $bf
@ref744:
	db $bf
@ref745:
	db $bf
@ref746:
	db $bf
@ref747:
	db $bf
@ref748:
	db $bf
@ref749:
	db $bf
@ref750:
	db $bf
@ref751:
	db $bf
@ref752:
	db $bf
@ref753:
	db $bf
@ref754:
	db $bf
	db $fd
	dw @song15ch4loop


; W8
@song16ch0:
	db $fb,$05
@ref755:
	db $a0,$25,$81,$24,$81,$23,$81,$22,$a1
@ref756:
	db $08,$81,$14,$81,$19,$81,$14,$81,$19,$81,$18,$81,$70,$83,$7f,$14
	db $81,$17,$81,$70,$83,$7f,$14,$81,$17,$81,$70,$83,$7f,$16,$81,$17
	db $81,$18,$81
@song16ch0loop:
@ref757:
	db $a0,$08,$81,$14,$81,$19,$81,$14,$81,$19,$81,$18,$81,$70,$83,$7f
	db $14,$81,$17,$81,$70,$83,$7f,$14,$81,$17,$81,$70,$83,$7f,$16,$81
	db $17,$81,$18,$81
	db $ff,$1d
	dw @ref756
	db $ff,$1d
	dw @ref756
	db $ff,$1d
	dw @ref756
@ref761:
	db $09,$81,$15,$81,$1a,$81,$15,$81,$1a,$81,$19,$81,$70,$83,$7f,$15
	db $81,$18,$81,$70,$83,$7f,$15,$81,$18,$81,$70,$83,$7f,$17,$81,$18
	db $81,$19,$81
	db $ff,$1d
	dw @ref761
	db $fd
	dw @song16ch0loop

; W8
@song16ch1:
@ref763:
	db $a0,$1c,$81,$1b,$81,$1a,$81,$19,$a1
@ref764:
	db $08,$81,$14,$81,$1e,$81,$14,$81,$1e,$81,$1d,$81,$70,$83,$7f,$14
	db $81,$1c,$81,$70,$83,$7f,$14,$81,$1c,$81,$70,$83,$7f,$1b,$81,$1c
	db $81,$1d,$81
@song16ch1loop:
@ref765:
	db $a0,$08,$81,$14,$81,$1e,$81,$14,$81,$1e,$81,$1d,$81,$70,$83,$7f
	db $14,$81,$1c,$81,$70,$83,$7f,$14,$81,$1c,$81,$70,$83,$7f,$1b,$81
	db $1c,$81,$1d,$81
	db $ff,$1d
	dw @ref764
	db $ff,$1d
	dw @ref764
	db $ff,$1d
	dw @ref764
@ref769:
	db $09,$81,$15,$81,$1f,$81,$15,$81,$1f,$81,$1e,$81,$70,$83,$7f,$15
	db $81,$1d,$81,$70,$83,$7f,$15,$81,$1d,$81,$70,$83,$7f,$1c,$81,$1d
	db $81,$1e,$81
	db $ff,$1d
	dw @ref769
	db $fd
	dw @song16ch1loop

; W8
@song16ch2:
@ref771:
	db $a0,$22,$81,$21,$81,$20,$81,$1f,$9d,$1f,$81
@ref772:
	db $00,$bd
@song16ch2loop:
@ref773:
	db $87,$80,$33,$99,$94,$33,$89,$80,$32,$31,$94,$2f,$81,$80,$31,$81
	db $2c,$81
@ref774:
	db $83,$2f,$85,$2a,$85,$27,$81,$2a,$81,$2c,$81,$00,$9d
@ref775:
	db $87,$33,$99,$94,$33,$89,$80,$32,$31,$94,$2f,$81,$80,$31,$81,$2c
	db $81
	db $ff,$0d
	dw @ref774
@ref777:
	db $87,$34,$a9,$33,$81,$34,$81,$39,$81
@ref778:
	db $37,$81,$33,$81,$32,$81,$30,$81,$32,$33,$32,$30,$32,$81,$2d,$81
	db $30,$81,$2d,$81,$2b,$81,$2d,$89,$00,$85
	db $fd
	dw @song16ch2loop

; W8
@song16ch3:
@ref779:
	db $7e,$98,$0c,$85,$0c,$81,$0c,$85,$0c,$81,$0c,$81,$0c,$81,$0c,$81
	db $0c,$81,$0c,$81,$0c,$81
@ref780:
	db $9e,$01,$81,$94,$0d,$81,$7f,$0e,$81,$7e,$0d,$81,$0d,$81,$0d,$81
	db $7f,$0e,$81,$7e,$0d,$81,$9e,$02,$81,$94,$0d,$81,$7f,$0e,$81,$7e
	db $9e,$02,$81,$94,$0d,$81,$0d,$81,$7f,$9e,$02,$81,$7e,$94,$0d,$81
@song16ch3loop:
	db $ff,$20
	dw @ref780
	db $ff,$20
	dw @ref780
	db $ff,$20
	dw @ref780
	db $ff,$20
	dw @ref780
	db $ff,$20
	dw @ref780
	db $ff,$20
	dw @ref780
	db $fd
	dw @song16ch3loop

; W8
@song16ch4:
@ref787:
	db $af
@ref788:
	db $bf
@song16ch4loop:
@ref789:
	db $bf
@ref790:
	db $bf
@ref791:
	db $bf
@ref792:
	db $bf
@ref793:
	db $bf
@ref794:
	db $bf
	db $fd
	dw @song16ch4loop
